import type { VocabPack } from "./types";

/**
 * English Vocabulary in Use — Elementary (Cambridge, ấn bản 3).
 *
 * ĐÂY CHỈ LÀ DANH SÁCH TỪ, rút từ mục lục tra cứu cuối sách: mỗi mục gồm từ,
 * phiên âm, và số bài. Bản thân từ vựng và cách phiên âm là DỮ KIỆN về tiếng
 * Anh — không ai sở hữu chữ "grandmother" hay cách nó được đọc.
 *
 * KHÔNG chép bất cứ thứ gì thuộc phần diễn đạt của sách: không lời giải thích,
 * không câu ví dụ, không bài tập, không hình minh hoạ. Nghĩa và câu ví dụ trong
 * giáo trình sinh ra ở phía ứng dụng, không lấy từ sách.
 *
 * Dùng để đi theo đúng trình tự chủ đề của sách trong khi tự học. Ai muốn phần
 * giảng giải và bài tập thì vẫn phải mua sách — và nên mua.
 *
 * Tự sinh từ PDF người dùng cung cấp; 1699 từ trên 60 bài.
 */
export const EVU_ELEMENTARY: VocabPack = {
  id: "evu-elementary",
  title: "English Vocabulary in Use Elementary",
  langCode: "en",
  level: "A2",
  note: "Theo đúng trình tự 60 bài của sách. Nghĩa và ví dụ do ứng dụng soạn.",
  units: [
  {
    unit: 1,
    section: "People",
    title: "The family",
    words: [
      { term: "aunt", ipa: "ɑːnt" },
      { term: "brother", ipa: "ˈbrʌðə" },
      { term: "children", ipa: "ˈtʃɪldrən" },
      { term: "cousin", ipa: "ˈkʌzən" },
      { term: "daughter", ipa: "ˈdɔːtə" },
      { term: "family", ipa: "ˈfæmli" },
      { term: "father", ipa: "ˈfɑːðə" },
      { term: "granddaughter", ipa: "ˈgrænˌdɔːtə" },
      { term: "grandfather", ipa: "ˈgrænˌfɑːðə" },
      { term: "grandmother", ipa: "ˈgrænˌmʌðə" },
      { term: "grandparents", ipa: "ˈgrænˌpeərənts" },
      { term: "grandson", ipa: "ˈgrænsʌn" },
      { term: "husband", ipa: "ˈhʌzbənd" },
      { term: "mother", ipa: "ˈmʌðə" },
      { term: "nephew", ipa: "ˈnefjuː" },
      { term: "niece", ipa: "niːs" },
      { term: "only child", ipa: "ˈəʊnli tʃaɪld" },
      { term: "parents", ipa: "ˈpeərənts" },
      { term: "relations", ipa: "rɪˈleɪʃənz" },
      { term: "relatives", ipa: "ˈrelətɪvz" },
      { term: "sister", ipa: "ˈsɪstə" },
      { term: "son", ipa: "sʌn" },
      { term: "uncle", ipa: "ˈʌŋkəl" },
      { term: "wife", ipa: "waɪf" },
    ],
  },
  {
    unit: 2,
    section: "People",
    title: "Birth, marriage and death",
    words: [
      { term: "baby", ipa: "ˈbeɪbi" },
      { term: "be born", ipa: "biː bɔːn" },
      { term: "birth", ipa: "bɜːθ" },
      { term: "birthday", ipa: "ˈbɜːθdeɪ" },
      { term: "born", ipa: "bɔːn" },
      { term: "bride", ipa: "braɪd" },
      { term: "bridegroom", ipa: "ˈbraɪdgrʊm" },
      { term: "call after", ipa: "kɔːl ˈɑːftə" },
      { term: "dead", ipa: "ded" },
      { term: "death", ipa: "deθ" },
      { term: "die", ipa: "daɪ" },
      { term: "divorced", ipa: "dɪˈvɔːst" },
      { term: "funeral", ipa: "ˈfjuːnərəl" },
      { term: "get married get", ipa: "ˈmærɪd" },
      { term: "groom", ipa: "gruːm" },
      { term: "have a baby", ipa: "hæv ə ˈbeɪbi" },
      { term: "honeymoon", ipa: "ˈhʌnɪmuːn" },
      { term: "ill", ipa: "ɪl" },
      { term: "marriage", ipa: "ˈmærɪdʒ" },
      { term: "married", ipa: "ˈmærɪd" },
      { term: "separated", ipa: "ˈsepəreɪtɪd" },
      { term: "single", ipa: "ˈsɪŋgəl" },
      { term: "wedding", ipa: "ˈwedɪŋ" },
      { term: "weigh", ipa: "weɪ" },
      { term: "widowed", ipa: "ˈwɪdəʊd" },
    ],
  },
  {
    unit: 3,
    section: "People",
    title: "Parts of the body",
    words: [
      { term: "arm", ipa: "ɑːm" },
      { term: "back", ipa: "bæk" },
      { term: "blood", ipa: "blʌd" },
      { term: "body", ipa: "ˈbɒdi" },
      { term: "brain", ipa: "breɪn" },
      { term: "chest", ipa: "tʃest" },
      { term: "ear", ipa: "ɪə" },
      { term: "eye", ipa: "aɪ" },
      { term: "face", ipa: "feɪs" },
      { term: "feet", ipa: "fiːt" },
      { term: "finger", ipa: "ˈfɪŋgə" },
      { term: "foot", ipa: "fʊt" },
      { term: "hair", ipa: "heə" },
      { term: "hand", ipa: "hænd" },
      { term: "head", ipa: "hed" },
      { term: "heart", ipa: "hɑːt" },
      { term: "hip", ipa: "hɪp" },
      { term: "knee", ipa: "niː" },
      { term: "leg", ipa: "leg" },
      { term: "lip", ipa: "lɪp" },
      { term: "lipstick", ipa: "ˈlɪpstɪk" },
      { term: "mouth", ipa: "maʊθ" },
      { term: "nail", ipa: "neɪl" },
      { term: "neck", ipa: "nek" },
      { term: "nose", ipa: "nəʊz" },
      { term: "pain", ipa: "peɪn" },
      { term: "shoulder", ipa: "ˈʃəʊldə" },
      { term: "side", ipa: "saɪd" },
      { term: "skin", ipa: "skɪn" },
      { term: "stomach", ipa: "ˈstʌmək" },
      { term: "teeth", ipa: "tiːθ" },
      { term: "thumb", ipa: "θʌm" },
      { term: "toe", ipa: "təʊ" },
      { term: "tooth", ipa: "tuːθ" },
      { term: "waist", ipa: "weɪst" },
      { term: "wash", ipa: "wɒʃ" },
    ],
  },
  {
    unit: 4,
    section: "People",
    title: "Clothes",
    words: [
      { term: "bag", ipa: "bæg" },
      { term: "belt", ipa: "belt" },
      { term: "boots", ipa: "buːts" },
      { term: "carry", ipa: "ˈkæri" },
      { term: "clothes", ipa: "kləʊðz" },
      { term: "coat", ipa: "kəʊt" },
      { term: "dress", ipa: "dres" },
      { term: "get dressed", ipa: "get drest" },
      { term: "get undressed get", ipa: "ʌnˈdrest" },
      { term: "glasses", ipa: "ˈglɑːsɪz" },
      { term: "gloves", ipa: "glʌvz" },
      { term: "handbag", ipa: "ˈhænbæg" },
      { term: "hat", ipa: "hæt" },
      { term: "jacket", ipa: "ˈdʒækɪt" },
      { term: "jeans", ipa: "dʒiːnz" },
      { term: "jumper", ipa: "ˈdʒʌmpə" },
      { term: "pyjamas", ipa: "pɪˈdʒɑːməz" },
      { term: "ring", ipa: "rɪŋ" },
      { term: "scarf", ipa: "skɑːf" },
      { term: "shirt", ipa: "ʃɜːt" },
      { term: "shoe(s)", ipa: "ʃuː" },
      { term: "shorts", ipa: "ʃɔːts" },
      { term: "skirt", ipa: "skɜːt" },
      { term: "socks", ipa: "sɒks" },
      { term: "suit", ipa: "suːt" },
      { term: "sunglasses", ipa: "ˈsʌnˌglɑːsɪz" },
      { term: "sweater", ipa: "ˈswetə" },
      { term: "tie", ipa: "taɪ" },
      { term: "tights", ipa: "taɪts" },
      { term: "trainers", ipa: "ˈtreɪnəz" },
      { term: "trousers", ipa: "ˈtraʊzəz" },
      { term: "T-shirt", ipa: "ˈtiːʃɜːt" },
      { term: "umbrella", ipa: "ʌmˈbrelə" },
      { term: "wear", ipa: "weə" },
    ],
  },
  {
    unit: 5,
    section: "People",
    title: "Describing people",
    words: [
      { term: "age", ipa: "eɪdʒ" },
      { term: "average-looking", ipa: "ˈævrɪdʒ ˈlʊkɪŋ" },
      { term: "beard", ipa: "bɪəd" },
      { term: "beautiful", ipa: "ˈbjuːtɪfəl" },
      { term: "blonde", ipa: "blɒnd" },
      { term: "blue", ipa: "bluː" },
      { term: "brown", ipa: "braʊn" },
      { term: "dark", ipa: "dɑːk" },
      { term: "elderly", ipa: "ˈeldəli" },
      { term: "face", ipa: "feɪs" },
      { term: "fair", ipa: "feə" },
      { term: "fat", ipa: "fæt" },
      { term: "green", ipa: "griːn" },
      { term: "hair", ipa: "heə" },
      { term: "head", ipa: "hed" },
      { term: "heavy", ipa: "ˈhevi" },
      { term: "height", ipa: "haɪt" },
      { term: "long", ipa: "lɒŋ" },
      { term: "look like", ipa: "lʊk laɪk" },
      { term: "medium", ipa: "ˈmiːdiəm" },
      { term: "middle-aged", ipa: "ˈmɪdəlˈeɪdʒd" },
      { term: "moustache", ipa: "məˈstɑːʃ" },
      { term: "old(er)", ipa: "əʊld" },
      { term: "overweight", ipa: "ˈəʊvəweɪt" },
      { term: "pretty", ipa: "ˈprɪti" },
      { term: "short", ipa: "ʃɔːt" },
      { term: "skin", ipa: "skɪn" },
      { term: "slim", ipa: "slɪm" },
      { term: "tall", ipa: "tɔːl" },
      { term: "thin", ipa: "θɪn" },
      { term: "ugly", ipa: "ˈʌgli" },
      { term: "weigh", ipa: "weɪ" },
      { term: "weight", ipa: "weɪt" },
      { term: "young(er)", ipa: "jʌŋ" },
    ],
  },
  {
    unit: 6,
    section: "People",
    title: "Health and illness",
    words: [
      { term: "aspirin", ipa: "ˈæsprɪn" },
      { term: "asthma", ipa: "ˈæsmə" },
      { term: "cancer", ipa: "ˈkænsə" },
      { term: "cholera", ipa: "ˈkɒlərə" },
      { term: "cold", ipa: "kəʊld" },
      { term: "dentist", ipa: "ˈdentɪst" },
      { term: "diet", ipa: "daɪət" },
      { term: "doctor", ipa: "ˈdɒktə" },
      { term: "exercise", ipa: "ˈeksəsaɪz" },
      { term: "feel", ipa: "fiːl" },
      { term: "fine", ipa: "faɪn" },
      { term: "good for you", ipa: "gʊd fə juː" },
      { term: "have a cold", ipa: "hæv ə kəʊld" },
      { term: "have a headache", ipa: "hæv ə ˈhedeɪk" },
      { term: "have a healthy diet", ipa: "hæv ə ˈhelθi daɪət" },
      { term: "have a heart attack", ipa: "hæv ə hɑːt əˈtæk" },
      { term: "have toothache", ipa: "hæv tuːθeɪk" },
      { term: "hay fever", ipa: "heɪ ˈfiːvə" },
      { term: "headache", ipa: "ˈhedeɪk" },
      { term: "health", ipa: "helθ" },
      { term: "heart attack", ipa: "hɑːt əˈtæk" },
      { term: "hospital", ipa: "ˈhɒspɪtəl" },
      { term: "ill", ipa: "ɪl" },
      { term: "illness", ipa: "ˈɪlnəs" },
      { term: "malaria", ipa: "məˈleəriə" },
      { term: "mosquito", ipa: "mɒsˈkiːtəʊ" },
      { term: "relax", ipa: "rɪˈlæks" },
      { term: "sick", ipa: "sɪk" },
      { term: "sneeze", ipa: "sniːz" },
      { term: "stressed", ipa: "strest" },
      { term: "toothache", ipa: "ˈtuːθeɪk" },
      { term: "tropical", ipa: "ˈtrɒpɪkəl" },
      { term: "well", ipa: "wel" },
    ],
  },
  {
    unit: 7,
    section: "People",
    title: "Feelings",
    words: [
      { term: "angry", ipa: "ˈæŋgri" },
      { term: "cold", ipa: "kəʊld" },
      { term: "feelings", ipa: "ˈfiːlɪŋz" },
      { term: "happy", ipa: "ˈhæpi" },
      { term: "happy about", ipa: "ˈhæpi əˈbaʊt" },
      { term: "happy for", ipa: "ˈhæpi fɔː" },
      { term: "hate", ipa: "heɪt" },
      { term: "have a word with", ipa: "hæv ə wɜːd wɪð" },
      { term: "hope", ipa: "həʊp" },
      { term: "hot", ipa: "hɒt" },
      { term: "hungry", ipa: "ˈhʌŋgri" },
      { term: "ill", ipa: "ɪl" },
      { term: "like", ipa: "laɪk" },
      { term: "love", ipa: "lʌv" },
      { term: "prefer", ipa: "prɪˈfɜː" },
      { term: "really", ipa: "ˈrɪəli" },
      { term: "sad", ipa: "sæd" },
      { term: "surprised", ipa: "səˈpraɪzd" },
      { term: "thirsty", ipa: "ˈθɜːsti" },
      { term: "tired", ipa: "taɪəd" },
      { term: "upset", ipa: "ʌpˈset" },
      { term: "very well", ipa: "ˈveri wel" },
      { term: "want", ipa: "wɒnt" },
      { term: "well", ipa: "wel" },
    ],
  },
  {
    unit: 8,
    section: "People",
    title: "Conversations 1: Greetings and wishes",
    words: [
      { term: "Bless you bles", ipa: "juː" },
      { term: "Cheers", ipa: "tʃɪəz" },
      { term: "Congratulations", ipa: "kənˌgrætʃʊˈleɪʃənz" },
      { term: "Excuse me", ipa: "ɪkˈskjuːs miː" },
      { term: "Good afternoon", ipa: "gʊd ˌɑːftəˈnuːn" },
      { term: "Good evening", ipa: "gʊd ˈiːvnɪŋ" },
      { term: "Good luck", ipa: "gʊd lʌk" },
      { term: "Good morning", ipa: "gʊdˈmɔːnɪŋ" },
      { term: "Goodbye", ipa: "gʊdˈbaɪ" },
      { term: "Goodnight", ipa: "ˌgʊdˈnaɪt" },
      { term: "greetings", ipa: "ˈgriːtɪŋz" },
      { term: "Happy Birthday", ipa: "ˈhæpi ˈbɜːθdeɪ" },
      { term: "Happy Christmas", ipa: "ˈhæpi ˈkrɪsməs" },
      { term: "Happy New Year", ipa: "ˈhæpi njuː jɪə" },
      { term: "hello", ipa: "heˈləʊ" },
      { term: "hi", ipa: "haɪ" },
      { term: "Merry Christmas", ipa: "ˈmeri ˈkrɪsməs" },
      { term: "not too bad", ipa: "nɒt tuː bæd" },
      { term: "please", ipa: "pliːz" },
      { term: "See you soon", ipa: "siː juː suːn" },
      { term: "sleep well", ipa: "sliːp wel" },
      { term: "sorry", ipa: "ˈsɒri" },
      { term: "Thank you", ipa: "θæŋk juː" },
      { term: "thanks", ipa: "θæŋks" },
      { term: "Well done wel", ipa: "dʌn" },
    ],
  },
  {
    unit: 9,
    section: "People",
    title: "Conversations 2: Useful words and expressions",
    words: [
      { term: "absolutely", ipa: "ˌæbsəˈluːtli" },
      { term: "actually", ipa: "ˈæktʃuəli" },
      { term: "agree", ipa: "əˈgriː" },
      { term: "anyway", ipa: "ˈeniweɪ" },
      { term: "around", ipa: "əˈraʊnd" },
      { term: "Be careful", ipa: "biː ˈkeəfəl" },
      { term: "else", ipa: "els" },
      { term: "hurry up", ipa: "ˈhʌri ʌp" },
      { term: "I agree", ipa: "aɪ əˈgri" },
      { term: "let", ipa: "lets" },
      { term: "Look out", ipa: "lʊk aʊt" },
      { term: "Oh dear", ipa: "əʊ dɪə" },
      { term: "really", ipa: "ˈrɪəli" },
      { term: "Well done wel", ipa: "dʌn" },
      { term: "What a pity", ipa: "wɒt ə ˈpɪti" },
    ],
  },
  {
    unit: 10,
    section: "At home",
    title: "Food and drink",
    words: [
      { term: "apple", ipa: "ˈæpəl" },
      { term: "banana", ipa: "bəˈnɑːnə" },
      { term: "beans", ipa: "biːnz" },
      { term: "beer", ipa: "bɪə" },
      { term: "bread", ipa: "bred" },
      { term: "carrot(s)", ipa: "ˈkærət" },
      { term: "chips", ipa: "tʃɪps" },
      { term: "coffee", ipa: "ˈkɒfi" },
      { term: "drink", ipa: "drɪŋk" },
      { term: "fast food", ipa: "fɑːst fuːd" },
      { term: "fish", ipa: "fɪʃ" },
      { term: "fish and chips", ipa: "fɪʃ ənd tʃɪps" },
      { term: "food", ipa: "fuːd" },
      { term: "fruit", ipa: "fruːt" },
      { term: "fruit juice", ipa: "fruːt dʒuːs" },
      { term: "garlic", ipa: "ˈgɑːlɪk" },
      { term: "grape(s)", ipa: "greɪp" },
      { term: "hamburger", ipa: "ˈhæmˌbɜːgə" },
      { term: "hot dog", ipa: "hɒt dɒg" },
      { term: "meat", ipa: "miːt" },
      { term: "milk", ipa: "mɪlk" },
      { term: "mineral water", ipa: "ˈmɪnərəl ˈwɔːtə" },
      { term: "mushroom(s)", ipa: "ˈmʌʃrʊm" },
      { term: "onion", ipa: "ˈʌnjən" },
      { term: "orange", ipa: "ˈɒrɪndʒ" },
      { term: "pasta", ipa: "ˈpæstə" },
      { term: "pea(s)", ipa: "piː" },
      { term: "pear", ipa: "peə" },
      { term: "pepper", ipa: "ˈpepə" },
      { term: "pineapple", ipa: "ˈpaɪnæpəl" },
      { term: "pizza", ipa: "ˈpiːtsə" },
      { term: "potato(es)", ipa: "pəˈteɪtəʊ" },
      { term: "rice", ipa: "raɪs" },
      { term: "salt", ipa: "sɒlt" },
      { term: "strawberry (-ies)", ipa: "ˈstrɔːbəri" },
      { term: "sugar", ipa: "ˈʃʊgə" },
      { term: "tea", ipa: "tiː" },
      { term: "tomato(es)", ipa: "təˈmɑːtəʊ" },
      { term: "vegetable(s)", ipa: "ˈvedʒtəbəl" },
      { term: "vegetarian", ipa: "ˌvedʒɪˈteəriən" },
      { term: "wine", ipa: "waɪn" },
    ],
  },
  {
    unit: 11,
    section: "At home",
    title: "In the kitchen",
    words: [
      { term: "bin", ipa: "bɪn" },
      { term: "bowl", ipa: "bəʊl" },
      { term: "chopsticks", ipa: "ˈtʃɒpstɪks" },
      { term: "cloth", ipa: "klɒθ" },
      { term: "coffee maker", ipa: "ˈkɒfi ˈmeɪkə" },
      { term: "cook", ipa: "kʊk" },
      { term: "cooker", ipa: "ˈkʊkə" },
      { term: "cup", ipa: "kʌp" },
      { term: "cupboard", ipa: "ˈkʌbəd" },
      { term: "dishwasher", ipa: "ˈdɪʃˌwɒʃə" },
      { term: "dry", ipa: "draɪ" },
      { term: "fork", ipa: "fɔːk" },
      { term: "freezer", ipa: "ˈfriːzə" },
      { term: "fridge", ipa: "frɪdʒ" },
      { term: "frying pan", ipa: "ˈfraɪɪŋ pæn" },
      { term: "glass", ipa: "glɑːs" },
      { term: "kitchen", ipa: "ˈkɪtʃɪn" },
      { term: "kitchen roll", ipa: "ˈkɪtʃɪn rəʊl" },
      { term: "knife", ipa: "naɪf" },
      { term: "microwave", ipa: "ˈmaɪkrəweɪv" },
      { term: "mug", ipa: "mʌg" },
      { term: "plate", ipa: "pleɪt" },
      { term: "saucepan", ipa: "ˈsɔːspən" },
      { term: "shelf", ipa: "ʃelf" },
      { term: "sink", ipa: "sɪŋk" },
      { term: "spoon", ipa: "spuːn" },
      { term: "tap", ipa: "tæp" },
      { term: "tea towel", ipa: "tiː taʊəl" },
      { term: "teapot", ipa: "ˈtiːpɒt" },
      { term: "washing machine", ipa: "ˈwɒʃɪŋ məˈʃiːn" },
      { term: "washing-up liquid", ipa: "ˈwɒʃɪŋ ʌp ˈlɪkwɪd" },
      { term: "worktop", ipa: "ˈwɜːktɒp" },
    ],
  },
  {
    unit: 12,
    section: "At home",
    title: "In the bedroom and bathroom",
    words: [
      { term: "alarm clock", ipa: "əˈlɑːm klɒk" },
      { term: "basin", ipa: "ˈbeɪsən" },
      { term: "bathroom", ipa: "ˈbɑːθrʊm" },
      { term: "bed", ipa: "bed" },
      { term: "bedroom", ipa: "ˈbedrʊm" },
      { term: "bedside lamp", ipa: "ˈbedsaɪd læmp" },
      { term: "bedside table", ipa: "ˈbedsaɪd ˈteɪbəl" },
      { term: "chest of drawers", ipa: "tʃest əv drɔːz" },
      { term: "clean", ipa: "kliːn" },
      { term: "clean your teeth", ipa: "kliːn jɔː tiːθ" },
      { term: "comb", ipa: "kəʊm" },
      { term: "downstairs", ipa: "ˌdaʊnˈsteəz" },
      { term: "drawers", ipa: "drɔːz" },
      { term: "dressing table", ipa: "ˈdresɪŋ ˈteɪbəl" },
      { term: "every", ipa: "ˈevri" },
      { term: "fall asleep", ipa: "fɔːl əˈsliːp" },
      { term: "get dressed", ipa: "get drest" },
      { term: "get undressed get", ipa: "ʌnˈdrest" },
      { term: "get up get", ipa: "ʌp" },
      { term: "go", ipa: "gəʊ" },
      { term: "go downstairs", ipa: "gəʊ ˌdaʊnˈsteəz" },
      { term: "go to bed", ipa: "gəʊ tə bed" },
      { term: "go upstairs", ipa: "gəʊ ʌpˈsteəz" },
      { term: "hairbrush", ipa: "ˈheəbrʌʃ" },
      { term: "have", ipa: "hæv" },
      { term: "have a shower", ipa: "hæv ə ˈʃaʊə" },
      { term: "home", ipa: "həʊm" },
      { term: "light", ipa: "laɪt" },
      { term: "make", ipa: "meɪk" },
      { term: "mirror", ipa: "ˈmɪrə" },
      { term: "normally", ipa: "ˈnɔːməli" },
      { term: "pyjamas", ipa: "pɪˈdʒɑːməz" },
      { term: "radio", ipa: "ˈreɪdiəʊ" },
      { term: "razor", ipa: "ˈreɪzə" },
      { term: "routine", ipa: "ruːˈtiːn" },
      { term: "shampoo", ipa: "ʃæmˈpuː" },
      { term: "shelf", ipa: "ʃelf" },
      { term: "shower", ipa: "ʃaʊə" },
      { term: "shower gel", ipa: "ˈʃaʊə dʒel" },
      { term: "soap", ipa: "səʊp" },
      { term: "telephone (phone)", ipa: "ˈtelɪfəʊn" },
      { term: "television (TV)", ipa: "ˈtelɪvɪʒən" },
      { term: "toilet", ipa: "ˈtɔɪlət" },
      { term: "toothbrush", ipa: "ˈtuːθbrʌʃ" },
      { term: "toothpaste", ipa: "ˈtuːθpeɪst" },
      { term: "towel", ipa: "taʊəl" },
      { term: "turn off", ipa: "tɜːn ɒf" },
      { term: "upstairs", ipa: "ʌpˈsteəz" },
      { term: "wake up", ipa: "weɪk ʌp" },
      { term: "wardrobe", ipa: "ˈwɔːdrəʊb" },
    ],
  },
  {
    unit: 13,
    section: "At home",
    title: "In the living room",
    words: [
      { term: "armchair", ipa: "ˈɑːmtʃeə" },
      { term: "book", ipa: "bʊk" },
      { term: "bookshelf (bookshelves)", ipa: "ˈbʊkʃelf" },
      { term: "carpet", ipa: "ˈkɑːpɪt" },
      { term: "chair", ipa: "tʃeə" },
      { term: "close the curtains", ipa: "kləʊs ðə ˈkɜːtns" },
      { term: "coffee table", ipa: "ˈkɒfi ˈteɪbəl" },
      { term: "curtains", ipa: "ˈkɜːtənz" },
      { term: "hi-fi", ipa: "ˈhaɪfaɪ" },
      { term: "just relax", ipa: "dʒʌst rɪˈlæks" },
      { term: "lamp", ipa: "læmp" },
      { term: "light", ipa: "laɪt" },
      { term: "light switch", ipa: "laɪt swɪtʃ" },
      { term: "listen (to)", ipa: "ˈlɪsən" },
      { term: "living room", ipa: "ˈlɪvɪŋ ruːm" },
      { term: "pass", ipa: "pɑːs" },
      { term: "phone", ipa: "fəʊn" },
      { term: "picture", ipa: "ˈpɪktʃə" },
      { term: "radio", ipa: "ˈreɪdiəʊ" },
      { term: "read", ipa: "riːd" },
      { term: "relax", ipa: "rɪˈlæks" },
      { term: "remote control", ipa: "rɪˈməʊt kənˈtrəʊl" },
      { term: "rug", ipa: "rʌg" },
      { term: "socket", ipa: "ˈsɒkɪt" },
      { term: "sofa", ipa: "ˈsəʊfə" },
      { term: "switch on", ipa: "swɪtʃ ɒn" },
      { term: "table", ipa: "ˈteɪbəl" },
      { term: "television (TV)", ipa: "ˈtelɪvɪʒən" },
      { term: "turn off", ipa: "tɜːn ɒf" },
      { term: "turn on", ipa: "tɜːn ɒn" },
      { term: "TV", ipa: "ˌtiːˈviː" },
      { term: "window", ipa: "ˈwɪndəʊ" },
    ],
  },
  {
    unit: 14,
    section: "School and workplace",
    title: "Jobs",
    words: [
      { term: "bank clerk", ipa: "bæŋk klɑːk" },
      { term: "beauty salon", ipa: "ˈbjuːti ˈsælɒn" },
      { term: "do", ipa: "duː" },
      { term: "doctor", ipa: "ˈdɒktə" },
      { term: "engineer", ipa: "ˌendʒɪˈnɪə" },
      { term: "factory", ipa: "ˈfæktəri" },
      { term: "farmer", ipa: "ˈfɑːmə" },
      { term: "hospital", ipa: "ˈhɒspɪtəl" },
      { term: "job", ipa: "dʒɒb" },
      { term: "librarian", ipa: "laɪˈbreəriən" },
      { term: "mechanic", ipa: "məˈkænɪk" },
      { term: "nurse", ipa: "nɜːs" },
      { term: "office", ipa: "ˈɒfɪs" },
      { term: "police officer", ipa: "pəˈliːs ˈɒfɪsə" },
      { term: "restaurant", ipa: "ˈrestrɒnt" },
      { term: "secretary", ipa: "ˈsekrətəri" },
      { term: "shop", ipa: "ʃɒp" },
      { term: "shop assistant", ipa: "ʃɒp əˈsɪstənt" },
      { term: "taxi driver", ipa: "ˈtæksi ˈdraɪvə" },
      { term: "teacher", ipa: "ˈtiːtʃə" },
      { term: "traffic warden", ipa: "ˈtræfɪk ˈwɔːdən" },
      { term: "train", ipa: "treɪn" },
      { term: "waiter", ipa: "ˈweɪtə" },
      { term: "work", ipa: "wɜːk" },
    ],
  },
  {
    unit: 15,
    section: "School and workplace",
    title: "At school and university",
    words: [
      { term: "art", ipa: "ɑːt" },
      { term: "biology", ipa: "baɪˈɒlədʒi" },
      { term: "board", ipa: "bɔːd" },
      { term: "board pen", ipa: "bɔːd pen" },
      { term: "board rubber", ipa: "bɔːd ˈrʌbə" },
      { term: "chemistry", ipa: "ˈkemɪstri" },
      { term: "computer", ipa: "kəmˈpjuːtə" },
      { term: "degree", ipa: "dɪˈgriː" },
      { term: "desk", ipa: "desk" },
      { term: "do a course", ipa: "duː ə kɔːs" },
      { term: "do an exam", ipa: "duː æn ɪgˈzæm" },
      { term: "do homework", ipa: "duː ˈhəʊmwɜːk" },
      { term: "drawing pin", ipa: "ˈdrɔːɪŋ pɪn" },
      { term: "DVD player", ipa: "ˌdiːviːˈdiː ˈpleɪə" },
      { term: "English", ipa: "ˈɪŋglɪʃ" },
      { term: "exam", ipa: "ɪgˈzæm" },
      { term: "fail an exam", ipa: "feɪl ən ɪgˈzæm" },
      { term: "geography", ipa: "dʒɪˈɒgrəfi" },
      { term: "get a degree get", ipa: "ə dɪˈgriː" },
      { term: "go to school", ipa: "gəʊ tə skuːl" },
      { term: "go to university", ipa: "gəʊ tə ˌjuːnɪˈvɜːsəti" },
      { term: "history", ipa: "ˈhɪstri" },
      { term: "homework", ipa: "ˈhəʊmwɜːk" },
      { term: "learn", ipa: "lɜːn" },
      { term: "maths", ipa: "mæθs" },
      { term: "modern languages", ipa: "ˈmɒdən ˈlæŋgwɪdʒɪz" },
      { term: "music", ipa: "ˈmjuːzɪk" },
      { term: "notebook", ipa: "ˈnəʊtbʊk" },
      { term: "noticeboard", ipa: "nəʊtɪsbɔːd" },
      { term: "OHP", ipa: "əʊ eɪtʃ ˈpiː" },
      { term: "pass an exam", ipa: "pɑːs ən ɪgˈzæm" },
      { term: "PE (physical education)", ipa: "ˌpiːˈiː" },
      { term: "pen", ipa: "pen" },
      { term: "pencil", ipa: "ˈpensəl" },
      { term: "pencil sharpener", ipa: "ˈpensəl ˈʃɑːpənə" },
      { term: "physics", ipa: "ˈfɪzɪks" },
      { term: "piece of paper", ipa: "piːs əv ˈpeɪpə" },
      { term: "read", ipa: "riːd" },
      { term: "rubber", ipa: "ˈrʌbə" },
      { term: "ruler", ipa: "ˈruːlə" },
      { term: "school", ipa: "skuːl" },
      { term: "student", ipa: "ˈstjuːdənt" },
      { term: "study", ipa: "ˈstʌdi" },
      { term: "subject", ipa: "ˈsʌbdʒəkt" },
      { term: "take an exam", ipa: "teɪk ən ɪgˈzæm" },
      { term: "teach", ipa: "tiːtʃ" },
      { term: "teacher", ipa: "ˈtiːtʃə" },
      { term: "textbook", ipa: "ˈteksbʊk" },
      { term: "university", ipa: "ˌjuːnɪˈvɜːsəti" },
      { term: "whiteboard", ipa: "ˈwaɪtbɔːd" },
      { term: "write", ipa: "raɪt" },
    ],
  },
  {
    unit: 16,
    section: "School and workplace",
    title: "Communications",
    words: [
      { term: "address", ipa: "əˈdres" },
      { term: "call", ipa: "kɔːl" },
      { term: "call back", ipa: "kɔːl bæk" },
      { term: "computer", ipa: "kəmˈpjuːtə" },
      { term: "date", ipa: "deɪt" },
      { term: "dot", ipa: "dɒt" },
      { term: "email", ipa: "ˈiːmeɪl" },
      { term: "email address", ipa: "ˈiːmeɪl əˈdres" },
      { term: "envelope", ipa: "ˈenvələʊp" },
      { term: "Internet", ipa: "ˈɪntənet" },
      { term: "keyboard", ipa: "ˈkiːbɔːd" },
      { term: "laptop", ipa: "ˈlæptɒp" },
      { term: "letter", ipa: "ˈletə" },
      { term: "letter box", ipa: "ˈletə bɒks" },
      { term: "make a (phone) call", ipa: "meɪk ə kɔːl" },
      { term: "make phone calls", ipa: "meɪk fəʊn kɔːlz" },
      { term: "memory stick", ipa: "ˈmeməri stɪk" },
      { term: "message", ipa: "ˈmesɪdʒ" },
      { term: "mobile", ipa: "ˈməʊbaɪl" },
      { term: "mobile device", ipa: "ˈməʊbaɪl dɪˈvaɪs" },
      { term: "mouse", ipa: "maʊs" },
      { term: "online", ipa: "ˌɒnˈlaɪn" },
      { term: "phone box", ipa: "fəʊn bɒks" },
      { term: "phone call", ipa: "ˈfəʊn kɔːl" },
      { term: "phone number", ipa: "fəʊn ˈnʌmbə" },
      { term: "post", ipa: "pəʊst" },
      { term: "screen", ipa: "skriːn" },
      { term: "send a text (message) send", ipa: "ə tekst" },
      { term: "speak to", ipa: "spiːk tə" },
      { term: "stamp", ipa: "stæmp" },
      { term: "take a message", ipa: "teɪk ə ˈmesɪdʒ" },
      { term: "telephone (phone)", ipa: "ˈtelɪfəʊn" },
      { term: "tell someone you called tel", ipa: "ˈsʌmwʌn juː kɔːld" },
      { term: "text", ipa: "tekst" },
      { term: "voicemail", ipa: "ˈvɔɪsmeɪl" },
    ],
  },
  {
    unit: 17,
    section: "School and workplace",
    title: "Your phone",
    words: [
      { term: "apps", ipa: "æps" },
      { term: "battery", ipa: "ˈbætəri" },
      { term: "call", ipa: "kɔːl" },
      { term: "camera", ipa: "ˈkæmrə" },
      { term: "charger", ipa: "ˈtʃɑːdʒə" },
      { term: "delete", ipa: "dɪˈliːt" },
      { term: "download", ipa: "ˌdaʊnˈləʊd" },
      { term: "download an app", ipa: "daʊnˈləʊd ən æp" },
      { term: "leave a voicemail", ipa: "liːv ə ˈvɔɪsmeɪl" },
      { term: "local", ipa: "ˈləʊkəl" },
      { term: "locked", ipa: "lɒkt" },
      { term: "memory", ipa: "ˈmeməri" },
      { term: "message", ipa: "ˈmesɪdʒ" },
      { term: "phone case", ipa: "fəʊn keɪs" },
      { term: "PIN", ipa: "pɪn" },
      { term: "power button", ipa: "ˈpaʊə ˈbʌtən" },
      { term: "save", ipa: "seɪv" },
      { term: "screen", ipa: "skriːn" },
      { term: "selfies", ipa: "selfis" },
      { term: "SIM card", ipa: "ˈsɪm kɑːd" },
      { term: "swipe", ipa: "swaɪp" },
      { term: "text", ipa: "tekst" },
      { term: "unlock", ipa: "ʌnˈlɒk" },
    ],
  },
  {
    unit: 18,
    section: "Leisure",
    title: "Holidays",
    words: [
      { term: "by bus", ipa: "baɪ bʌs" },
      { term: "by car", ipa: "baɪ kɑː" },
      { term: "by coach", ipa: "baɪ kəʊtʃ" },
      { term: "by ferry", ipa: "baɪ ˈferi" },
      { term: "by plane", ipa: "baɪ pleɪn" },
      { term: "by train", ipa: "baɪ treɪn" },
      { term: "camera", ipa: "ˈkæmrə" },
      { term: "camping", ipa: "ˈkæmpɪŋ" },
      { term: "car", ipa: "kɑː" },
      { term: "coach", ipa: "kəʊtʃ" },
      { term: "coach tour", ipa: "kəʊtʃ tʊə" },
      { term: "currency", ipa: "ˈkʌrənsi" },
      { term: "enjoy", ipa: "ɪnˈdʒɔɪ" },
      { term: "ferry", ipa: "ˈferi" },
      { term: "flight", ipa: "flaɪt" },
      { term: "fly", ipa: "flaɪ" },
      { term: "go on holiday", ipa: "gəʊ ɒn ˈhɒlədeɪ" },
      { term: "have a great time", ipa: "hæv ə greɪt taɪm" },
      { term: "have a holiday", ipa: "ˈhɒlədeɪ" },
      { term: "holiday", ipa: "ˈhɒlədeɪ" },
      { term: "luggage", ipa: "ˈlʌgɪdʒ" },
      { term: "nightlife", ipa: "ˈnaɪtlaɪf" },
      { term: "package holiday", ipa: "ˈpækɪdʒ ˈhɒlədeɪ" },
      { term: "passport", ipa: "ˈpɑːspɔːt" },
      { term: "plane", ipa: "pleɪn" },
      { term: "postcard", ipa: "ˈpəʊstkɑːd" },
      { term: "rucksack", ipa: "ˈrʌksæk" },
      { term: "send a postcard send", ipa: "ə pəʊstkɑːd" },
      { term: "suitcase", ipa: "ˈsuːtkeɪs" },
      { term: "train", ipa: "treɪn" },
      { term: "transport", ipa: "ˈtrænspɔːt" },
      { term: "visa", ipa: "ˈviːzə" },
      { term: "walking holiday", ipa: "ˈwɔːkɪŋ ˈhɒlədeɪ" },
      { term: "winter holiday", ipa: "ˈwɪntə ˈhɒlədeɪ" },
    ],
  },
  {
    unit: 19,
    section: "Leisure",
    title: "Shops and shopping",
    words: [
      { term: "bag", ipa: "bæg" },
      { term: "basement", ipa: "ˈbeɪsmənt" },
      { term: "beauty", ipa: "ˈbjuːti" },
      { term: "bigger (size)", ipa: "bɪgə" },
      { term: "bookshop", ipa: "ˈbʊkʃɒp" },
      { term: "carrier bag", ipa: "ˈkæriə bæg" },
      { term: "cash", ipa: "kæʃ" },
      { term: "cash desk", ipa: "kæʃ desk" },
      { term: "change", ipa: "tʃeɪndʒ" },
      { term: "cheque", ipa: "tʃek" },
      { term: "closed", ipa: "kləʊzd" },
      { term: "colour", ipa: "ˈkʌlə" },
      { term: "cost", ipa: "kɒst" },
      { term: "credit card", ipa: "ˈkredɪt kɑːd" },
      { term: "department store", ipa: "dɪˈpɑːtmənt stɔː" },
      { term: "different (colour)", ipa: "ˈdɪfrnt" },
      { term: "electricals", ipa: "ɪˈlektrɪkəlz" },
      { term: "first floor", ipa: "fɜːst flɔː" },
      { term: "floor", ipa: "flɔː" },
      { term: "food", ipa: "fuːd" },
      { term: "fourth", ipa: "fɔːθ" },
      { term: "furniture", ipa: "ˈfɜːnɪtʃə" },
      { term: "gift shop", ipa: "gɪft ʃɒp" },
      { term: "ground floor", ipa: "graʊnd flɔː" },
      { term: "note", ipa: "nəʊt" },
      { term: "open", ipa: "ˈəʊpən" },
      { term: "pay", ipa: "peɪ" },
      { term: "post office", ipa: "pəʊst ˈɒfɪs" },
      { term: "pull", ipa: "pʊl" },
      { term: "push", ipa: "pʊʃ" },
      { term: "receipt", ipa: "rɪˈsiːt" },
      { term: "restaurant", ipa: "ˈrestrɒnt" },
      { term: "second", ipa: "ˈsekənd" },
      { term: "shop", ipa: "ʃɒp" },
      { term: "shopping", ipa: "ˈʃɒpɪŋ" },
      { term: "sign", ipa: "saɪn" },
      { term: "size", ipa: "saɪz" },
      { term: "smaller (size)", ipa: "smɔːlə" },
      { term: "supermarket", ipa: "ˈsuːpəˌmɑːkɪt" },
      { term: "third", ipa: "θɜːd" },
      { term: "toys", ipa: "tɔɪz" },
      { term: "try on", ipa: "traɪ ɒn" },
    ],
  },
  {
    unit: 20,
    section: "Leisure",
    title: "Online shopping",
    words: [
      { term: "add to basket", ipa: "æd tə ˈbæskət" },
      { term: "basket", ipa: "ˈbæskət" },
      { term: "colour", ipa: "ˈkʌlə" },
      { term: "credit card", ipa: "ˈkredɪt kɑːd" },
      { term: "delivery", ipa: "dɪˈlɪvəri" },
      { term: "next day delivery nekst", ipa: "deɪ dɪˈlɪvəri" },
      { term: "online", ipa: "ˌɒnˈlaɪn" },
      { term: "online reviews", ipa: "ˈɑːnlaɪn rɪˈvjuːz" },
      { term: "order number", ipa: "ˈɔːdə ˈnʌm. bə" },
      { term: "post code", ipa: "ˈpəʊst kəʊd" },
      { term: "price", ipa: "praɪs" },
      { term: "review", ipa: "rɪˈvjuː" },
      { term: "search", ipa: "sɜːtʃ" },
      { term: "shop online", ipa: "ʃɒpɑːnlaɪn" },
      { term: "size", ipa: "saɪz" },
      { term: "zip code", ipa: "zɪp kəʊd" },
    ],
  },
  {
    unit: 21,
    section: "Leisure",
    title: "In a hotel",
    words: [
      { term: "bathroom", ipa: "ˈbɑːθrʊm" },
      { term: "bill", ipa: "bɪl" },
      { term: "breakfast", ipa: "ˈbrekfəst" },
      { term: "change", ipa: "tʃeɪndʒ" },
      { term: "change money", ipa: "tʃeɪndʒ ˈmʌni" },
      { term: "check", ipa: "tʃek" },
      { term: "check out", ipa: "tʃek aʊt" },
      { term: "check your bill", ipa: "tʃek jɔː bɪl" },
      { term: "code", ipa: "kəʊd" },
      { term: "double room", ipa: "ˈdʌbəl ruːm" },
      { term: "exchange", ipa: "ɪksˈtʃeɪndʒ" },
      { term: "exchange some money", ipa: "ɪksˈtʃeɪndʒ sʌm mʌni" },
      { term: "fill in a form", ipa: "fɪl ɪn ə fɔːm" },
      { term: "floor", ipa: "flɔː" },
      { term: "form", ipa: "fɔːm" },
      { term: "hairdryer", ipa: "ˈheəˌdraɪə" },
      { term: "have a wake-up call", ipa: "hæv ə weɪk ʌp kɔːl" },
      { term: "have breakfast", ipa: "hæv ˈbrekfəst" },
      { term: "hotel", ipa: "həʊˈtel" },
      { term: "key", ipa: "kiː" },
      { term: "lift", ipa: "lɪft" },
      { term: "luggage", ipa: "ˈlʌgɪdʒ" },
      { term: "mini-bar", ipa: "ˈmɪni bɑː" },
      { term: "money", ipa: "ˈmʌni" },
      { term: "on the first floor", ipa: "ɒn ðə fɜːst flɔː" },
      { term: "outside line", ipa: "ˌaʊtˈsaɪd laɪn" },
      { term: "over there", ipa: "ˈəʊvə ðeə" },
      { term: "phone", ipa: "fəʊn" },
      { term: "reception", ipa: "rɪˈsepʃən" },
      { term: "reservation", ipa: "ˌrezəˈveɪʃən" },
      { term: "room service", ipa: "ˈruːm ˌsɜːvɪs" },
      { term: "room with a view", ipa: "ruːm wɪð ə vjuː" },
      { term: "shower", ipa: "ʃaʊə" },
      { term: "sign", ipa: "saɪn" },
      { term: "single room", ipa: "ˈsɪŋgəl ruːm" },
      { term: "take the lift", ipa: "teɪk ðə lɪft" },
      { term: "TV", ipa: "ˌtiːˈviː" },
      { term: "wake-up call", ipa: "weɪk ʌp kɔːl" },
    ],
  },
  {
    unit: 22,
    section: "Leisure",
    title: "Eating out",
    words: [
      { term: "alcohol", ipa: "ˈælkəhɒl" },
      { term: "apple pie", ipa: "ˈæpəl paɪ" },
      { term: "bar", ipa: "bɑː" },
      { term: "beans", ipa: "biːnz" },
      { term: "burger", ipa: "ˈbɜːgə" },
      { term: "chocolate", ipa: "ˈtʃɒklət" },
      { term: "course", ipa: "kɔːs" },
      { term: "curry", ipa: "ˈkʌri" },
      { term: "delicious", ipa: "dɪˈlɪʃəs" },
      { term: "dessert", ipa: "dɪˈzɜːt" },
      { term: "drink", ipa: "drɪŋk" },
      { term: "fast food restaurant", ipa: "fɑːst fuːd ˈrestrɒnt" },
      { term: "fish and chips", ipa: "fɪʃ ənd tʃɪps" },
      { term: "fruit salad", ipa: "fruːt ˈsæləd" },
      { term: "green beans", ipa: "griːn biːnz" },
      { term: "have", ipa: "hæv" },
      { term: "have a cup of tea (coffee)", ipa: "hæv ə kʌp ɒv tiː" },
      { term: "ice cream", ipa: "ˌaɪsˈkriːm" },
      { term: "main course", ipa: "meɪn kɔːs" },
      { term: "meal", ipa: "miːl" },
      { term: "medium", ipa: "ˈmiːdiəm" },
      { term: "menu", ipa: "ˈmenjuː" },
      { term: "mixed salad", ipa: "mɪkst ˈsæləd" },
      { term: "mushroom(s)", ipa: "ˈmʌʃrʊm" },
      { term: "new potatoes", ipa: "njuː pəˈteɪtəʊz" },
      { term: "order", ipa: "ˈɔːdə" },
      { term: "place", ipa: "pleɪs" },
      { term: "potato(es)", ipa: "pəˈteɪtəʊ" },
      { term: "pub", ipa: "pʌb" },
      { term: "rare", ipa: "reə" },
      { term: "ready to order", ipa: "ˈredi tə ˈɔːdə" },
      { term: "restaurant", ipa: "ˈrestrɒnt" },
      { term: "salad", ipa: "ˈsæləd" },
      { term: "salmon fillet", ipa: "ˈsæmən ˈfɪlɪt" },
      { term: "snack", ipa: "snæk" },
      { term: "soft drink(s)", ipa: "sɒft drɪŋk" },
      { term: "soup (of the day)", ipa: "suːp" },
      { term: "starter", ipa: "ˈstɑːtə" },
      { term: "steak", ipa: "steɪk" },
      { term: "take-away", ipa: "teɪk əˈweɪ" },
      { term: "vegetable(s)", ipa: "ˈvedʒtəbəl" },
      { term: "well-done", ipa: "ˌwelˈdʌn" },
    ],
  },
  {
    unit: 23,
    section: "Leisure",
    title: "Sports",
    words: [
      { term: "American football", ipa: "əˈmerɪkən ˈfʊtbɔːl" },
      { term: "badminton", ipa: "ˈbædmɪntən" },
      { term: "ball game", ipa: "bɔːl geɪm" },
      { term: "baseball", ipa: "ˈbeɪsbɔːl" },
      { term: "basketball", ipa: "ˈbɑːskɪtbɔːl" },
      { term: "court", ipa: "kɔːt" },
      { term: "do", ipa: "duː" },
      { term: "favourite", ipa: "ˈfeɪvərɪt" },
      { term: "football", ipa: "ˈfʊtbɔːl" },
      { term: "go", ipa: "gəʊ" },
      { term: "horse racing", ipa: "ˈhɔːs ˌreɪsɪŋ" },
      { term: "judo", ipa: "ˈdʒuːdəʊ" },
      { term: "karate", ipa: "kəˈrɑːti" },
      { term: "kayaking", ipa: "ˈkaɪækɪŋ" },
      { term: "like", ipa: "laɪk" },
      { term: "motor racing", ipa: "ˈməʊtə ˈreɪsɪŋ" },
      { term: "pitch", ipa: "pɪtʃ" },
      { term: "play", ipa: "pleɪ" },
      { term: "pool", ipa: "puːl" },
      { term: "rugby", ipa: "ˈrʌgbi" },
      { term: "running", ipa: "ˈrʌnɪŋ" },
      { term: "sailing", ipa: "ˈseɪlɪŋ" },
      { term: "skiing", ipa: "ˈskiːɪŋ" },
      { term: "snowboarding", ipa: "ˈsnəʊbɔːdɪŋ" },
      { term: "sports", ipa: "spɔːts" },
      { term: "sports centre", ipa: "spɔːts ˈsentə" },
      { term: "swimming", ipa: "ˈswɪmɪŋ" },
      { term: "swimming pool", ipa: "ˈswɪmɪŋ puːl" },
      { term: "table tennis", ipa: "ˈteɪbəl ˈtenɪs" },
      { term: "tennis", ipa: "ˈtenɪs" },
      { term: "volleyball", ipa: "ˈvɒlibɔːl" },
    ],
  },
  {
    unit: 24,
    section: "Leisure",
    title: "Cinema",
    words: [
      { term: "action film", ipa: "ˈækʃən fɪlm" },
      { term: "boring", ipa: "ˈbɔːrɪŋ" },
      { term: "cartoon", ipa: "kɑːˈtuːn" },
      { term: "cinema", ipa: "ˈsɪnəmə" },
      { term: "comedy", ipa: "ˈkɒmədi" },
      { term: "director", ipa: "dɪˈrektə" },
      { term: "enjoy", ipa: "ɪnˈdʒɔɪ" },
      { term: "film", ipa: "fɪlm" },
      { term: "film star", ipa: "fɪlm stɑː" },
      { term: "go", ipa: "gəʊ" },
      { term: "horror", ipa: "ˈhɒrə" },
      { term: "in", ipa: "ɪn" },
      { term: "love", ipa: "lʌv" },
      { term: "musical", ipa: "ˈmjuːzɪkəl" },
      { term: "on TV", ipa: "ɒn tiːˈviː" },
      { term: "play", ipa: "pleɪ" },
      { term: "romantic (comedy)", ipa: "rəˈmæntɪk" },
      { term: "science fiction", ipa: "saɪəns ˈfɪkʃən" },
      { term: "see", ipa: "siː" },
      { term: "thriller", ipa: "ˈθrɪlə" },
      { term: "TV", ipa: "ˌtiːˈviː" },
      { term: "western", ipa: "ˈwestən" },
    ],
  },
  {
    unit: 25,
    section: "Leisure",
    title: "Free time at home",
    words: [
      { term: "about", ipa: "əˈbaʊt" },
      { term: "book", ipa: "bʊk" },
      { term: "chat", ipa: "tʃæt" },
      { term: "chat to friends online", ipa: "tʃæt tə frendz ˈɒnlaɪn" },
      { term: "come", ipa: "kʌm" },
      { term: "comic", ipa: "ˈkɒmɪk" },
      { term: "cooking", ipa: "ˈkʊkɪŋ" },
      { term: "dinner", ipa: "ˈdɪnə" },
      { term: "do", ipa: "duː" },
      { term: "do nothing", ipa: "duː ˈnʌθɪŋ" },
      { term: "download", ipa: "ˌdaʊnˈləʊd" },
      { term: "DVD", ipa: "ˌdiːviːˈdiː" },
      { term: "film", ipa: "fɪlm" },
      { term: "friend", ipa: "frend" },
      { term: "gardening", ipa: "ˈgɑːdənɪŋ" },
      { term: "grow flowers / vegetables", ipa: "grəʊ flaʊəz / ˈvedʒtəbəlz" },
      { term: "have", ipa: "hæv" },
      { term: "have a sleep", ipa: "hæv ə sliːp" },
      { term: "have friends round", ipa: "hæv frendz raʊnd" },
      { term: "headphones", ipa: "ˈhedfəʊnz" },
      { term: "hobby", ipa: "ˈhɒbi" },
      { term: "home", ipa: "həʊm" },
      { term: "Internet", ipa: "ˈɪntənet" },
      { term: "listen (to)", ipa: "ˈlɪsən" },
      { term: "magazine", ipa: "ˌmægəˈziːn" },
      { term: "Morocco", ipa: "məˈrɒkəʊ" },
      { term: "newspaper", ipa: "ˈnjuːzˌpeɪpə" },
      { term: "nothing", ipa: "ˈnʌθɪŋ" },
      { term: "novel", ipa: "ˈnɒvəl" },
      { term: "on the phone", ipa: "ɒn ðə fəʊn" },
      { term: "online", ipa: "ˌɒnˈlaɪn" },
      { term: "phone", ipa: "fəʊn" },
      { term: "play", ipa: "pleɪ" },
      { term: "play video games", ipa: "pleɪ ˈvɪdɪəʊ geimz" },
      { term: "programme", ipa: "ˈprəʊgræm" },
      { term: "radio", ipa: "ˈreɪdiəʊ" },
      { term: "read", ipa: "riːd" },
      { term: "see", ipa: "siː" },
      { term: "sleep", ipa: "sliːp" },
      { term: "stay", ipa: "steɪ" },
      { term: "talk", ipa: "tɔːk" },
      { term: "talk to", ipa: "tɔːk tuː" },
      { term: "TV", ipa: "ˌtiːˈviː" },
      { term: "vegetable(s)", ipa: "ˈvedʒtəbəl" },
      { term: "video games", ipa: "ˈvidiːəʊ geɪmz" },
      { term: "watch", ipa: "wɒtʃ 4, 23, 24, watch television (TV) wɒtʃ televɪʒən" },
      { term: "watch a DVD", ipa: "wɒtʃ ə diːviːdiː" },
    ],
  },
  {
    unit: 26,
    section: "Leisure",
    title: "Music and musical instruments",
    words: [
      { term: "band", ipa: "bænd" },
      { term: "cello", ipa: "ˈtʃeləʊ" },
      { term: "clarinet", ipa: "ˌklærɪˈnet" },
      { term: "classical music", ipa: "ˈklæsɪkəl ˈmjuːzɪk" },
      { term: "concert", ipa: "ˈkɒnsət" },
      { term: "download", ipa: "ˌdaʊnˈləʊd" },
      { term: "drums", ipa: "drʌmz" },
      { term: "flute", ipa: "fluːt" },
      { term: "flute-player", ipa: "fluːt ˈpleɪə" },
      { term: "folk music", ipa: "fəʊk ˈmjuːzɪk" },
      { term: "guitar", ipa: "gɪˈtɑː" },
      { term: "have a piano lesson", ipa: "hæv ə pɪˈænəʊ lesən" },
      { term: "jazz", ipa: "dʒæz" },
      { term: "learn", ipa: "lɜːn" },
      { term: "lesson(s)", ipa: "lesʌn" },
      { term: "listen (to)", ipa: "ˈlɪsən" },
      { term: "music", ipa: "ˈmjuːzɪk" },
      { term: "musical", ipa: "ˈmjuːzɪkəl" },
      { term: "musical instruments", ipa: "ˈmjuːzɪkəl ˈɪnstrəmənts" },
      { term: "musician", ipa: "mjuːˈzɪʃən" },
      { term: "opera", ipa: "ˈɒpərə" },
      { term: "orchestra", ipa: "ˈɔːkɪstrə" },
      { term: "pianist", ipa: "ˈpiːənɪst" },
      { term: "piano", ipa: "piˈænəʊ" },
      { term: "play a musical instrument", ipa: "pleɪ ə ˈmjuːzɪkəl ˈɪnstrəmənt" },
      { term: "play in an orchestra", ipa: "pleɪ ɪn æn ˈɔːkɪstrə" },
      { term: "pop music", ipa: "pɒp ˈmjuːzɪk" },
      { term: "rock", ipa: "rɒk" },
      { term: "song", ipa: "sɒŋ" },
      { term: "trumpet", ipa: "ˈtrʌmpɪt" },
      { term: "trumpet-player", ipa: "ˈtrʌmpɪt ˈpleɪə" },
      { term: "violin", ipa: "ˌvaɪəˈlɪn" },
      { term: "violinist", ipa: "vaɪəˈlɪnɪst" },
    ],
  },
  {
    unit: 27,
    section: "The world",
    title: "Countries and nationalities",
    words: [
      { term: "Africa", ipa: "ˈæfrɪkə" },
      { term: "American", ipa: "əˈmerɪkən" },
      { term: "Antarctica", ipa: "ˌænˈtɑːktɪkə" },
      { term: "Arabic", ipa: "ˈærəbɪk" },
      { term: "Argentina", ipa: "ˌɑːdʒənˈtiːnə" },
      { term: "Argentinian", ipa: "ˌɑːdʒənˈtɪnɪən" },
      { term: "Asia", ipa: "ˈeɪʒə" },
      { term: "Australasia", ipa: "ˌɒstrəˈleɪʒə" },
      { term: "Australia", ipa: "ɒsˈstreɪliə" },
      { term: "Australian", ipa: "ɒsˈstreɪliən" },
      { term: "Brazil", ipa: "brəˈzɪl" },
      { term: "Brazilian", ipa: "brəˈzɪljən" },
      { term: "British", ipa: "ˈbrɪtɪʃ" },
      { term: "Canada", ipa: "ˈkænədə" },
      { term: "Canadian", ipa: "kəˈneɪdiən" },
      { term: "Chile", ipa: "ˈtʃɪliː" },
      { term: "China", ipa: "ˈtʃaɪnə" },
      { term: "Chinese", ipa: "ˌtʃaɪˈniːz" },
      { term: "Colombia", ipa: "kəˈlɒmbiə" },
      { term: "Colombian", ipa: "kəˈlɒmbiən" },
      { term: "continent", ipa: "ˈkɒntɪnənt" },
      { term: "country", ipa: "ˈkʌntri" },
      { term: "Egypt", ipa: "ˈiːdʒɪpt" },
      { term: "Egyptian", ipa: "ɪˈdʒɪpʃən" },
      { term: "English", ipa: "ˈɪŋglɪʃ" },
      { term: "Europe", ipa: "ˈjʊərəp" },
      { term: "Finnish", ipa: "ˈfɪnɪʃ" },
      { term: "French", ipa: "frentʃ" },
      { term: "German", ipa: "ˈdʒɜːmən" },
      { term: "Germany", ipa: "ˈdʒɜːməni" },
      { term: "India", ipa: "ˈɪndiə" },
      { term: "Indian", ipa: "ˈɪndiən" },
      { term: "Irish", ipa: "ˈaɪrɪʃ" },
      { term: "Italian", ipa: "ɪˈtæliən" },
      { term: "Italy", ipa: "ˈɪtəli" },
      { term: "Japan", ipa: "dʒəˈpæn" },
      { term: "Japanese", ipa: "dʒæpnˈiːz" },
      { term: "Moroccan", ipa: "məˈrɒkən" },
      { term: "nationality", ipa: "næʃənˈæləti" },
      { term: "New Zealand", ipa: "ˌnjuː ˈziːlənd" },
      { term: "North America", ipa: "nɔːθ əˈmerɪkə" },
      { term: "Pakistan", ipa: "ˌpɑːkɪˈstɑːn" },
      { term: "Pakistani", ipa: "ˌpɑːkɪˈstɑːni" },
      { term: "Peru", ipa: "pəˈruː" },
      { term: "Peruvian", ipa: "pəˈruːviən" },
      { term: "Poland", ipa: "ˈpəʊlənd" },
      { term: "Polish", ipa: "ˈpəʊlɪʃ" },
      { term: "Portuguese", ipa: "ˌpɔːtʃəˈgiːz" },
      { term: "Scottish", ipa: "ˈskɒtɪʃ" },
      { term: "South Africa", ipa: "saʊθ ˈæfrɪkə" },
      { term: "South African", ipa: "saʊθ ˈæfrɪkən" },
      { term: "South America", ipa: "saʊθ əˈmerɪkə" },
      { term: "Spain", ipa: "speɪn" },
      { term: "Spanish", ipa: "ˈspænɪʃ" },
      { term: "Thai", ipa: "taɪ" },
      { term: "Thailand", ipa: "ˈtaɪlænd" },
      { term: "Tunisia", ipa: "tjuːˈnɪziə" },
      { term: "Tunisian", ipa: "tjuːˈnɪziən" },
      { term: "UK", ipa: "ˌjuːˈkeɪ" },
      { term: "United States (the US)", ipa: "juːˌnaɪtɪd ˈsteɪts" },
      { term: "USA", ipa: "ˌjuːesˈeɪ" },
    ],
  },
  {
    unit: 28,
    section: "The world",
    title: "Weather",
    words: [
      { term: "cloud", ipa: "klaʊd" },
      { term: "cloudy", ipa: "ˈklaʊdi" },
      { term: "cold", ipa: "kəʊld" },
      { term: "degrees", ipa: "dɪˈgriːz" },
      { term: "dry", ipa: "draɪ" },
      { term: "fog", ipa: "fɒg" },
      { term: "foggy", ipa: "ˈfɒgi" },
      { term: "hot", ipa: "hɒt" },
      { term: "hurricane", ipa: "ˈhʌrɪkən" },
      { term: "lightning", ipa: "ˈlaɪtnɪŋ" },
      { term: "minus", ipa: "ˈmaɪnəs" },
      { term: "rain", ipa: "reɪn" },
      { term: "rainy", ipa: "ˈreɪni" },
      { term: "snow", ipa: "snəʊ" },
      { term: "snowing", ipa: "ˈsnəʊɪŋ" },
      { term: "snowy", ipa: "ˈsnəʊi" },
      { term: "storm", ipa: "stɔːm" },
      { term: "sun", ipa: "sʌn" },
      { term: "sunny", ipa: "ˈsʌni" },
      { term: "thunder", ipa: "ˈθʌndə" },
      { term: "thunderstorm", ipa: "ˈθʌndəstɔːm" },
      { term: "thundery", ipa: "ˈθʌndəri" },
      { term: "weather", ipa: "ˈweðə" },
      { term: "wet", ipa: "wet" },
      { term: "wind", ipa: "wɪnd" },
      { term: "windy", ipa: "ˈwɪndi" },
    ],
  },
  {
    unit: 29,
    section: "The world",
    title: "In the town",
    words: [
      { term: "bank", ipa: "bæŋk" },
      { term: "bus", ipa: "bʌs" },
      { term: "bus station", ipa: "bʌs ˈsteɪʃən" },
      { term: "car", ipa: "kɑː" },
      { term: "car park", ipa: "kɑː pɑːk" },
      { term: "cash machine", ipa: "kæʃ məˈʃiːn" },
      { term: "change money", ipa: "tʃeɪndʒ ˈmʌni" },
      { term: "directions", ipa: "daɪˈrekʃns" },
      { term: "entrance", ipa: "ˈentrəns" },
      { term: "Excuse me", ipa: "ɪkˈskjuːs miː" },
      { term: "exit", ipa: "ˈeksɪt" },
      { term: "get a bus get", ipa: "ə bʌs" },
      { term: "get a train get", ipa: "ə treɪn" },
      { term: "get information get", ipa: "ˌɪnfəˈmeɪʃən" },
      { term: "get off get", ipa: "ɒf" },
      { term: "information", ipa: "ˌɪnfəˈmeɪʃən" },
      { term: "left", ipa: "left" },
      { term: "library", ipa: "ˈlaɪbrəri" },
      { term: "look for", ipa: "lʊk fɔː" },
      { term: "museum", ipa: "mjuːˈziːəm" },
      { term: "newspaper", ipa: "ˈnjuːzˌpeɪpə" },
      { term: "no smoking", ipa: "nəʊ ˈsməʊkɪŋ" },
      { term: "notice", ipa: "ˈnəʊtɪs" },
      { term: "number", ipa: "ˈnʌmbə" },
      { term: "on the left", ipa: "ɒn ðə left" },
      { term: "out of order", ipa: "aʊt əv ˈɔːdə" },
      { term: "park", ipa: "pɑːk" },
      { term: "pedestrian area", ipa: "pəˈdestriən ˈeəriə" },
      { term: "please keep off the grass", ipa: "pliːz kiːp ɒf ðə grɑːs" },
      { term: "post", ipa: "pəʊst" },
      { term: "post office", ipa: "pəʊst ˈɒfɪs" },
      { term: "railway station", ipa: "ˈreɪlweɪ ˈsteɪʃən" },
      { term: "right", ipa: "raɪt" },
      { term: "road", ipa: "rəʊd" },
      { term: "shop", ipa: "ʃɒp" },
      { term: "shopping centre", ipa: "ˈʃɒpɪŋ ˈsentə" },
      { term: "side", ipa: "saɪd" },
      { term: "station", ipa: "ˈsteɪʃən" },
      { term: "take the bus", ipa: "teɪk ðə bʌs" },
      { term: "tourist (information) office", ipa: "ˈtʊərɪst ˈɒfɪs" },
      { term: "town", ipa: "taʊn" },
      { term: "train", ipa: "treɪn" },
      { term: "train station", ipa: "treɪn ˈsteɪʃən" },
      { term: "turn", ipa: "tɜːn" },
    ],
  },
  {
    unit: 30,
    section: "The world",
    title: "In the countryside",
    words: [
      { term: "conservation area", ipa: "ˌkɒnsəˈveɪʃən ˈeəriə" },
      { term: "cottage", ipa: "ˈkɒtɪdʒ" },
      { term: "country", ipa: "ˈkʌntri" },
      { term: "country road", ipa: "ˈkʌntri rəʊd" },
      { term: "countryside", ipa: "ˈkʌntrɪsaɪd" },
      { term: "farm", ipa: "fɑːm" },
      { term: "farmer", ipa: "ˈfɑːmə" },
      { term: "field", ipa: "fiːld" },
      { term: "forest", ipa: "ˈfɒrɪst" },
      { term: "go skiing", ipa: "gəʊ ˈskiːɪŋ" },
      { term: "go walking", ipa: "gəʊ waːkɪŋ" },
      { term: "have a picnic", ipa: "hæv ə ˈpɪknɪk" },
      { term: "hill", ipa: "hɪl" },
      { term: "lake", ipa: "leɪk" },
      { term: "mountain", ipa: "ˈmaʊntɪn" },
      { term: "national park", ipa: "ˈnæʃənl pɑːk" },
      { term: "nature", ipa: "ˈneɪtʃə" },
      { term: "path", ipa: "pɑːθ" },
      { term: "river", ipa: "ˈrɪvə" },
      { term: "skiing", ipa: "ˈskiːɪŋ" },
      { term: "town", ipa: "taʊn" },
      { term: "village", ipa: "ˈvɪlɪdʒ" },
      { term: "walk", ipa: "wɔːk" },
      { term: "wildlife", ipa: "ˈwaɪldlaɪf" },
      { term: "wood", ipa: "wʊd" },
    ],
  },
  {
    unit: 31,
    section: "The world",
    title: "Animals",
    words: [
      { term: "animal", ipa: "ˈænɪməl" },
      { term: "bacon", ipa: "ˈbeɪkən" },
      { term: "beef", ipa: "biːf" },
      { term: "bird", ipa: "bɜːd" },
      { term: "calf", ipa: "kɑːf" },
      { term: "cat", ipa: "kæt" },
      { term: "chick", ipa: "tʃɪk" },
      { term: "chicken", ipa: "ˈtʃɪkɪn" },
      { term: "cow", ipa: "kaʊ" },
      { term: "dog", ipa: "dɒg" },
      { term: "egg", ipa: "eg" },
      { term: "elephant", ipa: "ˈelɪfənt" },
      { term: "farm animal", ipa: "fɑːm ˈænɪməl" },
      { term: "feed", ipa: "fiːd" },
      { term: "fish", ipa: "fɪʃ" },
      { term: "foal", ipa: "fəʊl" },
      { term: "giraffe", ipa: "dʒɪˈrɑːf" },
      { term: "give", ipa: "gɪv" },
      { term: "goat", ipa: "gəʊt" },
      { term: "hair", ipa: "heə" },
      { term: "ham", ipa: "hæm" },
      { term: "hen", ipa: "hen" },
      { term: "horse", ipa: "hɔːs" },
      { term: "kid", ipa: "kɪd" },
      { term: "lamb", ipa: "læm" },
      { term: "leather", ipa: "ˈleðə" },
      { term: "lion", ipa: "laɪən" },
      { term: "meat", ipa: "miːt" },
      { term: "milk", ipa: "mɪlk" },
      { term: "monkey", ipa: "ˈmʌŋki" },
      { term: "parrot", ipa: "ˈpærət" },
      { term: "pet", ipa: "pet" },
      { term: "pig", ipa: "pɪg" },
      { term: "piglet", ipa: "ˈpɪglət" },
      { term: "pork", ipa: "pɔːk" },
      { term: "rabbit", ipa: "ˈræbɪt" },
      { term: "sheep", ipa: "ʃiːp" },
      { term: "snake", ipa: "sneɪk" },
      { term: "tiger", ipa: "ˈtaɪgə" },
      { term: "tortoise", ipa: "ˈtɔːtəs" },
      { term: "water", ipa: "ˈwɔːtə" },
      { term: "wild animal", ipa: "waɪld ˈænɪməl" },
      { term: "wool", ipa: "wʊl" },
      { term: "zoo", ipa: "zuː" },
    ],
  },
  {
    unit: 32,
    section: "The world",
    title: "Travelling",
    words: [
      { term: "aeroplane", ipa: "ˈeərəpleɪn" },
      { term: "arrive", ipa: "əˈraɪv" },
      { term: "bicycle", ipa: "ˈbaɪsəkl" },
      { term: "bike", ipa: "baɪk" },
      { term: "boarding card", ipa: "ˈbɔːdɪŋ kɑːd" },
      { term: "boat", ipa: "bəʊt" },
      { term: "book", ipa: "bʊk" },
      { term: "book a seat", ipa: "bʊk ə siːt" },
      { term: "bus", ipa: "bʌs" },
      { term: "car", ipa: "kɑː" },
      { term: "change", ipa: "tʃeɪndʒ" },
      { term: "change trains", ipa: "tʃeɪndʒ treɪnz" },
      { term: "check", ipa: "tʃek" },
      { term: "check in", ipa: "tʃek ɪn" },
      { term: "check in online", ipa: "tʃek ɪn ˌɒnˈlaɪn" },
      { term: "customs", ipa: "ˈkʌstəmz" },
      { term: "depart", ipa: "dɪˈpɑːt" },
      { term: "direct", ipa: "dɪˈrekt" },
      { term: "fill up with", ipa: "fɪl ʌp wɪð" },
      { term: "flight", ipa: "flaɪt" },
      { term: "flight attendant", ipa: "flaɪt əˈtendənt" },
      { term: "give a lift", ipa: "gɪv ə lɪft" },
      { term: "go through customs", ipa: "gəʊ θruː ˈkɪstəms" },
      { term: "helicopter", ipa: "ˈhelɪkɒptə" },
      { term: "hire a car", ipa: "haɪə ə kɑː" },
      { term: "in advance", ipa: "ɪn ədˈvɑːns" },
      { term: "journey", ipa: "ˈdʒɜːni" },
      { term: "land", ipa: "lænd" },
      { term: "leave", ipa: "liːv" },
      { term: "luggage", ipa: "ˈlʌgɪdʒ" },
      { term: "map", ipa: "mæp" },
      { term: "motorbike", ipa: "ˈməʊtəbaɪk" },
      { term: "motorcycle", ipa: "ˈməʊtəˌsaɪkəl" },
      { term: "online check-in", ipa: "ˌɒnˈlaɪn tʃek ɪn" },
      { term: "passport", ipa: "ˈpɑːspɔːt" },
      { term: "petrol", ipa: "ˈpetrəl" },
      { term: "plane", ipa: "pleɪn" },
      { term: "reserve (a seat)", ipa: "rɪˈzɜːv" },
      { term: "restaurant car", ipa: "ˈrestrɒnt kɑː" },
      { term: "return ticket", ipa: "rɪˈtɜːn ˈtɪkɪt" },
      { term: "seat", ipa: "siːt" },
      { term: "ship", ipa: "ʃɪp" },
      { term: "single ticket", ipa: "ˈsɪŋgəl ˈtɪkɪt" },
      { term: "take off", ipa: "teɪk ɒf" },
      { term: "taxi", ipa: "ˈtæksi" },
      { term: "ticket", ipa: "ˈtɪkɪt" },
      { term: "timetable", ipa: "ˈtaɪmˌteɪbəl" },
      { term: "train", ipa: "treɪn" },
      { term: "transport", ipa: "ˈtrænspɔːt" },
      { term: "travelling", ipa: "ˈtrævəlɪŋ" },
      { term: "underground", ipa: "ˈʌndəgraʊnd" },
    ],
  },
  {
    unit: 33,
    section: "The world",
    title: "UK culture",
    words: [
      { term: "bank holiday", ipa: "bæŋk ˈhɒlədeɪ" },
      { term: "bonfire", ipa: "ˈbɒnfaɪə" },
      { term: "Bonfire Night", ipa: "ˈbɒnfaɪə naɪt" },
      { term: "chicken tikka masala", ipa: "ˈtʃɪkɪn tikə məˈsɑːlə" },
      { term: "Christmas", ipa: "ˈkrɪsməs" },
      { term: "Christmas tree", ipa: "ˈkrɪsməs triː" },
      { term: "curry", ipa: "ˈkʌri" },
      { term: "Easter", ipa: "ˈiːstə" },
      { term: "Easter eggs", ipa: "ˈiːstə egz" },
      { term: "festival", ipa: "ˈfestɪvl" },
      { term: "fireworks", ipa: "ˈfaɪəwɜːks" },
      { term: "fish and chips", ipa: "fɪʃ ənd tʃɪps" },
      { term: "Halloween", ipa: "ˌhæləʊˈiːn" },
      { term: "Hogmanay", ipa: "ˌhɒgməneɪ" },
      { term: "Houses of Parliament", ipa: "ˈhaʊzɪz əv ˈpɑːləmənt" },
      { term: "king", ipa: "kɪŋ" },
      { term: "nursery school", ipa: "ˈnɜːsri skuːl" },
      { term: "oven", ipa: "ˈʌvən" },
      { term: "primary school", ipa: "ˈpraɪməri skuːl" },
      { term: "Prime Minister", ipa: "praɪm ˈmɪnɪstə" },
      { term: "private school", ipa: "ˈpraɪvɪt skuːl" },
      { term: "queen", ipa: "kwiːn" },
      { term: "roast potatoes", ipa: "rəʊst pəˈteɪtəʊz" },
      { term: "royal family", ipa: "ˈrɔɪəl ˈfæməli" },
      { term: "secondary school", ipa: "ˈsekəndri skuːl" },
      { term: "state school", ipa: "steɪt skuːl" },
      { term: "Yorkshire pudding", ipa: "ˈjɔːkʃə ˈpʊdɪŋ" },
    ],
  },
  {
    unit: 34,
    section: "Social issues",
    title: "Crime",
    words: [
      { term: "arrest", ipa: "əˈrest" },
      { term: "attack", ipa: "əˈtæk" },
      { term: "break into", ipa: "breɪk ˈɪntə" },
      { term: "burglar", ipa: "ˈbɜːglə" },
      { term: "burglary", ipa: "ˈbɜːgləri" },
      { term: "car theft", ipa: "kɑː θeft" },
      { term: "car thief", ipa: "kɑː θiːf" },
      { term: "court", ipa: "kɔːt" },
      { term: "crime", ipa: "kraɪm" },
      { term: "criminal", ipa: "ˈkrɪmɪnəl" },
      { term: "drug dealer", ipa: "drʌg ˈdiːlə" },
      { term: "drug dealing", ipa: "drʌg ˈdiːlɪŋ" },
      { term: "drugs", ipa: "drʌgz" },
      { term: "fine", ipa: "faɪn" },
      { term: "football hooligan", ipa: "ˈfʊtbɔːl ˈhuːlɪgən" },
      { term: "football hooliganism", ipa: "ˈfʊtbɔːl ˈhuːlɪgənɪzəm" },
      { term: "go to court", ipa: "gəʊ tə kɔːt" },
      { term: "go to prison", ipa: "gəʊ tə ˈprɪzn" },
      { term: "guilty", ipa: "ˈgɪlti" },
      { term: "hooligan", ipa: "ˈhuːlɪgən" },
      { term: "innocent", ipa: "ˈɪnəsənt" },
      { term: "law", ipa: "lɔː" },
      { term: "mug", ipa: "mʌg" },
      { term: "mugger", ipa: "ˈmʌgə" },
      { term: "mugging", ipa: "ˈmʌgɪŋ" },
      { term: "murder", ipa: "ˈmɜːdə" },
      { term: "murderer", ipa: "ˈmɜːdərə" },
      { term: "pay", ipa: "peɪ" },
      { term: "pay a fine pei", ipa: "ə faɪn" },
      { term: "police", ipa: "pəˈliːs" },
      { term: "prison", ipa: "ˈprɪzən" },
      { term: "rob", ipa: "rɒb" },
      { term: "robber", ipa: "ˈrɒbə" },
      { term: "robbery", ipa: "ˈrɒbəri" },
      { term: "sell", ipa: "sel" },
      { term: "sell drugs sel", ipa: "drʌgz" },
      { term: "shoplifter", ipa: "ʃɒplɪftə" },
      { term: "shoplifting", ipa: "ˈʃɒplɪftɪŋ" },
      { term: "steal", ipa: "stiːl" },
      { term: "take", ipa: "teɪk" },
      { term: "take drugs", ipa: "teɪk drʌgz" },
      { term: "terrorism", ipa: "ˈterərɪzəm" },
      { term: "terrorist", ipa: "ˈterərɪst" },
      { term: "thief", ipa: "θiːf" },
      { term: "vandal", ipa: "ˈvændəl" },
      { term: "vandalism", ipa: "ˈvændəlɪzəm" },
    ],
  },
  {
    unit: 35,
    section: "Social issues",
    title: "The media",
    words: [
      { term: "advert", ipa: "ˈædvɜːt" },
      { term: "advertisement", ipa: "ədˈvɜːtɪsmənt" },
      { term: "cartoon", ipa: "kɑːˈtuːn" },
      { term: "change", ipa: "tʃeɪndʒ" },
      { term: "change the channel", ipa: "tʃeɪndʒ ðə ˈtʃænl" },
      { term: "channel", ipa: "ˈtʃænəl" },
      { term: "computer", ipa: "kəmˈpjuːtə" },
      { term: "computer magazine", ipa: "kəmˈpjuːtə ˌmægəˈzin" },
      { term: "documentary", ipa: "ˌdɒkjəˈmentə ri" },
      { term: "evening", ipa: "ˈiːvnɪŋ" },
      { term: "favourite", ipa: "ˈfeɪvərɪt" },
      { term: "interview (with)", ipa: "ˈɪntəvjuː" },
      { term: "journalist", ipa: "ˈdʒɜːnəlɪst" },
      { term: "magazine", ipa: "ˌmægəˈziːn" },
      { term: "media", ipa: "ˈmiːdiə" },
      { term: "morning", ipa: "ˈmɔːnɪŋ" },
      { term: "nature", ipa: "ˈneɪtʃə" },
      { term: "news", ipa: "njuːz" },
      { term: "newspaper", ipa: "ˈnjuːzˌpeɪpə" },
      { term: "online", ipa: "ˌɒnˈlaɪn" },
      { term: "paper", ipa: "ˈpeɪpə" },
      { term: "programme", ipa: "ˈprəʊgræm" },
      { term: "radio", ipa: "ˈreɪdiəʊ" },
      { term: "read", ipa: "riːd" },
      { term: "reality TV", ipa: "riˈæləti ˌtiːˈviː" },
      { term: "reporter", ipa: "rɪˈpɔːtə" },
      { term: "soap opera", ipa: "ˈsəʊpˌɒpərə" },
      { term: "sports", ipa: "spɔːts" },
      { term: "sports magazine", ipa: "spɔːts mægəˈziːn" },
      { term: "sports programme", ipa: "spɔːts prəʊgræm" },
      { term: "talk show", ipa: "tɔːk ʃəʊ" },
      { term: "teenage", ipa: "ˈtiːneɪdʒ" },
      { term: "teenage magazine", ipa: "tiːneɪdʒ ˌmægəˈziːn" },
      { term: "television (TV)", ipa: "ˈtelɪvɪʒən" },
      { term: "TV", ipa: "ˌtiːˈviː" },
      { term: "women's magazine", ipa: "ˈwɪmɪnz mægəˈziːn" },
    ],
  },
  {
    unit: 36,
    section: "Social issues",
    title: "Problems at home and work",
    words: [
      { term: "apologise", ipa: "əˈpɒlədʒaɪz" },
      { term: "bad mood", ipa: "bæd muːd" },
      { term: "broken", ipa: "ˈbrəʊkən" },
      { term: "computer", ipa: "kəmˈpjuːtə" },
      { term: "computer crashed", ipa: "kəmˈpjuːtə kræʃd" },
      { term: "crash", ipa: "kræʃ" },
      { term: "cut", ipa: "kʌt" },
      { term: "die", ipa: "daɪ" },
      { term: "have a bad day", ipa: "hæv ə bæd deɪ" },
      { term: "have a row with", ipa: "hæv ə rəʊ wɪð" },
      { term: "home", ipa: "həʊm" },
      { term: "in a bad mood", ipa: "ɪn ə bæd muːd" },
      { term: "late for", ipa: "leɪt fə" },
      { term: "look for", ipa: "lʊk fɔː" },
      { term: "lose", ipa: "luːz" },
      { term: "mend", ipa: "mend" },
      { term: "mood", ipa: "muːd" },
      { term: "out of order", ipa: "aʊt əv ˈɔːdə" },
      { term: "plaster", ipa: "ˈplɑːstə" },
      { term: "put on", ipa: "pʊt ɒn" },
      { term: "repair", ipa: "rɪˈpeə" },
      { term: "row", ipa: "raʊ" },
      { term: "tidy", ipa: "ˈtaɪdi" },
      { term: "too much (work)", ipa: "tuː mʌtʃ" },
      { term: "untidy", ipa: "ʌnˈtaɪdi" },
      { term: "watch TV online", ipa: "wɒtʃ tiːviː ɒnlaɪn" },
      { term: "water", ipa: "ˈwɔːtə" },
      { term: "work", ipa: "wɜːk" },
    ],
  },
  {
    unit: 37,
    section: "Social issues",
    title: "Global problems",
    words: [
      { term: "air pollution", ipa: "eə pəˈluːʃən" },
      { term: "car crash", ipa: "kɑː kræʃ" },
      { term: "crowded", ipa: "ˈkraʊdɪd" },
      { term: "disaster", ipa: "dɪˈzɑːstə" },
      { term: "earthquake", ipa: "ˈɜːθkweɪk" },
      { term: "flood", ipa: "flʌd" },
      { term: "forest fire", ipa: "ˈfɒrɪst faɪə" },
      { term: "global", ipa: "ˈgləʊbəl" },
      { term: "homeless", ipa: "ˈhəʊmləs" },
      { term: "hungry", ipa: "ˈhʌŋgri" },
      { term: "hurricane", ipa: "ˈhʌrɪkən" },
      { term: "man-made", ipa: "ˌmænˈmeɪd" },
      { term: "natural disaster", ipa: "ˈnætʃrəl dɪˈzɑːstə" },
      { term: "on strike", ipa: "ɒn straɪk" },
      { term: "polluted", ipa: "pəˈluːtɪd" },
      { term: "pollution", ipa: "pəˈluːʃən" },
      { term: "poor", ipa: "pɔː" },
      { term: "problem", ipa: "ˈprɒbləm" },
      { term: "rush hour", ipa: "rʌʃ aʊə" },
      { term: "snowstorm", ipa: "ˈsnəʊstɔːm" },
      { term: "strike", ipa: "straɪk" },
      { term: "traffic jam", ipa: "ˈtræfɪk dʒæm" },
      { term: "unemployed", ipa: "ˌʌnɪmˈplɔɪd" },
      { term: "war", ipa: "wɔː" },
    ],
  },
  {
    unit: 38,
    section: "Everyday verbs",
    title: "Have / had / had",
    words: [
      { term: "bath", ipa: "bɑːθ" },
      { term: "breakfast", ipa: "ˈbrekfəst" },
      { term: "cheese", ipa: "tʃiːz" },
      { term: "coffee", ipa: "ˈkɒfi" },
      { term: "cold", ipa: "kəʊld" },
      { term: "cup of tea", ipa: "kʌp əv tiː" },
      { term: "drink", ipa: "drɪŋk" },
      { term: "exam", ipa: "ɪgˈzæm" },
      { term: "game", ipa: "geɪm" },
      { term: "haircut", ipa: "ˈheəkʌt" },
      { term: "have", ipa: "hæv" },
      { term: "have (your) hair cut", ipa: "hæv heə kʌt" },
      { term: "have a bath", ipa: "hæv ə bɑːθ" },
      { term: "have a cold", ipa: "hæv ə kəʊld" },
      { term: "have a cup of tea (coffee)", ipa: "hæv ə kʌp ɒv tiː" },
      { term: "have a drink", ipa: "hæv ə drɪŋk" },
      { term: "have a game", ipa: "hæv ə geɪm" },
      { term: "have a go", ipa: "hæv ə gəʊ" },
      { term: "have a good journey", ipa: "hæv ə gʊd ˈdʒɜːni" },
      { term: "have a good time", ipa: "hæv ə gʊd taɪm" },
      { term: "have a headache", ipa: "hæv ə ˈhedeɪk" },
      { term: "have a lesson", ipa: "hæv ə ˈlesən" },
      { term: "have a look", ipa: "hæv ə lʊk" },
      { term: "have a meal", ipa: "hæv ə miːl" },
      { term: "have a meeting", ipa: "hæv ə ˈmiːtɪŋ" },
      { term: "have a moment", ipa: "hæv ə ˈməʊmənt" },
      { term: "have a party", ipa: "hæv ə ˈpɑːti" },
      { term: "have a swim", ipa: "hæv ə swɪm" },
      { term: "have a word with", ipa: "hæv ə wɜːd wɪð" },
      { term: "have an exam", ipa: "hæv ən ɪgˈzæm" },
      { term: "have breakfast", ipa: "hæv ˈbrekfəst" },
      { term: "have coffee", ipa: "hæv ˈkɒfi" },
      { term: "have dinner", ipa: "hæv ˈdɪnə" },
      { term: "have got", ipa: "hæv gɒt" },
      { term: "have homework", ipa: "hæv həʊmwɜːk" },
      { term: "have lunch", ipa: "hæv lʌnʃ" },
      { term: "have the time", ipa: "hæv ðə taɪm" },
      { term: "have to", ipa: "hæv tuː" },
      { term: "headache", ipa: "ˈhedeɪk" },
      { term: "homework", ipa: "ˈhəʊmwɜːk" },
      { term: "ice cream", ipa: "ˌaɪsˈkriːm" },
      { term: "lesson(s)", ipa: "lesʌn" },
      { term: "lunch", ipa: "lʌntʃ" },
      { term: "meal", ipa: "miːl" },
      { term: "moment", ipa: "ˈməʊmənt" },
      { term: "party", ipa: "ˈpɑːti" },
      { term: "shower", ipa: "ʃaʊə" },
      { term: "swim", ipa: "swɪm" },
      { term: "tea", ipa: "tiː" },
    ],
  },
  {
    unit: 39,
    section: "Everyday verbs",
    title: "Go / went / gone",
    words: [
      { term: "go", ipa: "gəʊ" },
      { term: "go by", ipa: "gəʊ baɪ" },
      { term: "go dancing", ipa: "gəʊ ˈdɑːntsɪŋ" },
      { term: "go down", ipa: "gəʊ daʊn" },
      { term: "go fishing", ipa: "gəʊ ˈfɪʃɪŋ" },
      { term: "go in", ipa: "gəʊ ɪn" },
      { term: "go into", ipa: "gəʊ ˈɪntə" },
      { term: "go out of", ipa: "gəʊ aʊt ɒv" },
      { term: "go shopping", ipa: "gəʊ ˈʃɒpɪŋ" },
      { term: "go sightseeing", ipa: "gəʊ ˈsaɪtsiːɪŋ" },
      { term: "go skiing", ipa: "gəʊ ˈskiːɪŋ" },
      { term: "go swimming", ipa: "gəʊ ˈswɪmɪŋ" },
      { term: "go up", ipa: "gəʊ ʌp" },
      { term: "going to", ipa: "ˈgəʊɪŋ tuː" },
    ],
  },
  {
    unit: 40,
    section: "Everyday verbs",
    title: "Do / did / done",
    words: [
      { term: "do", ipa: "duː" },
      { term: "do business with", ipa: "duː ˈbɪznɪs wɪð" },
      { term: "do homework", ipa: "duː ˈhəʊmwɜːk" },
      { term: "do some exercise(s)", ipa: "duː sʌm ˈeksəsaɪz" },
      { term: "do the gardening", ipa: "duː ðə ˈgɑːdənɪŋ" },
      { term: "do the housework", ipa: "duː ðə ˈhaʊswɜːk" },
      { term: "do the washing", ipa: "duː ðə ˈwɒʃɪŋ" },
      { term: "do the washing-up", ipa: "duː ðə ˈwɒʃɪŋ ʌp" },
      { term: "do your best", ipa: "duː jɔː best" },
      { term: "make", ipa: "meɪk" },
    ],
  },
  {
    unit: 41,
    section: "Everyday verbs",
    title: "Make / made / made",
    words: [
      { term: "make a choice", ipa: "meɪk ə tʃɔɪs" },
      { term: "make a film", ipa: "meɪk ə fɪlm" },
      { term: "make a mess", ipa: "meɪk ə mes" },
      { term: "make a mistake", ipa: "meɪk ə mɪsˈteɪk" },
      { term: "make a noise", ipa: "meɪk ə nɔɪz" },
      { term: "make a photocopy", ipa: "meɪk ə ˈfəʊtəˌkɒpi" },
      { term: "make a video", ipa: "meɪk ə ˈvɪdɪəʊ" },
      { term: "make an appointment", ipa: "meɪk ən əˈpɔɪntmənt" },
      { term: "make breakfast", ipa: "meɪk ˈbrekfəst" },
      { term: "make dinner", ipa: "meɪk ˈdɪnə" },
      { term: "make hot chocolate", ipa: "meɪk hɒt ˈtʃɒklət" },
      { term: "make lunch", ipa: "meɪk lʌntʃ" },
      { term: "make my bed", ipa: "meɪk maɪ bed" },
      { term: "make some coffee", ipa: "meɪk səm ˈkɒfi" },
      { term: "make some tea", ipa: "meɪk səm tiː" },
    ],
  },
  {
    unit: 42,
    section: "Everyday verbs",
    title: "Come / came / come",
    words: [
      { term: "come", ipa: "kʌm" },
      { term: "come along", ipa: "kʌm əˈlɒŋ" },
      { term: "come and see me", ipa: "kʌm ənd siː miː" },
      { term: "come back", ipa: "kʌm bæk" },
      { term: "come back from", ipa: "kʌm bæk frɒm" },
      { term: "come from", ipa: "kʌm frɒm" },
      { term: "come home", ipa: "kʌm həʊm" },
      { term: "come in", ipa: "kʌm ɪn" },
      { term: "come into", ipa: "kʌm ˈɪntə" },
      { term: "come out", ipa: "kʌm aʊt" },
      { term: "come out of", ipa: "kʌm aʊt ɒv" },
      { term: "go", ipa: "gəʊ" },
    ],
  },
  {
    unit: 43,
    section: "Everyday verbs",
    title: "Take / took / taken",
    words: [
      { term: "photo", ipa: "ˈfəʊtəʊ" },
      { term: "photograph", ipa: "ˈfəʊtəgrɑːf" },
      { term: "take", ipa: "teɪk" },
      { term: "take (some) lessons", ipa: "teɪk ˈlesənz" },
      { term: "take a course", ipa: "teɪk ə kɔːs" },
      { term: "take a photo", ipa: "teɪk ə ˈfəʊtəʊ" },
      { term: "take a taxi", ipa: "teɪk ə ˈtæksi" },
      { term: "take an exam", ipa: "teɪk ən ɪgˈzæm" },
      { term: "take the bus", ipa: "teɪk ðə bʌs" },
      { term: "take the train", ipa: "teɪk ðə treɪn" },
      { term: "take the underground", ipa: "teɪk ðə ˈʌndəgraʊnd" },
      { term: "taxi", ipa: "ˈtæksi" },
    ],
  },
  {
    unit: 44,
    section: "Everyday verbs",
    title: "Bring / brought / brought",
    words: [
      { term: "bring", ipa: "brɪŋ" },
      { term: "bring back", ipa: "brɪŋ bæk" },
      { term: "take", ipa: "teɪk" },
    ],
  },
  {
    unit: 45,
    section: "Everyday verbs",
    title: "Get / got / got",
    words: [
      { term: "get", ipa: "get" },
      { term: "get back get", ipa: "bæk" },
      { term: "get married get", ipa: "ˈmærɪd" },
      { term: "get to get", ipa: "tuː" },
    ],
  },
  {
    unit: 46,
    section: "Everyday verbs",
    title: "Phrasal verbs",
    words: [
      { term: "come on", ipa: "kʌm ɒn" },
      { term: "get off get", ipa: "ɒf" },
      { term: "get on get", ipa: "ɒn" },
      { term: "get up get", ipa: "ʌp" },
      { term: "go off", ipa: "gəʊ ɒf" },
      { term: "go on", ipa: "gəʊ ɒn" },
      { term: "put on", ipa: "pʊt ɒn" },
      { term: "take off", ipa: "teɪk ɒf" },
      { term: "turn down", ipa: "tɜːn daʊn" },
      { term: "turn off", ipa: "tɜːn ɒf" },
      { term: "turn on", ipa: "tɜːn ɒn" },
      { term: "turn up", ipa: "tɜːn ʌp" },
    ],
  },
  {
    unit: 47,
    section: "Everyday verbs",
    title: "Everyday things",
    words: [
      { term: "by bus", ipa: "baɪ bʌs" },
      { term: "by car", ipa: "baɪ kɑː" },
      { term: "by train", ipa: "baɪ treɪn" },
      { term: "call a friend", ipa: "kɔːl ə frend" },
      { term: "clean the house", ipa: "kliːn ðə haʊs" },
      { term: "come home", ipa: "kʌm həʊm" },
      { term: "get up get", ipa: "ʌp" },
      { term: "go for a walk", ipa: "gəʊ fɔːr ə wɔːk" },
      { term: "go to bed", ipa: "gəʊ tə bed" },
      { term: "go to the bathroom", ipa: "gəʊ tə ðə ˈbɑːθrʊm" },
      { term: "go to work", ipa: "gəʊ tə wɜːk" },
      { term: "have a shower", ipa: "hæv ə ˈʃaʊə" },
      { term: "have breakfast", ipa: "hæv ˈbrekfəst" },
      { term: "listen (to)", ipa: "ˈlɪsən" },
      { term: "make dinner", ipa: "meɪk ˈdɪnə" },
      { term: "normally", ipa: "ˈnɔːməli" },
      { term: "phone a friend", ipa: "fəʊn ə frend" },
      { term: "sometimes", ipa: "ˈsʌmtaɪmz" },
      { term: "usually", ipa: "ˈjuːʒəli" },
      { term: "wake up", ipa: "weɪk ʌp" },
      { term: "wash clothes", ipa: "wɒʃ kləʊðz" },
      { term: "watch", ipa: "wɒtʃ 4, 23, 24, watch television (TV) wɒtʃ televɪʒən" },
      { term: "write emails", ipa: "raɪt iːmeilz" },
      { term: "write letters", ipa: "raɪt ˈletəz" },
    ],
  },
  {
    unit: 48,
    section: "Everyday verbs",
    title: "Talking",
    words: [
      { term: "answer", ipa: "ˈɑːnsər" },
      { term: "ask", ipa: "ɑːsk" },
      { term: "ask (someone) the time", ipa: "ɑːsk ðə taɪm" },
      { term: "ask (someone) the way", ipa: "ɑːsk ðə weɪ" },
      { term: "ask for", ipa: "ɑːsk fɔː" },
      { term: "ask someone for something", ipa: "ɑːsk ˈsʌmwʌn fɔːˈsʌmθɪŋ" },
      { term: "ask someone to do something", ipa: "ɑːsk ˈsʌmwʌn tuː duː ˈsʌmθɪŋ" },
      { term: "Congratulations", ipa: "kənˌgrætʃʊˈleɪʃənz" },
      { term: "Goodbye", ipa: "gʊdˈbaɪ" },
      { term: "Happy Birthday", ipa: "ˈhæpi ˈbɜːθdeɪ" },
      { term: "Happy New Year", ipa: "ˈhæpi njuː jɪə" },
      { term: "hello", ipa: "heˈləʊ" },
      { term: "Merry Christmas", ipa: "ˈmeri ˈkrɪsməs" },
      { term: "please", ipa: "pliːz" },
      { term: "reply", ipa: "rɪˈplaɪ" },
      { term: "say", ipa: "seɪ" },
      { term: "speak", ipa: "spiːk" },
      { term: "talk", ipa: "tɔːk" },
      { term: "tell (someone) a joke tel", ipa: "ə dʒəʊk" },
      { term: "tell (someone) a story tel", ipa: "ə ˈstɔːri" },
      { term: "tell (someone) the time tel", ipa: "ðə taɪm" },
      { term: "tell someone your address tel", ipa: "ˈsʌmwʌn jɔː əˈdres" },
      { term: "tell someone your name tel", ipa: "ˈsʌmwʌn jɔː neɪm" },
      { term: "tell someone your phone number tel", ipa: "ˈsʌmwʌn jɔː fəʊn ˈnʌmbə" },
      { term: "Thank you", ipa: "θæŋk juː" },
    ],
  },
  {
    unit: 49,
    section: "Everyday verbs",
    title: "Moving",
    words: [
      { term: "arrive at", ipa: "əˈraɪv æt" },
      { term: "arrive in", ipa: "əˈraɪv ɪn" },
      { term: "carry", ipa: "ˈkæri" },
      { term: "catch", ipa: "kætʃ" },
      { term: "climb", ipa: "klaɪm" },
      { term: "dance", ipa: "dɑːns" },
      { term: "drive", ipa: "draɪv" },
      { term: "fall", ipa: "fɔːl" },
      { term: "fly", ipa: "flaɪ" },
      { term: "go by", ipa: "gəʊ baɪ" },
      { term: "in", ipa: "ɪn" },
      { term: "jump", ipa: "dʒʌmp" },
      { term: "miss", ipa: "mɪs" },
      { term: "pass", ipa: "pɑːs" },
      { term: "ride", ipa: "raɪd" },
      { term: "run", ipa: "rʌn" },
      { term: "swim", ipa: "swɪm" },
      { term: "take", ipa: "teɪk" },
      { term: "transport", ipa: "ˈtrænspɔːt" },
      { term: "walk", ipa: "wɔːk" },
    ],
  },
  {
    unit: 50,
    section: "Words and grammar",
    title: "Conjunctions and connecting words",
    words: [
      { term: "after", ipa: "ˈɑːftə" },
      { term: "also", ipa: "ˈɔːlsəʊ" },
      { term: "and", ipa: "ænd" },
      { term: "as well", ipa: "æz wel" },
      { term: "because", ipa: "bɪˈkɒz" },
      { term: "before", ipa: "bɪˈfɔː" },
      { term: "but", ipa: "bʌt" },
      { term: "even", ipa: "ˈiːvən" },
      { term: "if", ipa: "ɪf" },
      { term: "like", ipa: "laɪk" },
      { term: "only", ipa: "ˈəʊnli" },
      { term: "or", ipa: "ɔː" },
      { term: "so", ipa: "səʊ" },
      { term: "than", ipa: "ðæn" },
      { term: "too", ipa: "tuː" },
      { term: "when", ipa: "wen" },
    ],
  },
  {
    unit: 51,
    section: "Words and grammar",
    title: "Days, months, seasons",
    words: [
      { term: "afternoon", ipa: "ˌɑːftəˈnuːn" },
      { term: "April", ipa: "ˈeɪprəl" },
      { term: "August", ipa: "ˈɔːgəst" },
      { term: "autumn", ipa: "ˈɔːtəm" },
      { term: "century", ipa: "ˈsentʃəri" },
      { term: "day", ipa: "deɪ" },
      { term: "day after tomorrow dei", ipa: "ɑːftə təˈmɒrəvʊ" },
      { term: "day before yesterday dei", ipa: "bɪˈfɔːr jestədei" },
      { term: "December", ipa: "dɪˈsembə" },
      { term: "evening", ipa: "ˈiːvnɪŋ" },
      { term: "February", ipa: "ˈfebruəri" },
      { term: "fortnight", ipa: "ˈfɔːtnaɪt" },
      { term: "Friday", ipa: "ˈfraɪdeɪ" },
      { term: "hour", ipa: "aʊə" },
      { term: "January", ipa: "ˈdʒænjuəri" },
      { term: "July", ipa: "dʒuˈlaɪ" },
      { term: "June", ipa: "dʒuːn" },
      { term: "leap year", ipa: "liːp jɪə" },
      { term: "March", ipa: "mɑːtʃ" },
      { term: "May", ipa: "meɪ" },
      { term: "minute", ipa: "mɪnɪt" },
      { term: "Monday", ipa: "ˈmʌndeɪ" },
      { term: "month", ipa: "mʌnθ" },
      { term: "morning", ipa: "ˈmɔːnɪŋ" },
      { term: "November", ipa: "nəˈvembə" },
      { term: "October", ipa: "ɒkˈtəʊbə" },
      { term: "Saturday", ipa: "ˈsætədeɪ" },
      { term: "season", ipa: "ˈsiːzən" },
      { term: "second", ipa: "ˈsekənd" },
      { term: "September", ipa: "sepˈtembə" },
      { term: "spring", ipa: "sprɪŋ" },
      { term: "summer", ipa: "ˈsʌmə" },
      { term: "Sunday", ipa: "ˈsʌndeɪ" },
      { term: "Thursday", ipa: "ˈθɜːzdeɪ" },
      { term: "time", ipa: "taɪm" },
      { term: "today", ipa: "təˈdeɪ" },
      { term: "tomorrow", ipa: "təˈmɒrəʊ" },
      { term: "Tuesday", ipa: "ˈtjuːzdeɪ" },
      { term: "Wednesday", ipa: "ˈwenzdeɪ" },
      { term: "week", ipa: "wiːk" },
      { term: "weekend", ipa: "ˌwiːkˈend" },
      { term: "winter", ipa: "ˈwɪntə" },
      { term: "year", ipa: "jɪə" },
      { term: "yesterday", ipa: "ˈjestədeɪ" },
    ],
  },
  {
    unit: 52,
    section: "Words and grammar",
    title: "Time words",
    words: [
      { term: "ago", ipa: "əˈgəʊ" },
      { term: "always", ipa: "ˈɔːlweɪz" },
      { term: "at the moment", ipa: "æt ðə ˈməʊmənt" },
      { term: "future", ipa: "ˈfjuːtʃə" },
      { term: "hour", ipa: "aʊə" },
      { term: "in a moment", ipa: "ɪn ə ˈməʊmənt" },
      { term: "last", ipa: "lɑːst" },
      { term: "moment", ipa: "ˈməʊmənt" },
      { term: "never", ipa: "ˈnevə" },
      { term: "next", ipa: "nekst" },
      { term: "not often", ipa: "nɒt ˈɒfən" },
      { term: "now", ipa: "naʊ" },
      { term: "now and then", ipa: "naʊ ən ðen" },
      { term: "occasionally", ipa: "əˈkeɪʒnəli" },
      { term: "often", ipa: "ˈɒfən" },
      { term: "once", ipa: "wʌns" },
      { term: "past", ipa: "pɑːst" },
      { term: "present", ipa: "ˈprezənt" },
      { term: "rarely", ipa: "ˈreəli" },
      { term: "recently", ipa: "ˈriːsəntli" },
      { term: "sometimes", ipa: "ˈsʌmtaɪmz" },
      { term: "soon", ipa: "suːn" },
      { term: "then", ipa: "ðen" },
      { term: "time", ipa: "taɪm" },
      { term: "today", ipa: "təˈdeɪ" },
      { term: "tomorrow", ipa: "təˈmɒrəʊ" },
      { term: "twice", ipa: "twaɪs" },
      { term: "usually", ipa: "ˈjuːʒəli" },
      { term: "week", ipa: "wiːk" },
      { term: "year", ipa: "jɪə" },
    ],
  },
  {
    unit: 53,
    section: "Words and grammar",
    title: "Places",
    words: [
      { term: "abroad", ipa: "əˈbrɔːd" },
      { term: "at", ipa: "æt" },
      { term: "at home", ipa: "æt həʊm" },
      { term: "away", ipa: "əˈweɪ" },
      { term: "back", ipa: "bæk" },
      { term: "beginning", ipa: "bɪˈgɪnɪŋ" },
      { term: "bottom", ipa: "ˈbɒtəm" },
      { term: "end", ipa: "end" },
      { term: "everywhere", ipa: "ˈevrɪweə" },
      { term: "front", ipa: "frʌnt" },
      { term: "here", ipa: "hɪə" },
      { term: "home", ipa: "həʊm" },
      { term: "in", ipa: "ɪn" },
      { term: "left", ipa: "left" },
      { term: "middle", ipa: "ˌmɪdəl" },
      { term: "on", ipa: "ɒn" },
      { term: "on the left", ipa: "ɒn ðə left" },
      { term: "on the right", ipa: "ɒn ðə raɪt" },
      { term: "out", ipa: "aʊt" },
      { term: "position", ipa: "pəˈzɪʃən" },
      { term: "right", ipa: "raɪt" },
      { term: "side", ipa: "saɪd" },
      { term: "there", ipa: "ðeə" },
      { term: "top", ipa: "tɒp" },
    ],
  },
  {
    unit: 54,
    section: "Words and grammar",
    title: "Manner",
    words: [
      { term: "bad", ipa: "bæd" },
      { term: "badly", ipa: "ˈbædli" },
      { term: "fast", ipa: "fɑːst" },
      { term: "friendly", ipa: "ˈfrendli" },
      { term: "good", ipa: "gʊd" },
      { term: "loud", ipa: "laʊd" },
      { term: "loudly", ipa: "ˈlaʊdli" },
      { term: "manner", ipa: "ˈmænə" },
      { term: "quiet", ipa: "ˈkwaɪət" },
      { term: "quietly", ipa: "ˈkwaɪətli" },
      { term: "right", ipa: "raɪt" },
      { term: "right way", ipa: "raɪt wei" },
      { term: "slow", ipa: "sləʊ" },
      { term: "slowly", ipa: "ˈsləʊli" },
      { term: "way", ipa: "weɪ" },
      { term: "well", ipa: "wel" },
      { term: "wrong (way)", ipa: "rɒŋ" },
    ],
  },
  {
    unit: 55,
    section: "Words and grammar",
    title: "Common uncountable nouns",
    words: [
      { term: "accommodation", ipa: "əˌkɒməˈdeɪʃən" },
      { term: "advice", ipa: "ədˈvaɪs" },
      { term: "air", ipa: "eə" },
      { term: "apple", ipa: "ˈæpəl" },
      { term: "bread", ipa: "bred" },
      { term: "butter", ipa: "ˈbʌtə" },
      { term: "coffee", ipa: "ˈkɒfi" },
      { term: "countable", ipa: "ˈkaʊntəbəl" },
      { term: "furniture", ipa: "ˈfɜːnɪtʃə" },
      { term: "information", ipa: "ˌɪnfəˈmeɪʃən" },
      { term: "kilo", ipa: "ˈkiːləʊ" },
      { term: "litre", ipa: "ˈliːtə" },
      { term: "loaf", ipa: "ləʊf" },
      { term: "luggage", ipa: "ˈlʌgɪdʒ" },
      { term: "milk", ipa: "mɪlk" },
      { term: "money", ipa: "ˈmʌni" },
      { term: "news", ipa: "njuːz" },
      { term: "plate", ipa: "pleɪt" },
      { term: "rice", ipa: "raɪs" },
      { term: "shoe(s)", ipa: "ʃuː" },
      { term: "spaghetti", ipa: "spəˈgeti" },
      { term: "sugar", ipa: "ˈʃʊgə" },
      { term: "tea", ipa: "tiː" },
      { term: "traffic", ipa: "ˈtræfɪk" },
      { term: "travel", ipa: "ˈtrævəl" },
      { term: "uncountable", ipa: "ʌnˈkaʊntəbəl" },
      { term: "water", ipa: "ˈwɔːtə" },
      { term: "weather", ipa: "ˈweðə" },
      { term: "work", ipa: "wɜːk" },
    ],
  },
  {
    unit: 56,
    section: "Words and grammar",
    title: "Common adjectives: Good and bad things",
    words: [
      { term: "awful", ipa: "ˈɔːfəl" },
      { term: "bad", ipa: "bæd" },
      { term: "dreadful", ipa: "ˈdredfəl" },
      { term: "excellent", ipa: "ˈeksələnt" },
      { term: "good", ipa: "gʊd" },
      { term: "great", ipa: "greɪt" },
      { term: "horrible", ipa: "ˈhɒrəbl" },
      { term: "How (awful)", ipa: "haʊ" },
      { term: "lovely", ipa: "ˈlʌvli" },
      { term: "nice", ipa: "naɪs" },
      { term: "not bad", ipa: "nɒt bæd" },
      { term: "perfect", ipa: "ˈpɜːfəkt" },
      { term: "terrible", ipa: "ˈterəbəl" },
      { term: "very (bad / good)", ipa: "ˈveri" },
      { term: "wonderful", ipa: "ˈwʌndəfəl" },
    ],
  },
  {
    unit: 57,
    section: "Words and grammar",
    title: "Words and prepositions",
    words: [
      { term: "afraid of", ipa: "əˈfreɪd əv" },
      { term: "apologise for", ipa: "əˈpɒlədʒaɪz fɔː" },
      { term: "ask for", ipa: "ɑːsk fɔː" },
      { term: "bad at", ipa: "bæd æt" },
      { term: "be used to", ipa: "biː juːst tə" },
      { term: "belong to", ipa: "bɪˈlɒŋ tə" },
      { term: "come to", ipa: "kʌm tə" },
      { term: "get used to get", ipa: "ˈjus tu" },
      { term: "good at", ipa: "gʊd æt" },
      { term: "happy about", ipa: "ˈhæpi əˈbaʊt" },
      { term: "interested in", ipa: "ˈɪntrəstɪd ɪn" },
      { term: "listen to", ipa: "ˈlɪsən tə" },
      { term: "look after", ipa: "lʊk ˈɑːftə" },
      { term: "look at", ipa: "lʊk æt" },
      { term: "look for", ipa: "lʊk fɔː" },
      { term: "look forward to", ipa: "lʊk ˈfɔːwəd tə" },
      { term: "pay for", ipa: "peɪ fɔː" },
      { term: "proud of", ipa: "praʊd ɒv" },
      { term: "thank for", ipa: "θæŋk fɔː" },
      { term: "think about", ipa: "θɪŋk əˈbaʊt" },
      { term: "used to", ipa: "ˈjus tu" },
      { term: "wait for", ipa: "weɪt fɔː" },
    ],
  },
  {
    unit: 58,
    section: "Words and grammar",
    title: "Prefixes",
    words: [
      { term: "ex-boyfriend eks", ipa: "ˈbɔɪfrend" },
      { term: "ex-wife eks", ipa: "waɪf" },
      { term: "half", ipa: "hɑːf" },
      { term: "half-hour", ipa: "ˈhɑːfˌaʊə" },
      { term: "half-price", ipa: "ˈhɑːfˈpraɪs" },
      { term: "impossible", ipa: "ɪmˈpɒsəbəl" },
      { term: "informal", ipa: "ɪnˈfɔːməl" },
      { term: "non-smoking", ipa: "nɒn ˈsməʊkɪŋ" },
      { term: "pre-heat", ipa: "priː hiːt" },
      { term: "pre-school", ipa: "priː skuːl" },
      { term: "redo", ipa: "ˈriːˌduː" },
      { term: "rewrite", ipa: "ˈriːraɪt" },
      { term: "unhappy", ipa: "ʌnˈhæpi" },
      { term: "unsafe", ipa: "ʌnˈseɪf" },
    ],
  },
  {
    unit: 59,
    section: "Words and grammar",
    title: "Suffixes",
    words: [
      { term: "beautiful", ipa: "ˈbjuːtɪfəl" },
      { term: "calculator", ipa: "ˈkælkjəleɪtə" },
      { term: "cooker", ipa: "ˈkʊkə" },
      { term: "endless", ipa: "ˈendləs" },
      { term: "happily", ipa: "ˈhæpɪli" },
      { term: "happiness", ipa: "ˈhæpɪnəs" },
      { term: "instructor", ipa: "ɪnˈstrʌktə" },
      { term: "quickly", ipa: "ˈkwɪkli" },
      { term: "sadness", ipa: "ˈsædnəs" },
      { term: "sandy", ipa: "ˈsændi" },
      { term: "sunny", ipa: "ˈsʌni" },
      { term: "swimmer", ipa: "ˈswɪmə" },
      { term: "useful", ipa: "ˈjuːsfəl" },
      { term: "useless", ipa: "ˈjuːsləs" },
      { term: "worker", ipa: "ˈwɜːkə" },
    ],
  },
  {
    unit: 60,
    section: "Words and grammar",
    title: "Words you may confuse",
    words: [
      { term: "afternoon", ipa: "ˌɑːftəˈnuːn" },
      { term: "borrow", ipa: "ˈbɒrəʊ" },
      { term: "check", ipa: "tʃek" },
      { term: "control", ipa: "kənˈtrəʊl" },
      { term: "cook", ipa: "kʊk" },
      { term: "cooker", ipa: "ˈkʊkə" },
      { term: "evening", ipa: "ˈiːvnɪŋ" },
      { term: "expect", ipa: "ɪkˈspekt" },
      { term: "fall", ipa: "fɔːl" },
      { term: "feel", ipa: "fiːl" },
      { term: "hope", ipa: "həʊp" },
      { term: "lend", ipa: "lend" },
      { term: "loose", ipa: "luːs" },
      { term: "lose", ipa: "luːz" },
      { term: "night", ipa: "naɪt" },
      { term: "quiet", ipa: "ˈkwaɪət" },
      { term: "quite", ipa: "kwaɪt" },
      { term: "wait for", ipa: "weɪt fɔː" },
    ],
  },
  ],
};
