import type { CollocationPack } from "./types";

/**
 * Tiếng Anh — kết hợp từ, cụm động từ, cấu tạo từ, giới từ.
 *
 * Bốn mảng này là phần "vocabulary" mà các sách ngữ pháp-từ vựng trình độ B1–C1
 * thường dạy song song với ngữ pháp. Cách chia theo bốn mảng là cách tổ chức
 * quen thuộc; câu ví dụ và lời giải thích ở đây do dự án tự viết.
 */
export const EN_COLLOCATIONS: CollocationPack = {
  code: "en",
  scale: "CEFR",
  levels: ["B1", "B2", "C1"],
  sets: [
    {
      id: "en.coll.make-do",
      title: "make hay do",
      kind: "collocation",
      level: "B1",
      note: "Cặp bị nhầm nhiều nhất. Không có quy tắc suy ra được — phải nhớ từng cụm.",
      items: [
        { sentence: "I'm afraid I ___ a mistake in the calculation.", answer: "made", note: "make a mistake. *do a mistake* là lỗi rất phổ biến của người học." },
        { sentence: "She ___ her homework before dinner every day.", answer: "does", note: "do homework, do housework, do the washing — việc phải làm thì dùng do." },
        { sentence: "Could you ___ me a favour and post this letter?", answer: "do", note: "do somebody a favour." },
        { sentence: "They ___ a lot of progress in the first month.", answer: "made", note: "make progress. Lưu ý progress không đếm được: *a progress* là sai." },
        { sentence: "He ___ his best but still didn't pass.", answer: "did", note: "do your best." },
        { sentence: "We need to ___ a decision by Friday.", answer: "make", note: "make a decision. Trang trọng hơn thì dùng reach a decision." },
        { sentence: "The new policy ___ no difference at all.", answer: "made", note: "make a difference." },
        { sentence: "I have to ___ some research before the meeting.", answer: "do", note: "do research, hoặc trang trọng hơn là conduct research. Không phải *make research*." },
        { sentence: "Try not to ___ so much noise — the baby is asleep.", answer: "make", note: "make noise, make a mess, make trouble." },
        { sentence: "She ___ a living as a translator.", answer: "makes", note: "make a living." },
      ],
    },
    {
      id: "en.coll.strong",
      title: "Tính từ đi với danh từ",
      kind: "collocation",
      level: "B2",
      note: "Cùng nghĩa 'mạnh' nhưng mỗi danh từ chọn một tính từ riêng. Dịch từng chữ từ tiếng Việt là sai ngay.",
      items: [
        { sentence: "There was ___ rain all weekend and the river burst its banks.", answer: "heavy", note: "heavy rain, heavy traffic, heavy smoker. Không phải *strong rain*." },
        { sentence: "He has a ___ interest in classical music.", answer: "keen", alt: ["strong"], note: "keen interest hoặc strong interest đều dùng được." },
        { sentence: "The evidence against him was ___.", answer: "overwhelming", note: "overwhelming evidence, overwhelming majority." },
        { sentence: "She made a ___ recovery after the operation.", answer: "full", alt: ["complete", "speedy"], note: "make a full recovery là cụm cố định." },
        { sentence: "That's a ___ point — I hadn't thought of it.", answer: "fair", alt: ["valid", "good"], note: "a fair point khi thừa nhận ý người khác có lý." },
        { sentence: "The film received ___ reviews from critics.", answer: "mixed", note: "mixed reviews nghĩa là khen chê lẫn lộn." },
        { sentence: "They have a ___ chance of winning the contract.", answer: "good", alt: ["slim", "fair"], note: "a good chance, a slim chance — chọn theo nghĩa muốn nói." },
        { sentence: "It was a ___ mistake that cost the company millions.", answer: "costly", alt: ["serious"], note: "a costly mistake." },
        { sentence: "He gave a ___ explanation of a difficult idea.", answer: "clear", alt: ["lucid"], note: "a clear explanation." },
        { sentence: "The company is under ___ pressure to cut costs.", answer: "intense", alt: ["mounting", "considerable"], note: "intense pressure, mounting pressure." },
      ],
    },
    {
      id: "en.coll.academic",
      title: "Kết hợp từ trong văn viết học thuật",
      kind: "collocation",
      level: "C1",
      note: "Những cụm hay gặp trong bài luận và bài báo. Dùng đúng là bài lên hẳn một bậc.",
      items: [
        { sentence: "The study ___ light on an issue that had long been ignored.", answer: "shed", alt: ["sheds"], note: "shed light on something — làm sáng tỏ." },
        { sentence: "These results ___ doubt on the earlier findings.", answer: "cast", note: "cast doubt on something." },
        { sentence: "The two variables are ___ linked.", answer: "closely", alt: ["strongly", "inextricably"], note: "closely linked, strongly correlated." },
        { sentence: "This raises an important ___ about data privacy.", answer: "question", alt: ["issue", "concern"], note: "raise a question, raise an issue, raise a concern." },
        { sentence: "The author ___ a compelling case for reform.", answer: "makes", alt: ["made", "puts"], note: "make a case for something, hoặc put forward a case." },
        { sentence: "We must ___ into account the small sample size.", answer: "take", note: "take something into account." },
        { sentence: "The findings are ___ with previous research.", answer: "consistent", note: "be consistent with — đi với giới từ with." },
        { sentence: "There is ___ evidence to support this claim.", answer: "little", alt: ["scant", "insufficient"], note: "little evidence, scant evidence." },
        { sentence: "The policy had far-___ consequences.", answer: "reaching", note: "far-reaching consequences — viết có gạch nối." },
        { sentence: "This ___ a significant departure from earlier practice.", answer: "marks", alt: ["represents"], note: "mark a departure from, represent a shift in." },
      ],
    },
    {
      id: "en.phrasal.everyday",
      title: "Cụm động từ đời thường",
      kind: "phrasal",
      level: "B1",
      note: "Cụm động từ là chỗ tiếng Anh nói khác hẳn tiếng Anh viết. Không biết thì nghe không hiểu.",
      items: [
        { sentence: "I need to ___ up early tomorrow for the flight.", answer: "get", note: "get up — thức dậy." },
        { sentence: "Could you ___ after the children while I'm out?", answer: "look", note: "look after — trông nom. Khác look for là tìm." },
        { sentence: "The meeting was ___ off because of the storm.", answer: "called", note: "call off — huỷ bỏ." },
        { sentence: "She ___ up smoking three years ago.", answer: "gave", note: "give up — từ bỏ." },
        { sentence: "We've ___ out of milk again.", answer: "run", note: "run out of something — hết sạch." },
        { sentence: "I ___ into an old classmate at the station.", answer: "ran", alt: ["bumped"], note: "run into hoặc bump into — tình cờ gặp." },
        { sentence: "Please ___ down your name and phone number.", answer: "write", alt: ["put", "jot"], note: "write down, put down, jot down." },
        { sentence: "The plane will ___ off in ten minutes.", answer: "take", note: "take off — cất cánh. Cũng có nghĩa cởi ra tuỳ ngữ cảnh." },
        { sentence: "He ___ up with a brilliant idea during lunch.", answer: "came", note: "come up with — nghĩ ra." },
        { sentence: "I can't ___ up with this noise any longer.", answer: "put", note: "put up with — chịu đựng." },
      ],
    },
    {
      id: "en.phrasal.advanced",
      title: "Cụm động từ nâng cao",
      kind: "phrasal",
      level: "C1",
      note: "Những cụm hay gặp trong báo chí và văn nói trang trọng.",
      items: [
        { sentence: "The scheme was ___ out over three years.", answer: "phased", note: "phase something out — loại bỏ dần." },
        { sentence: "Talks between the two sides have ___ down.", answer: "broken", note: "break down — đổ vỡ, thất bại." },
        { sentence: "It all ___ down to how much money is available.", answer: "boils", alt: ["comes"], note: "boil down to hoặc come down to — quy về, rốt cuộc là." },
        { sentence: "The government has ___ back on public spending.", answer: "cut", note: "cut back on — cắt giảm." },
        { sentence: "She ___ up for her colleague at the meeting.", answer: "stood", note: "stand up for — bênh vực." },
        { sentence: "The new rules will ___ in next January.", answer: "come", note: "come in — bắt đầu có hiệu lực. Cũng nói come into force." },
        { sentence: "We should ___ ahead with the original plan.", answer: "go", note: "go ahead with — tiến hành." },
        { sentence: "The company ___ up to its promise in the end.", answer: "lived", note: "live up to — đáp ứng được kỳ vọng." },
        { sentence: "Nobody could ___ for his whereabouts that night.", answer: "account", note: "account for — giải thích, lý giải." },
        { sentence: "The issue keeps ___ up in every discussion.", answer: "cropping", alt: ["coming"], note: "crop up — nảy ra, xuất hiện bất ngờ." },
      ],
    },
    {
      id: "en.wordform.noun-adj",
      title: "Cấu tạo từ — danh từ và tính từ",
      kind: "wordform",
      level: "B2",
      note: "Cho từ gốc, đổi sang đúng từ loại mà câu cần. Đây là dạng bài kinh điển của sách ngữ pháp-từ vựng.",
      items: [
        { sentence: "His ___ to the project was enormous. (CONTRIBUTE)", answer: "contribution", note: "contribute → contribution." },
        { sentence: "The results were highly ___. (SIGNIFY)", answer: "significant", note: "signify → significant. Danh từ là significance." },
        { sentence: "There has been a steady ___ in crime. (REDUCE)", answer: "reduction", note: "reduce → reduction." },
        { sentence: "She spoke with great ___. (CONFIDENT)", answer: "confidence", note: "confident → confidence." },
        { sentence: "The plan proved ___ in practice. (SUCCESS)", answer: "successful", note: "success → successful → successfully." },
        { sentence: "We need a more ___ approach. (SYSTEM)", answer: "systematic", note: "system → systematic." },
        { sentence: "His ___ of the situation was wrong. (ANALYSE)", answer: "analysis", note: "analyse → analysis. Số nhiều là analyses." },
        { sentence: "The building is under ___. (CONSTRUCT)", answer: "construction", note: "construct → construction." },
        { sentence: "It is ___ that he will accept. (LIKELY)", answer: "unlikely", note: "Câu cần nghĩa phủ định: likely → unlikely." },
        { sentence: "The two versions are almost ___. (DISTINGUISH)", answer: "indistinguishable", note: "distinguish → distinguishable → indistinguishable." },
      ],
    },
    {
      id: "en.prep.verb",
      title: "Giới từ sau động từ",
      kind: "preposition",
      level: "B1",
      note: "Không suy luận được, phải nhớ theo cặp. Sai giới từ là lỗi ngữ pháp rõ ràng.",
      items: [
        { sentence: "It depends ___ what time we finish.", answer: "on", note: "depend on. Không bao giờ *depend of*." },
        { sentence: "She apologised ___ being late.", answer: "for", note: "apologise for something, apologise to somebody." },
        { sentence: "He was accused ___ stealing the money.", answer: "of", note: "accuse somebody of something." },
        { sentence: "I'm not very good ___ remembering names.", answer: "at", note: "good at, bad at, brilliant at." },
        { sentence: "They congratulated her ___ passing the exam.", answer: "on", note: "congratulate somebody on something." },
        { sentence: "This year's figures are similar ___ last year's.", answer: "to", note: "similar to, different from." },
        { sentence: "He insisted ___ paying for dinner.", answer: "on", note: "insist on doing something." },
        { sentence: "The result was due ___ a simple error.", answer: "to", note: "due to, owing to." },
        { sentence: "She succeeded ___ convincing the committee.", answer: "in", note: "succeed in doing something." },
        { sentence: "I object ___ being treated like this.", answer: "to", note: "object to + V-ing. Không phải *object to do*." },
      ],
    },
    {
      id: "en.prep.adj-noun",
      title: "Giới từ sau tính từ và danh từ",
      kind: "preposition",
      level: "B2",
      note: "Chỗ hay sai trong bài viết, và giám khảo bắt rất nhanh.",
      items: [
        { sentence: "There is growing concern ___ the environment.", answer: "about", alt: ["over", "for"], note: "concern about, concern over." },
        { sentence: "He is responsible ___ the whole department.", answer: "for", note: "responsible for something, responsible to somebody." },
        { sentence: "She's completely unaware ___ the problem.", answer: "of", note: "aware of, unaware of." },
        { sentence: "The demand ___ housing continues to rise.", answer: "for", note: "demand for something." },
        { sentence: "There's no solution ___ this problem yet.", answer: "to", note: "a solution to, an answer to. Không phải *solution of*." },
        { sentence: "He's very keen ___ football.", answer: "on", note: "keen on something, keen to do something." },
        { sentence: "The reason ___ the delay was never explained.", answer: "for", note: "the reason for something." },
        { sentence: "She has a real talent ___ languages.", answer: "for", note: "a talent for, a gift for." },
        { sentence: "The effect ___ young people has been severe.", answer: "on", note: "an effect on, an impact on. Nhưng affect thì không có giới từ." },
        { sentence: "I'm not familiar ___ that software.", answer: "with", note: "familiar with something." },
      ],
    },
  ],
  references: [
    "Cách chia bốn mảng (kết hợp từ, cụm động từ, cấu tạo từ, giới từ) theo lối các sách ngữ pháp-từ vựng B1–C1 thường tổ chức",
    "Thang CEFR để xếp độ khó",
    "Câu ví dụ và lời giải thích do dự án tự viết, không chép từ sách nào",
  ],
};
