import type { CollocationPack } from "./types";

/**
 * Tiếng Anh — kết hợp từ, cụm động từ, cấu tạo từ, giới từ.
 *
 * Bốn mảng này là phần "vocabulary" mà các sách ngữ pháp-từ vựng trình độ B1–C1
 * thường dạy song song với ngữ pháp. Cách chia theo bốn mảng là cách tổ chức
 * quen thuộc; câu ví dụ và lời giải thích ở đây do dự án tự viết.
 */
export const EN_COLLOCATIONS: CollocationPack = {
  code: "en",
  scale: "CEFR",
  levels: ["B1", "B2", "C1"],
  sets: [
    {
      id: "en.coll.make-do",
      title: "make hay do",
      kind: "collocation",
      level: "B1",
      note: "Cặp bị nhầm nhiều nhất. Không có quy tắc suy ra được — phải nhớ từng cụm.",
      items: [
        { sentence: "I'm afraid I ___ a mistake in the calculation.", answer: "made", note: "make a mistake. *do a mistake* là lỗi rất phổ biến của người học." },
        { sentence: "She ___ her homework before dinner every day.", answer: "does", note: "do homework, do housework, do the washing — việc phải làm thì dùng do." },
        { sentence: "Could you ___ me a favour and post this letter?", answer: "do", note: "do somebody a favour." },
        { sentence: "They ___ a lot of progress in the first month.", answer: "made", note: "make progress. Lưu ý progress không đếm được: *a progress* là sai." },
        { sentence: "He ___ his best but still didn't pass.", answer: "did", note: "do your best." },
        { sentence: "We need to ___ a decision by Friday.", answer: "make", note: "make a decision. Trang trọng hơn thì dùng reach a decision." },
        { sentence: "The new policy ___ no difference at all.", answer: "made", note: "make a difference." },
        { sentence: "I have to ___ some research before the meeting.", answer: "do", note: "do research, hoặc trang trọng hơn là conduct research. Không phải *make research*." },
        { sentence: "Try not to ___ so much noise — the baby is asleep.", answer: "make", note: "make noise, make a mess, make trouble." },
        { sentence: "She ___ a living as a translator.", answer: "makes", note: "make a living." },
      ],
    },
    {
      id: "en.coll.strong",
      title: "Tính từ đi với danh từ",
      kind: "collocation",
      level: "B2",
      note: "Cùng nghĩa 'mạnh' nhưng mỗi danh từ chọn một tính từ riêng. Dịch từng chữ từ tiếng Việt là sai ngay.",
      items: [
        { sentence: "There was ___ rain all weekend and the river burst its banks.", answer: "heavy", note: "heavy rain, heavy traffic, heavy smoker. Không phải *strong rain*." },
        { sentence: "He has a ___ interest in classical music.", answer: "keen", alt: ["strong"], note: "keen interest hoặc strong interest đều dùng được." },
        { sentence: "The evidence against him was ___.", answer: "overwhelming", note: "overwhelming evidence, overwhelming majority." },
        { sentence: "She made a ___ recovery after the operation.", answer: "full", alt: ["complete", "speedy"], note: "make a full recovery là cụm cố định." },
        { sentence: "That's a ___ point — I hadn't thought of it.", answer: "fair", alt: ["valid", "good"], note: "a fair point khi thừa nhận ý người khác có lý." },
        { sentence: "The film received ___ reviews from critics.", answer: "mixed", note: "mixed reviews nghĩa là khen chê lẫn lộn." },
        { sentence: "They have a ___ chance of winning the contract.", answer: "good", alt: ["slim", "fair"], note: "a good chance, a slim chance — chọn theo nghĩa muốn nói." },
        { sentence: "It was a ___ mistake that cost the company millions.", answer: "costly", alt: ["serious"], note: "a costly mistake." },
        { sentence: "He gave a ___ explanation of a difficult idea.", answer: "clear", alt: ["lucid"], note: "a clear explanation." },
        { sentence: "The company is under ___ pressure to cut costs.", answer: "intense", alt: ["mounting", "considerable"], note: "intense pressure, mounting pressure." },
      ],
    },
    {
      id: "en.coll.academic",
      title: "Kết hợp từ trong văn viết học thuật",
      kind: "collocation",
      level: "C1",
      note: "Những cụm hay gặp trong bài luận và bài báo. Dùng đúng là bài lên hẳn một bậc.",
      items: [
        { sentence: "The study ___ light on an issue that had long been ignored.", answer: "shed", alt: ["sheds"], note: "shed light on something — làm sáng tỏ." },
        { sentence: "These results ___ doubt on the earlier findings.", answer: "cast", note: "cast doubt on something." },
        { sentence: "The two variables are ___ linked.", answer: "closely", alt: ["strongly", "inextricably"], note: "closely linked, strongly correlated." },
        { sentence: "This raises an important ___ about data privacy.", answer: "question", alt: ["issue", "concern"], note: "raise a question, raise an issue, raise a concern." },
        { sentence: "The author ___ a compelling case for reform.", answer: "makes", alt: ["made", "puts"], note: "make a case for something, hoặc put forward a case." },
        { sentence: "We must ___ into account the small sample size.", answer: "take", note: "take something into account." },
        { sentence: "The findings are ___ with previous research.", answer: "consistent", note: "be consistent with — đi với giới từ with." },
        { sentence: "There is ___ evidence to support this claim.", answer: "little", alt: ["scant", "insufficient"], note: "little evidence, scant evidence." },
        { sentence: "The policy had far-___ consequences.", answer: "reaching", note: "far-reaching consequences — viết có gạch nối." },
        { sentence: "This ___ a significant departure from earlier practice.", answer: "marks", alt: ["represents"], note: "mark a departure from, represent a shift in." },
      ],
    },
    {
      id: "en.phrasal.everyday",
      title: "Cụm động từ đời thường",
      kind: "phrasal",
      level: "B1",
      note: "Cụm động từ là chỗ tiếng Anh nói khác hẳn tiếng Anh viết. Không biết thì nghe không hiểu.",
      items: [
        { sentence: "I need to ___ up early tomorrow for the flight.", answer: "get", note: "get up — thức dậy." },
        { sentence: "Could you ___ after the children while I'm out?", answer: "look", note: "look after — trông nom. Khác look for là tìm." },
        { sentence: "The meeting was ___ off because of the storm.", answer: "called", note: "call off — huỷ bỏ." },
        { sentence: "She ___ up smoking three years ago.", answer: "gave", note: "give up — từ bỏ." },
        { sentence: "We've ___ out of milk again.", answer: "run", note: "run out of something — hết sạch." },
        { sentence: "I ___ into an old classmate at the station.", answer: "ran", alt: ["bumped"], note: "run into hoặc bump into — tình cờ gặp." },
        { sentence: "Please ___ down your name and phone number.", answer: "write", alt: ["put", "jot"], note: "write down, put down, jot down." },
        { sentence: "The plane will ___ off in ten minutes.", answer: "take", note: "take off — cất cánh. Cũng có nghĩa cởi ra tuỳ ngữ cảnh." },
        { sentence: "He ___ up with a brilliant idea during lunch.", answer: "came", note: "come up with — nghĩ ra." },
        { sentence: "I can't ___ up with this noise any longer.", answer: "put", note: "put up with — chịu đựng." },
      ],
    },
    {
      id: "en.phrasal.advanced",
      title: "Cụm động từ nâng cao",
      kind: "phrasal",
      level: "C1",
      note: "Những cụm hay gặp trong báo chí và văn nói trang trọng.",
      items: [
        { sentence: "The scheme was ___ out over three years.", answer: "phased", note: "phase something out — loại bỏ dần." },
        { sentence: "Talks between the two sides have ___ down.", answer: "broken", note: "break down — đổ vỡ, thất bại." },
        { sentence: "It all ___ down to how much money is available.", answer: "boils", alt: ["comes"], note: "boil down to hoặc come down to — quy về, rốt cuộc là." },
        { sentence: "The government has ___ back on public spending.", answer: "cut", note: "cut back on — cắt giảm." },
        { sentence: "She ___ up for her colleague at the meeting.", answer: "stood", note: "stand up for — bênh vực." },
        { sentence: "The new rules will ___ in next January.", answer: "come", note: "come in — bắt đầu có hiệu lực. Cũng nói come into force." },
        { sentence: "We should ___ ahead with the original plan.", answer: "go", note: "go ahead with — tiến hành." },
        { sentence: "The company ___ up to its promise in the end.", answer: "lived", note: "live up to — đáp ứng được kỳ vọng." },
        { sentence: "Nobody could ___ for his whereabouts that night.", answer: "account", note: "account for — giải thích, lý giải." },
        { sentence: "The issue keeps ___ up in every discussion.", answer: "cropping", alt: ["coming"], note: "crop up — nảy ra, xuất hiện bất ngờ." },
      ],
    },
    {
      id: "en.wordform.noun-adj",
      title: "Cấu tạo từ — danh từ và tính từ",
      kind: "wordform",
      level: "B2",
      note: "Cho từ gốc, đổi sang đúng từ loại mà câu cần. Đây là dạng bài kinh điển của sách ngữ pháp-từ vựng.",
      items: [
        { sentence: "His ___ to the project was enormous. (CONTRIBUTE)", answer: "contribution", note: "contribute → contribution." },
        { sentence: "The results were highly ___. (SIGNIFY)", answer: "significant", note: "signify → significant. Danh từ là significance." },
        { sentence: "There has been a steady ___ in crime. (REDUCE)", answer: "reduction", note: "reduce → reduction." },
        { sentence: "She spoke with great ___. (CONFIDENT)", answer: "confidence", note: "confident → confidence." },
        { sentence: "The plan proved ___ in practice. (SUCCESS)", answer: "successful", note: "success → successful → successfully." },
        { sentence: "We need a more ___ approach. (SYSTEM)", answer: "systematic", note: "system → systematic." },
        { sentence: "His ___ of the situation was wrong. (ANALYSE)", answer: "analysis", note: "analyse → analysis. Số nhiều là analyses." },
        { sentence: "The building is under ___. (CONSTRUCT)", answer: "construction", note: "construct → construction." },
        { sentence: "It is ___ that he will accept. (LIKELY)", answer: "unlikely", note: "Câu cần nghĩa phủ định: likely → unlikely." },
        { sentence: "The two versions are almost ___. (DISTINGUISH)", answer: "indistinguishable", note: "distinguish → distinguishable → indistinguishable." },
      ],
    },
    {
      id: "en.prep.verb",
      title: "Giới từ sau động từ",
      kind: "preposition",
      level: "B1",
      note: "Không suy luận được, phải nhớ theo cặp. Sai giới từ là lỗi ngữ pháp rõ ràng.",
      items: [
        { sentence: "It depends ___ what time we finish.", answer: "on", note: "depend on. Không bao giờ *depend of*." },
        { sentence: "She apologised ___ being late.", answer: "for", note: "apologise for something, apologise to somebody." },
        { sentence: "He was accused ___ stealing the money.", answer: "of", note: "accuse somebody of something." },
        { sentence: "I'm not very good ___ remembering names.", answer: "at", note: "good at, bad at, brilliant at." },
        { sentence: "They congratulated her ___ passing the exam.", answer: "on", note: "congratulate somebody on something." },
        { sentence: "This year's figures are similar ___ last year's.", answer: "to", note: "similar to, different from." },
        { sentence: "He insisted ___ paying for dinner.", answer: "on", note: "insist on doing something." },
        { sentence: "The result was due ___ a simple error.", answer: "to", note: "due to, owing to." },
        { sentence: "She succeeded ___ convincing the committee.", answer: "in", note: "succeed in doing something." },
        { sentence: "I object ___ being treated like this.", answer: "to", note: "object to + V-ing. Không phải *object to do*." },
      ],
    },
    {
      id: "en.prep.adj-noun",
      title: "Giới từ sau tính từ và danh từ",
      kind: "preposition",
      level: "B2",
      note: "Chỗ hay sai trong bài viết, và giám khảo bắt rất nhanh.",
      items: [
        { sentence: "There is growing concern ___ the environment.", answer: "about", alt: ["over", "for"], note: "concern about, concern over." },
        { sentence: "He is responsible ___ the whole department.", answer: "for", note: "responsible for something, responsible to somebody." },
        { sentence: "She's completely unaware ___ the problem.", answer: "of", note: "aware of, unaware of." },
        { sentence: "The demand ___ housing continues to rise.", answer: "for", note: "demand for something." },
        { sentence: "There's no solution ___ this problem yet.", answer: "to", note: "a solution to, an answer to. Không phải *solution of*." },
        { sentence: "He's very keen ___ football.", answer: "on", note: "keen on something, keen to do something." },
        { sentence: "The reason ___ the delay was never explained.", answer: "for", note: "the reason for something." },
        { sentence: "She has a real talent ___ languages.", answer: "for", note: "a talent for, a gift for." },
        { sentence: "The effect ___ young people has been severe.", answer: "on", note: "an effect on, an impact on. Nhưng affect thì không có giới từ." },
        { sentence: "I'm not familiar ___ that software.", answer: "with", note: "familiar with something." },
      ],
    },
    {
      id: "en.idiom.everyday",
      title: "Thành ngữ đời thường",
      kind: "idiom",
      level: "B2",
      note: "Nghĩa của cả cụm không bằng tổng nghĩa từng chữ. Không biết thì nghe xong vẫn không hiểu.",
      items: [
        { sentence: "I'm afraid the project is ___ the rocks — we may have to start again.", answer: "on", note: "be on the rocks — đang lung lay, sắp đổ vỡ. Dùng cho cả dự án lẫn quan hệ." },
        { sentence: "Let's play it ___ ear and decide when we get there.", answer: "by", note: "play it by ear — tuỳ cơ ứng biến, không lên kế hoạch trước." },
        { sentence: "He let the ___ out of the bag about the surprise party.", answer: "cat", note: "let the cat out of the bag — lỡ miệng làm lộ bí mật." },
        { sentence: "Learning the whole syllabus in a week is a tall ___.", answer: "order", note: "a tall order — một đòi hỏi quá sức." },
        { sentence: "We'll have to cross that ___ when we come to it.", answer: "bridge", note: "cross that bridge when you come to it — tới đâu tính đó." },
        { sentence: "She was ___ over heels about the new job.", answer: "head", note: "head over heels — mê mẩn, phấn khích tột độ." },
        { sentence: "That explanation doesn't ___ water, I'm afraid.", answer: "hold", note: "not hold water — lập luận không đứng vững." },
        { sentence: "He's been ___ the fence about whether to accept.", answer: "on", note: "sit on the fence — chưa ngả về bên nào." },
        { sentence: "The new rules are a blessing in ___.", answer: "disguise", note: "a blessing in disguise — trong rủi có may." },
        { sentence: "Getting that visa was a piece of ___.", answer: "cake", note: "a piece of cake — dễ như trở bàn tay." },
      ],
    },
    {
      id: "en.idiom.written",
      title: "Thành ngữ dùng được trong bài viết",
      kind: "idiom",
      level: "C1",
      note: "Phần lớn thành ngữ quá thân mật cho bài luận. Đây là những cụm vẫn dùng được ở văn trang trọng.",
      items: [
        { sentence: "The two problems go ___ in hand and cannot be solved separately.", answer: "hand", note: "go hand in hand — đi đôi với nhau. Dùng được trong bài luận." },
        { sentence: "This policy is a double-___ sword: it helps some and harms others.", answer: "edged", note: "a double-edged sword — con dao hai lưỡi." },
        { sentence: "Rising costs are only the ___ of the iceberg.", answer: "tip", note: "the tip of the iceberg — mới là phần nổi." },
        { sentence: "We should not throw the baby out with the ___.", answer: "bathwater", note: "throw the baby out with the bathwater — bỏ cả cái tốt khi loại cái xấu." },
        { sentence: "Education is arguably the ___ of long-term development.", answer: "cornerstone", alt: ["bedrock", "foundation"], note: "the cornerstone of — nền tảng của. Rất hợp bài luận." },
        { sentence: "These figures paint a rather bleak ___ of the situation.", answer: "picture", note: "paint a picture of — phác nên một bức tranh về." },
        { sentence: "The government is walking a ___ between growth and inflation.", answer: "tightrope", note: "walk a tightrope — đi trên dây, cân bằng hai thứ đối nghịch." },
        { sentence: "There is no one-size-fits-___ answer to this question.", answer: "all", note: "one-size-fits-all — giải pháp chung cho mọi trường hợp." },
        { sentence: "In the long ___, the benefits outweigh the costs.", answer: "run", note: "in the long run — về lâu dài." },
        { sentence: "This argument misses the ___ entirely.", answer: "point", note: "miss the point — hiểu lệch trọng tâm." },
      ],
    },
    {
      id: "en.topic.health",
      title: "Chủ đề Sức khoẻ",
      kind: "topic",
      level: "B2",
      note: "Từ vựng theo chủ đề, kèm cụm đi với nó. Sức khoẻ là chủ đề ra rất thường trong bài thi.",
      items: [
        { sentence: "Regular exercise can significantly ___ the risk of heart disease.", answer: "reduce", alt: ["lower", "cut"], note: "reduce/lower the risk of — cụm chuẩn khi nói về phòng bệnh." },
        { sentence: "Many countries face a shortage of trained medical ___.", answer: "staff", alt: ["personnel"], note: "medical staff, healthcare personnel." },
        { sentence: "She was ___ with diabetes two years ago.", answer: "diagnosed", note: "be diagnosed with + bệnh." },
        { sentence: "A ___ diet includes plenty of fruit and vegetables.", answer: "balanced", note: "a balanced diet — chế độ ăn cân bằng. Không phải *equal diet*." },
        { sentence: "Smoking remains a leading ___ of preventable death.", answer: "cause", note: "a leading cause of — nguyên nhân hàng đầu." },
        { sentence: "The hospital is struggling to cope with the ___ of patients.", answer: "influx", alt: ["number"], note: "an influx of — lượng đổ vào đột ngột." },
        { sentence: "Mental health has long been ___ in public policy.", answer: "overlooked", alt: ["neglected"], note: "be overlooked, be neglected — bị bỏ qua." },
        { sentence: "Access to clean water has a direct ___ on public health.", answer: "impact", alt: ["bearing", "effect"], note: "have an impact on. Nhớ giới từ ON." },
        { sentence: "Vaccination programmes have ___ out several diseases.", answer: "wiped", alt: ["stamped"], note: "wipe out a disease — xoá sổ một căn bệnh." },
        { sentence: "Patients should be encouraged to ___ a healthier lifestyle.", answer: "adopt", alt: ["lead"], note: "adopt a lifestyle, lead a healthy life." },
      ],
    },
    {
      id: "en.topic.work",
      title: "Chủ đề Công việc và sự nghiệp",
      kind: "topic",
      level: "B2",
      note: "Cụm từ dùng khi nói và viết về việc làm, thăng tiến, môi trường làm việc.",
      items: [
        { sentence: "She was ___ to head of department last year.", answer: "promoted", note: "be promoted to + chức vụ." },
        { sentence: "Many graduates struggle to gain relevant work ___.", answer: "experience", note: "gain work experience. Experience ở nghĩa này KHÔNG đếm được." },
        { sentence: "The company offers a competitive ___ package.", answer: "benefits", alt: ["salary", "pay"], note: "a benefits package, a competitive salary." },
        { sentence: "He decided to ___ a career in medicine.", answer: "pursue", note: "pursue a career — theo đuổi một nghề." },
        { sentence: "Flexible hours help employees strike a better work-life ___.", answer: "balance", note: "strike a work-life balance." },
        { sentence: "Hundreds were made ___ when the factory closed.", answer: "redundant", note: "be made redundant — bị cho thôi việc do cắt giảm, khác be fired là bị đuổi vì lỗi." },
        { sentence: "The role involves ___ a small team of designers.", answer: "managing", alt: ["leading"], note: "manage/lead a team." },
        { sentence: "Automation is expected to ___ many routine jobs.", answer: "replace", alt: ["displace"], note: "replace jobs, displace workers." },
        { sentence: "She handed in her ___ after ten years at the firm.", answer: "resignation", alt: ["notice"], note: "hand in your resignation, hand in your notice." },
        { sentence: "Staff ___ is high in industries with poor pay.", answer: "turnover", note: "staff turnover — tỷ lệ nhân viên nghỉ việc." },
      ],
    },
    {
      id: "en.topic.environment",
      title: "Chủ đề Môi trường",
      kind: "topic",
      level: "B2",
      note: "Chủ đề ra nhiều nhất trong bài viết Task 2. Thiếu vốn từ ở đây là mất điểm ngay.",
      items: [
        { sentence: "Factories continue to ___ harmful gases into the atmosphere.", answer: "emit", alt: ["release", "pump"], note: "emit gases, release emissions." },
        { sentence: "We urgently need to cut our carbon ___.", answer: "footprint", note: "carbon footprint — dấu chân các-bon." },
        { sentence: "Many species are on the ___ of extinction.", answer: "brink", alt: ["verge"], note: "on the brink/verge of extinction." },
        { sentence: "Governments should invest in ___ energy sources.", answer: "renewable", note: "renewable energy — năng lượng tái tạo." },
        { sentence: "Plastic waste poses a serious ___ to marine life.", answer: "threat", alt: ["danger", "risk"], note: "pose a threat to — gây ra mối đe doạ cho." },
        { sentence: "Deforestation has ___ soil erosion in the region.", answer: "accelerated", alt: ["worsened", "aggravated"], note: "accelerate, worsen, aggravate a problem." },
        { sentence: "Recycling schemes help ___ natural resources.", answer: "conserve", alt: ["preserve"], note: "conserve resources — bảo tồn tài nguyên." },
        { sentence: "The city has taken ___ to reduce air pollution.", answer: "steps", alt: ["measures", "action"], note: "take steps, take measures, take action." },
        { sentence: "Rising sea levels are a direct ___ of global warming.", answer: "consequence", alt: ["result"], note: "a consequence of, a result of." },
        { sentence: "Sustainable farming can ___ the damage already done.", answer: "offset", alt: ["mitigate", "reverse"], note: "offset damage, mitigate harm." },
      ],
    },
    {
      id: "en.topic.education",
      title: "Chủ đề Giáo dục",
      kind: "topic",
      level: "B2",
      note: "Chủ đề ra thường xuyên ở cả bài viết lẫn bài nói.",
      items: [
        { sentence: "She ___ a scholarship to study abroad.", answer: "won", alt: ["received", "was awarded"], note: "win a scholarship, be awarded a scholarship." },
        { sentence: "The course ___ both theory and practical work.", answer: "covers", alt: ["combines", "includes"], note: "a course covers topics." },
        { sentence: "Too much emphasis is placed on ___ exams.", answer: "passing", note: "place emphasis on something." },
        { sentence: "Students are expected to ___ their assignments by Friday.", answer: "submit", alt: ["hand in"], note: "submit an assignment, hand in work." },
        { sentence: "He ___ from university with first-class honours.", answer: "graduated", note: "graduate FROM a university, graduate IN a subject." },
        { sentence: "Small class ___ allow teachers to give individual attention.", answer: "sizes", note: "class size — sĩ số lớp." },
        { sentence: "The school has a strong ___ record in science.", answer: "track", note: "a track record — bề dày thành tích." },
        { sentence: "Online learning has made education more ___ to rural students.", answer: "accessible", note: "accessible TO somebody." },
        { sentence: "She ___ in economics before switching to law.", answer: "majored", alt: ["specialised"], note: "major in a subject (Mỹ), specialise in (Anh)." },
        { sentence: "Compulsory education ___ children from six to sixteen.", answer: "covers", alt: ["includes"], note: "Lưu ý compulsory chứ không phải *obligatory* khi nói về giáo dục bắt buộc." },
      ],
    },
    {
      id: "en.academic.reporting",
      title: "Từ học thuật — nêu và dẫn nghiên cứu",
      kind: "academic",
      level: "C1",
      note: "Động từ dùng khi thuật lại điều một nghiên cứu nói. Mỗi từ mang một mức chắc chắn khác nhau.",
      items: [
        { sentence: "The data ___ that the trend is slowing.", answer: "suggest", alt: ["indicate", "imply"], note: "suggest — mức chắc chắn vừa phải. Lưu ý data là số nhiều trong văn học thuật." },
        { sentence: "The author ___ that existing models are inadequate.", answer: "argues", alt: ["contends", "maintains"], note: "argue, contend, maintain — nêu một luận điểm có bảo vệ." },
        { sentence: "Earlier work ___ a link between the two factors.", answer: "established", alt: ["identified", "found"], note: "establish a link — mức chắc chắn cao hơn suggest." },
        { sentence: "These findings ___ with what we observed.", answer: "correspond", alt: ["accord"], note: "correspond with, accord with, be in line with." },
        { sentence: "The study ___ to explain why the effect disappears.", answer: "fails", note: "fail to explain — cách nói phê bình lịch sự." },
        { sentence: "The results should be ___ with caution.", answer: "interpreted", alt: ["treated", "viewed"], note: "interpret results with caution." },
        { sentence: "Further research is ___ to confirm these findings.", answer: "needed", alt: ["required", "warranted"], note: "further research is warranted — cách viết trang trọng." },
        { sentence: "The sample was not ___ of the wider population.", answer: "representative", note: "be representative of." },
        { sentence: "This ___ from the approach taken in earlier studies.", answer: "differs", alt: ["departs"], note: "differ from, depart from." },
        { sentence: "The two variables are ___ correlated.", answer: "positively", alt: ["strongly", "negatively"], note: "positively/negatively correlated." },
      ],
    },
    {
      id: "en.academic.process",
      title: "Từ học thuật — quá trình và thay đổi",
      kind: "academic",
      level: "C1",
      note: "Động từ và danh từ trừu tượng hay gặp trong bài luận và bài báo khoa học.",
      items: [
        { sentence: "Attitudes have ___ considerably over the past decade.", answer: "shifted", alt: ["changed", "evolved"], note: "attitudes shift, views evolve." },
        { sentence: "The policy was ___ in response to public pressure.", answer: "amended", alt: ["revised", "modified"], note: "amend a policy — sửa đổi." },
        { sentence: "Economic growth has ___ off since 2020.", answer: "levelled", alt: ["tailed"], note: "level off — chững lại; tail off — giảm dần." },
        { sentence: "The reforms were implemented in ___ rather than all at once.", answer: "stages", alt: ["phases"], note: "in stages, in phases — theo từng giai đoạn." },
        { sentence: "These factors ___ to the overall decline.", answer: "contributed", note: "contribute TO something." },
        { sentence: "The effect ___ over time rather than disappearing.", answer: "persists", alt: ["endures"], note: "an effect persists — kéo dài dai dẳng." },
        { sentence: "Technology has fundamentally ___ how we communicate.", answer: "transformed", alt: ["altered", "reshaped"], note: "transform, reshape — đổi về căn bản." },
        { sentence: "The benefits are likely to ___ the costs in the long run.", answer: "outweigh", note: "outweigh — lớn hơn về giá trị. Rất hay dùng trong Task 2." },
        { sentence: "Several factors ___ to explain the discrepancy.", answer: "combine", alt: ["interact"], note: "factors combine to produce an effect." },
        { sentence: "The trend shows no sign of ___ down.", answer: "slowing", note: "show no sign of + V-ing." },
      ],
    },
  ],
  references: [
    "Cách chia bốn mảng (kết hợp từ, cụm động từ, cấu tạo từ, giới từ) theo lối các sách ngữ pháp-từ vựng B1–C1 thường tổ chức",
    "Thang CEFR để xếp độ khó",
    "Câu ví dụ và lời giải thích do dự án tự viết, không chép từ sách nào",
  ],
};
