import type { Book } from "./types";

/**
 * Destination B1 — Grammar and Vocabulary (Macmillan).
 *
 * Bản PDF người dùng đưa là BẢN QUÉT, không có lớp chữ, ảnh lại mã hoá JBIG2
 * nên pdf.js không giải được. Cấu trúc và danh sách từ lấy bằng cách tải PDF
 * lên Gemini Files API rồi cho nó đọc: mục lục cho ra 42 unit và 14 bài ôn,
 * rồi từng nhóm unit từ vựng cho ra danh sách mục từ.
 *
 * CHỈ LẤY DANH SÁCH TỪ. Từ vựng là dữ kiện về tiếng Anh — không ai sở hữu chữ
 * "champion". KHÔNG chép định nghĩa, câu ví dụ, đề bài hay lời giải thích của
 * sách; phần đó có bản quyền và là thứ khiến cuốn sách đáng mua.
 *
 * Sách không in phiên âm cho phần từ vựng nên `ipa` để trống; tra một từ trong
 * màn unit thì AI trả về cách đọc.
 *
 * 28 unit ngữ pháp CHƯA có nội dung: ngữ pháp là quy tắc, và dự án đã có khung
 * 175 điểm ngữ pháp riêng — nối hai thứ đó lại hợp lý hơn là chép lại unit.
 *
 * 1118 mục từ trên 14 unit từ vựng.
 */
export const DESTINATION_B1: Book = {
  id: "destination-b1",
  title: "Destination B1 Grammar and Vocabulary",
  langCode: "en",
  level: "B1",
  note: "42 unit ngữ pháp và từ vựng, 14 bài ôn, theo đúng thứ tự của sách.",
  provenance:
    "Cấu trúc unit và danh sách từ đọc từ chính cuốn sách. Nghĩa, ví dụ và phần dạy do ứng dụng soạn — không chép nội dung sách. Unit ngữ pháp chưa có nội dung.",
  steps: [
    { step: 1, label: "1", kind: "grammar", title: "Present simple, present continuous, stative verbs" },
    { step: 2, label: "2", kind: "grammar", title: "Past simple, past continuous, used to" },
    { step: 3, label: "3", kind: "vocabulary", title: "Fun and games",
      words: [
        { term: "beat", ipa: "" },
        { term: "board game", ipa: "" },
        { term: "captain", ipa: "" },
        { term: "challenge", ipa: "" },
        { term: "champion", ipa: "" },
        { term: "cheat", ipa: "" },
        { term: "classical music", ipa: "" },
        { term: "club", ipa: "" },
        { term: "coach", ipa: "" },
        { term: "competition", ipa: "" },
        { term: "concert", ipa: "" },
        { term: "defeat", ipa: "" },
        { term: "entertaining", ipa: "" },
        { term: "folk music", ipa: "" },
        { term: "group", ipa: "" },
        { term: "gym", ipa: "" },
        { term: "have fun", ipa: "" },
        { term: "interest", ipa: "" },
        { term: "member", ipa: "" },
        { term: "opponent", ipa: "" },
        { term: "organise", ipa: "" },
        { term: "pleasure", ipa: "" },
        { term: "referee", ipa: "" },
        { term: "rhythm", ipa: "" },
        { term: "risk", ipa: "" },
        { term: "score", ipa: "" },
        { term: "support", ipa: "" },
        { term: "team", ipa: "" },
        { term: "train", ipa: "" },
        { term: "video game", ipa: "" },
        { term: "carry on", ipa: "" },
        { term: "eat out", ipa: "" },
        { term: "give up", ipa: "" },
        { term: "join in", ipa: "" },
        { term: "send off", ipa: "" },
        { term: "take up", ipa: "" },
        { term: "turn down", ipa: "" },
        { term: "turn up", ipa: "" },
        { term: "for a long time", ipa: "" },
        { term: "for fun", ipa: "" },
        { term: "in the middle (of)", ipa: "" },
        { term: "in time (for)", ipa: "" },
        { term: "on CD/DVD/video", ipa: "" },
        { term: "on stage", ipa: "" },
        { term: "act", ipa: "" },
        { term: "action", ipa: "" },
        { term: "active", ipa: "" },
        { term: "inactive", ipa: "" },
        { term: "actor", ipa: "" },
        { term: "athlete", ipa: "" },
        { term: "athletic", ipa: "" },
        { term: "athletics", ipa: "" },
        { term: "child", ipa: "" },
        { term: "children", ipa: "" },
        { term: "childhood", ipa: "" },
        { term: "collect", ipa: "" },
        { term: "collection", ipa: "" },
        { term: "collector", ipa: "" },
        { term: "entertain", ipa: "" },
        { term: "entertainment", ipa: "" },
        { term: "hero", ipa: "" },
        { term: "heroic", ipa: "" },
        { term: "heroine", ipa: "" },
        { term: "music", ipa: "" },
        { term: "musical", ipa: "" },
        { term: "musician", ipa: "" },
        { term: "play", ipa: "" },
        { term: "player", ipa: "" },
        { term: "playful", ipa: "" },
        { term: "sail", ipa: "" },
        { term: "sailing", ipa: "" },
        { term: "sailor", ipa: "" },
        { term: "sing", ipa: "" },
        { term: "sang", ipa: "" },
        { term: "sung", ipa: "" },
        { term: "song", ipa: "" },
        { term: "singer", ipa: "" },
        { term: "singing", ipa: "" },
        { term: "bored with", ipa: "" },
        { term: "crazy about", ipa: "" },
        { term: "good at", ipa: "" },
        { term: "interested in", ipa: "" },
        { term: "keen on", ipa: "" },
        { term: "popular with", ipa: "" },
        { term: "feel like", ipa: "" },
        { term: "listen to", ipa: "" },
        { term: "take part in", ipa: "" },
        { term: "a book (by sb) about", ipa: "" },
        { term: "a fan of", ipa: "" },
        { term: "a game against", ipa: "" },
      ] },
    { step: 4, label: "R1", kind: "review", title: "Units 1, 2 and 3" },
    { step: 5, label: "4", kind: "grammar", title: "Present perfect simple, present perfect continuous" },
    { step: 6, label: "5", kind: "grammar", title: "Past perfect simple, past perfect continuous" },
    { step: 7, label: "6", kind: "vocabulary", title: "Learning and doing",
      words: [
        { term: "achieve", ipa: "" },
        { term: "brain", ipa: "" },
        { term: "clever", ipa: "" },
        { term: "concentrate", ipa: "" },
        { term: "consider", ipa: "" },
        { term: "course", ipa: "" },
        { term: "degree", ipa: "" },
        { term: "experience", ipa: "" },
        { term: "expert", ipa: "" },
        { term: "fail", ipa: "" },
        { term: "guess", ipa: "" },
        { term: "hesitate", ipa: "" },
        { term: "instruction", ipa: "" },
        { term: "make progress", ipa: "" },
        { term: "make sure", ipa: "" },
        { term: "mark", ipa: "" },
        { term: "mental", ipa: "" },
        { term: "pass", ipa: "" },
        { term: "qualification", ipa: "" },
        { term: "remind", ipa: "" },
        { term: "report", ipa: "" },
        { term: "revise", ipa: "" },
        { term: "search", ipa: "" },
        { term: "skill", ipa: "" },
        { term: "smart", ipa: "" },
        { term: "subject", ipa: "" },
        { term: "take an exam", ipa: "" },
        { term: "talented", ipa: "" },
        { term: "term", ipa: "" },
        { term: "wonder", ipa: "" },
        { term: "cross out", ipa: "" },
        { term: "look up", ipa: "" },
        { term: "point out", ipa: "" },
        { term: "read out", ipa: "" },
        { term: "rip up", ipa: "" },
        { term: "rub out", ipa: "" },
        { term: "turn over", ipa: "" },
        { term: "write down", ipa: "" },
        { term: "by heart", ipa: "" },
        { term: "for instance", ipa: "" },
        { term: "in conclusion", ipa: "" },
        { term: "in fact", ipa: "" },
        { term: "in favour (of)", ipa: "" },
        { term: "in general", ipa: "" },
        { term: "begin", ipa: "" },
        { term: "began", ipa: "" },
        { term: "begun", ipa: "" },
        { term: "beginner", ipa: "" },
        { term: "beginning", ipa: "" },
        { term: "brave", ipa: "" },
        { term: "bravery", ipa: "" },
        { term: "correct", ipa: "" },
        { term: "correction", ipa: "" },
        { term: "incorrect", ipa: "" },
        { term: "divide", ipa: "" },
        { term: "division", ipa: "" },
        { term: "educate", ipa: "" },
        { term: "education", ipa: "" },
        { term: "instruct", ipa: "" },
        { term: "instructor", ipa: "" },
        { term: "memory", ipa: "" },
        { term: "memorise", ipa: "" },
        { term: "memorial", ipa: "" },
        { term: "refer", ipa: "" },
        { term: "reference", ipa: "" },
        { term: "silent", ipa: "" },
        { term: "silence", ipa: "" },
        { term: "silently", ipa: "" },
        { term: "simple", ipa: "" },
        { term: "simplify", ipa: "" },
        { term: "simplicity", ipa: "" },
        { term: "capable of", ipa: "" },
        { term: "talented at", ipa: "" },
        { term: "cheat at/in", ipa: "" },
        { term: "confuse sth with", ipa: "" },
        { term: "continue with", ipa: "" },
        { term: "cope with", ipa: "" },
        { term: "help (sb) with", ipa: "" },
        { term: "know about", ipa: "" },
        { term: "learn about", ipa: "" },
        { term: "succeed in", ipa: "" },
        { term: "an opinion about/of", ipa: "" },
        { term: "a question about", ipa: "" },
      ] },
    { step: 8, label: "R2", kind: "review", title: "Units 4, 5 and 6" },
    { step: 9, label: "7", kind: "grammar", title: "Future time (present continuous, will, be going to, present simple)" },
    { step: 10, label: "8", kind: "grammar", title: "Prepositions of time and place" },
    { step: 11, label: "9", kind: "vocabulary", title: "Coming and going",
      words: [
        { term: "abroad", ipa: "" },
        { term: "accommodation", ipa: "" },
        { term: "book", ipa: "" },
        { term: "break", ipa: "" },
        { term: "cancel", ipa: "" },
        { term: "catch", ipa: "" },
        { term: "coach", ipa: "" },
        { term: "convenient", ipa: "" },
        { term: "crash", ipa: "" },
        { term: "crowded", ipa: "" },
        { term: "cruise", ipa: "" },
        { term: "delay", ipa: "" },
        { term: "destination", ipa: "" },
        { term: "ferry", ipa: "" },
        { term: "flight", ipa: "" },
        { term: "foreign", ipa: "" },
        { term: "harbour", ipa: "" },
        { term: "journey", ipa: "" },
        { term: "luggage", ipa: "" },
        { term: "nearby", ipa: "" },
        { term: "pack", ipa: "" },
        { term: "passport", ipa: "" },
        { term: "platform", ipa: "" },
        { term: "public transport", ipa: "" },
        { term: "reach", ipa: "" },
        { term: "resort", ipa: "" },
        { term: "souvenir", ipa: "" },
        { term: "traffic", ipa: "" },
        { term: "trip", ipa: "" },
        { term: "vehicle", ipa: "" },
        { term: "get in(to)", ipa: "" },
        { term: "get off", ipa: "" },
        { term: "get on(to)", ipa: "" },
        { term: "get out (of)", ipa: "" },
        { term: "go away", ipa: "" },
        { term: "go back (to)", ipa: "" },
        { term: "set off", ipa: "" },
        { term: "take off", ipa: "" },
        { term: "by air/sea/bus/car/etc", ipa: "" },
        { term: "on board", ipa: "" },
        { term: "on foot", ipa: "" },
        { term: "on holiday", ipa: "" },
        { term: "on schedule", ipa: "" },
        { term: "on the coast", ipa: "" },
        { term: "attract", ipa: "" },
        { term: "attractive", ipa: "" },
        { term: "attraction", ipa: "" },
        { term: "back", ipa: "" },
        { term: "backwards", ipa: "" },
        { term: "choose", ipa: "" },
        { term: "chose", ipa: "" },
        { term: "chosen", ipa: "" },
        { term: "choice", ipa: "" },
        { term: "comfort", ipa: "" },
        { term: "comfortable", ipa: "" },
        { term: "uncomfortable", ipa: "" },
        { term: "depart", ipa: "" },
        { term: "departure", ipa: "" },
        { term: "direct", ipa: "" },
        { term: "direction", ipa: "" },
        { term: "drive", ipa: "" },
        { term: "drove", ipa: "" },
        { term: "driven", ipa: "" },
        { term: "driver", ipa: "" },
        { term: "fly", ipa: "" },
        { term: "flew", ipa: "" },
        { term: "flown", ipa: "" },
        { term: "travel", ipa: "" },
        { term: "traveller", ipa: "" },
        { term: "visit", ipa: "" },
        { term: "visitor", ipa: "" },
        { term: "close to", ipa: "" },
        { term: "famous for", ipa: "" },
        { term: "far from", ipa: "" },
        { term: "late for", ipa: "" },
        { term: "suitable for", ipa: "" },
        { term: "arrive at/in", ipa: "" },
        { term: "ask (sb) about", ipa: "" },
        { term: "ask for", ipa: "" },
        { term: "look at", ipa: "" },
        { term: "prepare for", ipa: "" },
        { term: "provide sb with", ipa: "" },
        { term: "wait for", ipa: "" },
      ] },
    { step: 12, label: "R3", kind: "review", title: "Units 7, 8 and 9" },
    { step: 13, label: "10", kind: "grammar", title: "The passive 1" },
    { step: 14, label: "11", kind: "grammar", title: "The passive 2" },
    { step: 15, label: "12", kind: "vocabulary", title: "Friends and relations",
      words: [
        { term: "apologise", ipa: "" },
        { term: "boyfriend", ipa: "" },
        { term: "close", ipa: "" },
        { term: "confident", ipa: "" },
        { term: "cool", ipa: "" },
        { term: "couple", ipa: "" },
        { term: "decorate", ipa: "" },
        { term: "defend", ipa: "" },
        { term: "divorced", ipa: "" },
        { term: "flat", ipa: "" },
        { term: "generous", ipa: "" },
        { term: "girlfriend", ipa: "" },
        { term: "grateful", ipa: "" },
        { term: "guest", ipa: "" },
        { term: "independent", ipa: "" },
        { term: "introduce", ipa: "" },
        { term: "loving", ipa: "" },
        { term: "loyal", ipa: "" },
        { term: "mood", ipa: "" },
        { term: "neighbourhood", ipa: "" },
        { term: "ordinary", ipa: "" },
        { term: "patient", ipa: "" },
        { term: "private", ipa: "" },
        { term: "recognise", ipa: "" },
        { term: "relation", ipa: "" },
        { term: "rent", ipa: "" },
        { term: "respect", ipa: "" },
        { term: "single", ipa: "" },
        { term: "stranger", ipa: "" },
        { term: "trust", ipa: "" },
        { term: "bring up", ipa: "" },
        { term: "fall out (with)", ipa: "" },
        { term: "get on (with)", ipa: "" },
        { term: "go out with", ipa: "" },
        { term: "grow up", ipa: "" },
        { term: "let down", ipa: "" },
        { term: "look after", ipa: "" },
        { term: "split up", ipa: "" },
        { term: "by yourself", ipa: "" },
        { term: "in common (with)", ipa: "" },
        { term: "in contact (with)", ipa: "" },
        { term: "in love (with)", ipa: "" },
        { term: "on purpose", ipa: "" },
        { term: "on your own", ipa: "" },
        { term: "able", ipa: "" },
        { term: "ability", ipa: "" },
        { term: "disabled", ipa: "" },
        { term: "unable", ipa: "" },
        { term: "admire", ipa: "" },
        { term: "admiration", ipa: "" },
        { term: "care", ipa: "" },
        { term: "careful", ipa: "" },
        { term: "careless", ipa: "" },
        { term: "confidence", ipa: "" },
        { term: "forgive", ipa: "" },
        { term: "forgave", ipa: "" },
        { term: "forgiven", ipa: "" },
        { term: "forgiveness", ipa: "" },
        { term: "honest", ipa: "" },
        { term: "dishonest", ipa: "" },
        { term: "honesty", ipa: "" },
        { term: "introduction", ipa: "" },
        { term: "lie", ipa: "" },
        { term: "liar", ipa: "" },
        { term: "lying", ipa: "" },
        { term: "person", ipa: "" },
        { term: "personality", ipa: "" },
        { term: "personal", ipa: "" },
        { term: "relate", ipa: "" },
        { term: "relative", ipa: "" },
        { term: "relationship", ipa: "" },
        { term: "fond of", ipa: "" },
        { term: "jealous of", ipa: "" },
        { term: "kind to", ipa: "" },
        { term: "married to", ipa: "" },
        { term: "proud of", ipa: "" },
        { term: "admire sb for", ipa: "" },
        { term: "apologise (to sb) for", ipa: "" },
        { term: "argue (with sb) about", ipa: "" },
        { term: "care about", ipa: "" },
        { term: "chat (to sb) about", ipa: "" },
        { term: "an argument (with sb) about", ipa: "" },
        { term: "a relationship with", ipa: "" },
      ] },
    { step: 16, label: "R4", kind: "review", title: "Units 10, 11 and 12" },
    { step: 17, label: "13", kind: "grammar", title: "Countable and uncountable nouns" },
    { step: 18, label: "14", kind: "grammar", title: "Articles" },
    { step: 19, label: "15", kind: "vocabulary", title: "Buying and selling",
      words: [
        { term: "advertisement", ipa: "" },
        { term: "afford", ipa: "" },
        { term: "bargain", ipa: "" },
        { term: "brand", ipa: "" },
        { term: "catalogue", ipa: "" },
        { term: "change", ipa: "" },
        { term: "coin", ipa: "" },
        { term: "cost", ipa: "" },
        { term: "customer", ipa: "" },
        { term: "debt", ipa: "" },
        { term: "demand", ipa: "" },
        { term: "export", ipa: "" },
        { term: "fee", ipa: "" },
        { term: "fortune", ipa: "" },
        { term: "import", ipa: "" },
        { term: "invest", ipa: "" },
        { term: "obtain", ipa: "" },
        { term: "owe", ipa: "" },
        { term: "own", ipa: "" },
        { term: "profit", ipa: "" },
        { term: "property", ipa: "" },
        { term: "purchase", ipa: "" },
        { term: "receipt", ipa: "" },
        { term: "require", ipa: "" },
        { term: "sale", ipa: "" },
        { term: "save", ipa: "" },
        { term: "select", ipa: "" },
        { term: "supply", ipa: "" },
        { term: "variety", ipa: "" },
        { term: "waste", ipa: "" },
        { term: "add up", ipa: "" },
        { term: "come back (from)", ipa: "" },
        { term: "give away", ipa: "" },
        { term: "hurry up", ipa: "" },
        { term: "pay back", ipa: "" },
        { term: "save up (for)", ipa: "" },
        { term: "take back", ipa: "" },
        { term: "take down", ipa: "" },
        { term: "by credit card", ipa: "" },
        { term: "by cheque", ipa: "" },
        { term: "for rent", ipa: "" },
        { term: "for sale", ipa: "" },
        { term: "in cash", ipa: "" },
        { term: "in debt", ipa: "" },
        { term: "in good condition", ipa: "" },
        { term: "in bad condition", ipa: "" },
        { term: "add", ipa: "" },
        { term: "addition", ipa: "" },
        { term: "affordable", ipa: "" },
        { term: "compare", ipa: "" },
        { term: "comparison", ipa: "" },
        { term: "decide", ipa: "" },
        { term: "decision", ipa: "" },
        { term: "expense", ipa: "" },
        { term: "expensive", ipa: "" },
        { term: "inexpensive", ipa: "" },
        { term: "judge", ipa: "" },
        { term: "judgement", ipa: "" },
        { term: "serve", ipa: "" },
        { term: "service", ipa: "" },
        { term: "servant", ipa: "" },
        { term: "true", ipa: "" },
        { term: "truth", ipa: "" },
        { term: "untrue", ipa: "" },
        { term: "truthful", ipa: "" },
        { term: "use", ipa: "" },
        { term: "useful", ipa: "" },
        { term: "useless", ipa: "" },
        { term: "value", ipa: "" },
        { term: "valuable", ipa: "" },
        { term: "wrong about", ipa: "" },
        { term: "wrong with", ipa: "" },
        { term: "belong to", ipa: "" },
        { term: "borrow sth from", ipa: "" },
        { term: "buy sth from", ipa: "" },
        { term: "choose between", ipa: "" },
        { term: "compare sth to", ipa: "" },
        { term: "compare sth with", ipa: "" },
        { term: "decide on", ipa: "" },
        { term: "lend sth to", ipa: "" },
        { term: "pay for", ipa: "" },
        { term: "spend sth on", ipa: "" },
        { term: "an advert for", ipa: "" },
        { term: "an advertisement for", ipa: "" },
      ] },
    { step: 20, label: "R5", kind: "review", title: "Units 13, 14 and 15" },
    { step: 21, label: "16", kind: "grammar", title: "Pronouns and possessive determiners" },
    { step: 22, label: "17", kind: "grammar", title: "Relative clauses" },
    { step: 23, label: "18", kind: "vocabulary", title: "Inventions and discoveries",
      words: [
        { term: "artificial", ipa: "" },
        { term: "automatic", ipa: "" },
        { term: "complicated", ipa: "" },
        { term: "decrease", ipa: "" },
        { term: "digital", ipa: "" },
        { term: "discover", ipa: "" },
        { term: "effect", ipa: "" },
        { term: "equipment", ipa: "" },
        { term: "estimate", ipa: "" },
        { term: "exact", ipa: "" },
        { term: "experiment", ipa: "" },
        { term: "gadget", ipa: "" },
        { term: "hardware", ipa: "" },
        { term: "invent", ipa: "" },
        { term: "involve", ipa: "" },
        { term: "laboratory", ipa: "" },
        { term: "lack", ipa: "" },
        { term: "laptop", ipa: "" },
        { term: "maximum", ipa: "" },
        { term: "minimum", ipa: "" },
        { term: "operate", ipa: "" },
        { term: "plastic", ipa: "" },
        { term: "program", ipa: "" },
        { term: "research", ipa: "" },
        { term: "run", ipa: "" },
        { term: "screen", ipa: "" },
        { term: "software", ipa: "" },
        { term: "sudden", ipa: "" },
        { term: "technology", ipa: "" },
        { term: "unique", ipa: "" },
        { term: "break down", ipa: "" },
        { term: "come across", ipa: "" },
        { term: "find out", ipa: "" },
        { term: "make up", ipa: "" },
        { term: "pull off", ipa: "" },
        { term: "throw away", ipa: "" },
        { term: "turn off", ipa: "" },
        { term: "turn on", ipa: "" },
        { term: "at last", ipa: "" },
        { term: "by chance", ipa: "" },
        { term: "in my opinion", ipa: "" },
        { term: "in the end", ipa: "" },
        { term: "in the future", ipa: "" },
        { term: "out of order", ipa: "" },
        { term: "boil", ipa: "" },
        { term: "boiler", ipa: "" },
        { term: "boiling", ipa: "" },
        { term: "chemist", ipa: "" },
        { term: "chemical", ipa: "" },
        { term: "chemistry", ipa: "" },
        { term: "conclude", ipa: "" },
        { term: "conclusion", ipa: "" },
        { term: "examine", ipa: "" },
        { term: "exam", ipa: "" },
        { term: "examination", ipa: "" },
        { term: "examiner", ipa: "" },
        { term: "fascinate", ipa: "" },
        { term: "fascination", ipa: "" },
        { term: "fascinating", ipa: "" },
        { term: "history", ipa: "" },
        { term: "historic", ipa: "" },
        { term: "historian", ipa: "" },
        { term: "identical", ipa: "" },
        { term: "identically", ipa: "" },
        { term: "long", ipa: "" },
        { term: "length", ipa: "" },
        { term: "measure", ipa: "" },
        { term: "measurement", ipa: "" },
        { term: "science", ipa: "" },
        { term: "scientist", ipa: "" },
        { term: "different from", ipa: "" },
        { term: "different to", ipa: "" },
        { term: "full of", ipa: "" },
        { term: "begin sth with", ipa: "" },
        { term: "connect sth to", ipa: "" },
        { term: "connect sth with", ipa: "" },
        { term: "disconnect sth from", ipa: "" },
        { term: "fill sth with", ipa: "" },
        { term: "result in", ipa: "" },
        { term: "a difference between", ipa: "" },
        { term: "an idea about", ipa: "" },
        { term: "a number of", ipa: "" },
        { term: "a reason for", ipa: "" },
        { term: "a type of", ipa: "" },
      ] },
    { step: 24, label: "R6", kind: "review", title: "Units 16, 17 and 18" },
    { step: 25, label: "19", kind: "grammar", title: "Modals 1: ability, permission, advice" },
    { step: 26, label: "20", kind: "grammar", title: "Modals 2: obligation, probability, possibility" },
    { step: 27, label: "21", kind: "vocabulary", title: "Sending and receiving",
      words: [
        { term: "accent", ipa: "" },
        { term: "announcement", ipa: "" },
        { term: "broadcast", ipa: "" },
        { term: "channel", ipa: "" },
        { term: "clear", ipa: "" },
        { term: "click", ipa: "" },
        { term: "contact", ipa: "" },
        { term: "file", ipa: "" },
        { term: "formal", ipa: "" },
        { term: "image", ipa: "" },
        { term: "internet", ipa: "" },
        { term: "interrupt", ipa: "" },
        { term: "link", ipa: "" },
        { term: "media", ipa: "" },
        { term: "mobile phone", ipa: "" },
        { term: "online", ipa: "" },
        { term: "pause", ipa: "" },
        { term: "persuade", ipa: "" },
        { term: "pronounce", ipa: "" },
        { term: "publish", ipa: "" },
        { term: "report", ipa: "" },
        { term: "request", ipa: "" },
        { term: "ring", ipa: "" },
        { term: "signal", ipa: "" },
        { term: "swear", ipa: "" },
        { term: "type", ipa: "" },
        { term: "viewer", ipa: "" },
        { term: "website", ipa: "" },
        { term: "whisper", ipa: "" },
        { term: "call back", ipa: "" },
        { term: "come out", ipa: "" },
        { term: "cut off", ipa: "" },
        { term: "fill in", ipa: "" },
        { term: "hang up", ipa: "" },
        { term: "log off", ipa: "" },
        { term: "log on (to)", ipa: "" },
        { term: "print out", ipa: "" },
        { term: "by e-mail/phone/letter", ipa: "" },
        { term: "on the internet", ipa: "" },
        { term: "on the news", ipa: "" },
        { term: "on the phone", ipa: "" },
        { term: "on the radio", ipa: "" },
        { term: "on TV", ipa: "" },
        { term: "certain", ipa: "" },
        { term: "communicate", ipa: "" },
        { term: "connect", ipa: "" },
        { term: "deliver", ipa: "" },
        { term: "express", ipa: "" },
        { term: "inform", ipa: "" },
        { term: "predict", ipa: "" },
        { term: "secret", ipa: "" },
        { term: "speak", ipa: "" },
        { term: "translate", ipa: "" },
        { term: "comment on", ipa: "" },
        { term: "communicate with", ipa: "" },
        { term: "glance at", ipa: "" },
        { term: "receive sth from", ipa: "" },
        { term: "reply to", ipa: "" },
        { term: "send sth to sb", ipa: "" },
        { term: "talk (to sb) about", ipa: "" },
        { term: "tell sb about", ipa: "" },
        { term: "translate (from sth) into", ipa: "" },
        { term: "write (to sb) about", ipa: "" },
        { term: "information about", ipa: "" },
        { term: "a letter (from sb) about", ipa: "" },
      ] },
    { step: 28, label: "R7", kind: "review", title: "Units 19, 20 and 21" },
    { step: 29, label: "22", kind: "grammar", title: "Modals 3: the modal perfect" },
    { step: 30, label: "23", kind: "grammar", title: "Questions, question tags, indirect questions" },
    { step: 31, label: "24", kind: "vocabulary", title: "People and daily life",
      words: [
        { term: "admit", ipa: "" },
        { term: "arrest", ipa: "" },
        { term: "charity", ipa: "" },
        { term: "commit", ipa: "" },
        { term: "community", ipa: "" },
        { term: "court", ipa: "" },
        { term: "criminal", ipa: "" },
        { term: "culture", ipa: "" },
        { term: "familiar", ipa: "" },
        { term: "government", ipa: "" },
        { term: "habit", ipa: "" },
        { term: "identity card", ipa: "" },
        { term: "illegal", ipa: "" },
        { term: "politics", ipa: "" },
        { term: "population", ipa: "" },
        { term: "prison", ipa: "" },
        { term: "protest", ipa: "" },
        { term: "resident", ipa: "" },
        { term: "responsible", ipa: "" },
        { term: "rob", ipa: "" },
        { term: "routine", ipa: "" },
        { term: "schedule", ipa: "" },
        { term: "situation", ipa: "" },
        { term: "social", ipa: "" },
        { term: "society", ipa: "" },
        { term: "steal", ipa: "" },
        { term: "tradition", ipa: "" },
        { term: "typical", ipa: "" },
        { term: "vote", ipa: "" },
        { term: "youth club", ipa: "" },
        { term: "break in (to)", ipa: "" },
        { term: "catch up (with)", ipa: "" },
        { term: "get away with", ipa: "" },
        { term: "get up", ipa: "" },
        { term: "move in", ipa: "" },
        { term: "put away", ipa: "" },
        { term: "wake up", ipa: "" },
        { term: "wash up", ipa: "" },
        { term: "against the law", ipa: "" },
        { term: "at the age of", ipa: "" },
        { term: "in public", ipa: "" },
        { term: "in response to", ipa: "" },
        { term: "in touch (with)", ipa: "" },
        { term: "in your teens/twenties/etc", ipa: "" },
        { term: "agree", ipa: "" },
        { term: "belief", ipa: "" },
        { term: "courage", ipa: "" },
        { term: "elect", ipa: "" },
        { term: "equal", ipa: "" },
        { term: "life", ipa: "" },
        { term: "nation", ipa: "" },
        { term: "peace", ipa: "" },
        { term: "shoot", ipa: "" },
        { term: "angry (with sb) about", ipa: "" },
        { term: "guilty of", ipa: "" },
        { term: "accuse sb of", ipa: "" },
        { term: "blame sb for", ipa: "" },
        { term: "criticise sb for", ipa: "" },
        { term: "forget about", ipa: "" },
        { term: "forgive sb for", ipa: "" },
        { term: "invite sb to", ipa: "" },
        { term: "punish sb for", ipa: "" },
        { term: "share sth with", ipa: "" },
        { term: "smile at", ipa: "" },
      ] },
    { step: 32, label: "R8", kind: "review", title: "Units 22, 23 and 24" },
    { step: 33, label: "25", kind: "grammar", title: "So and such, too and enough" },
    { step: 34, label: "26", kind: "grammar", title: "Comparatives and superlatives" },
    { step: 35, label: "27", kind: "vocabulary", title: "Working and earning",
      words: [
        { term: "ambition", ipa: "" },
        { term: "application", ipa: "" },
        { term: "bank account", ipa: "" },
        { term: "boss", ipa: "" },
        { term: "career", ipa: "" },
        { term: "colleague", ipa: "" },
        { term: "company", ipa: "" },
        { term: "contract", ipa: "" },
        { term: "department", ipa: "" },
        { term: "deserve", ipa: "" },
        { term: "earn", ipa: "" },
        { term: "fame", ipa: "" },
        { term: "goal", ipa: "" },
        { term: "impress", ipa: "" },
        { term: "income", ipa: "" },
        { term: "industry", ipa: "" },
        { term: "interview", ipa: "" },
        { term: "leader", ipa: "" },
        { term: "manager", ipa: "" },
        { term: "pension", ipa: "" },
        { term: "poverty", ipa: "" },
        { term: "pressure", ipa: "" },
        { term: "previous", ipa: "" },
        { term: "profession", ipa: "" },
        { term: "retire", ipa: "" },
        { term: "salary", ipa: "" },
        { term: "staff", ipa: "" },
        { term: "tax", ipa: "" },
        { term: "talented", ipa: "" },
        { term: "wealthy", ipa: "" },
        { term: "call off", ipa: "" },
        { term: "give back", ipa: "" },
        { term: "go on", ipa: "" },
        { term: "put off", ipa: "" },
        { term: "set up", ipa: "" },
        { term: "stay up", ipa: "" },
        { term: "take away", ipa: "" },
        { term: "take over", ipa: "" },
        { term: "take on", ipa: "" },
        { term: "at the moment", ipa: "" },
        { term: "in charge (of)", ipa: "" },
        { term: "on business", ipa: "" },
        { term: "on strike", ipa: "" },
        { term: "on time", ipa: "" },
        { term: "on/off duty", ipa: "" },
        { term: "assist", ipa: "" },
        { term: "beg", ipa: "" },
        { term: "occupy", ipa: "" },
        { term: "office", ipa: "" },
        { term: "safe", ipa: "" },
        { term: "succeed", ipa: "" },
        { term: "bossy", ipa: "" },
        { term: "occupation", ipa: "" },
        { term: "successful", ipa: "" },
        { term: "famous", ipa: "" },
        { term: "retirement", ipa: "" },
        { term: "unemployed", ipa: "" },
        { term: "careful with", ipa: "" },
        { term: "difficult for", ipa: "" },
        { term: "fed up with", ipa: "" },
        { term: "ready for", ipa: "" },
        { term: "responsible for", ipa: "" },
        { term: "apply for", ipa: "" },
        { term: "depend on", ipa: "" },
        { term: "inform sb about", ipa: "" },
        { term: "refer to", ipa: "" },
        { term: "work as", ipa: "" },
        { term: "work for", ipa: "" },
        { term: "a kind of", ipa: "" },
      ] },
    { step: 36, label: "R9", kind: "review", title: "Units 25, 26 and 27" },
    { step: 37, label: "28", kind: "grammar", title: "Conditionals 1: (zero, first, second)" },
    { step: 38, label: "29", kind: "grammar", title: "Conditionals 2: (third)" },
    { step: 39, label: "30", kind: "vocabulary", title: "Body and lifestyle",
      words: [
        { term: "affect", ipa: "" },
        { term: "balance", ipa: "" },
        { term: "benefit", ipa: "" },
        { term: "breathe", ipa: "" },
        { term: "chew", ipa: "" },
        { term: "chop", ipa: "" },
        { term: "contain", ipa: "" },
        { term: "cough", ipa: "" },
        { term: "cure", ipa: "" },
        { term: "exercise", ipa: "" },
        { term: "flu", ipa: "" },
        { term: "have an operation", ipa: "" },
        { term: "healthy", ipa: "" },
        { term: "ignore", ipa: "" },
        { term: "infection", ipa: "" },
        { term: "ingredient", ipa: "" },
        { term: "injury", ipa: "" },
        { term: "limit", ipa: "" },
        { term: "meal", ipa: "" },
        { term: "pill", ipa: "" },
        { term: "recover", ipa: "" },
        { term: "salty", ipa: "" },
        { term: "slice", ipa: "" },
        { term: "sour", ipa: "" },
        { term: "spicy", ipa: "" },
        { term: "stir", ipa: "" },
        { term: "suffer", ipa: "" },
        { term: "taste", ipa: "" },
        { term: "treatment", ipa: "" },
        { term: "vitamin", ipa: "" },
        { term: "cut down (on)", ipa: "" },
        { term: "fall down", ipa: "" },
        { term: "get over", ipa: "" },
        { term: "go off", ipa: "" },
        { term: "lie down", ipa: "" },
        { term: "put on", ipa: "" },
        { term: "sit down", ipa: "" },
        { term: "stand up", ipa: "" },
        { term: "at night", ipa: "" },
        { term: "at risk", ipa: "" },
        { term: "in addition (to)", ipa: "" },
        { term: "in comparison to/with", ipa: "" },
        { term: "in shape", ipa: "" },
        { term: "on a diet", ipa: "" },
        { term: "bake", ipa: "" },
        { term: "baker", ipa: "" },
        { term: "bakery", ipa: "" },
        { term: "bend", ipa: "" },
        { term: "bent", ipa: "" },
        { term: "cook", ipa: "" },
        { term: "cooker", ipa: "" },
        { term: "cookery", ipa: "" },
        { term: "intend", ipa: "" },
        { term: "intention", ipa: "" },
        { term: "intentional", ipa: "" },
        { term: "jog", ipa: "" },
        { term: "jogging", ipa: "" },
        { term: "jogger", ipa: "" },
        { term: "medicine", ipa: "" },
        { term: "medical", ipa: "" },
        { term: "pain", ipa: "" },
        { term: "painful", ipa: "" },
        { term: "painless", ipa: "" },
        { term: "reduce", ipa: "" },
        { term: "reduction", ipa: "" },
        { term: "sense", ipa: "" },
        { term: "sensible", ipa: "" },
        { term: "sensitive", ipa: "" },
        { term: "weigh", ipa: "" },
        { term: "weight", ipa: "" },
        { term: "addicted to", ipa: "" },
        { term: "allergic to", ipa: "" },
        { term: "covered in/with", ipa: "" },
        { term: "pleased with", ipa: "" },
        { term: "combine sth with", ipa: "" },
        { term: "complain (to sb) about", ipa: "" },
        { term: "die from/of", ipa: "" },
        { term: "fight against", ipa: "" },
        { term: "recover from", ipa: "" },
        { term: "smell of", ipa: "" },
        { term: "a cure for", ipa: "" },
        { term: "a recipe for", ipa: "" },
      ] },
    { step: 40, label: "R10", kind: "review", title: "Units 28, 29 and 30" },
    { step: 41, label: "31", kind: "grammar", title: "Reported speech" },
    { step: 42, label: "32", kind: "grammar", title: "Reported questions, orders, requests" },
    { step: 43, label: "33", kind: "vocabulary", title: "Creating and building",
      words: [
        { term: "ancient", ipa: "" },
        { term: "checked", ipa: "" },
        { term: "cotton", ipa: "" },
        { term: "create", ipa: "" },
        { term: "design", ipa: "" },
        { term: "fix", ipa: "" },
        { term: "fold", ipa: "" },
        { term: "gallery", ipa: "" },
        { term: "improvement", ipa: "" },
        { term: "loose", ipa: "" },
        { term: "maintain", ipa: "" },
        { term: "match", ipa: "" },
        { term: "material", ipa: "" },
        { term: "notice", ipa: "" },
        { term: "pattern", ipa: "" },
        { term: "pile", ipa: "" },
        { term: "practical", ipa: "" },
        { term: "rough", ipa: "" },
        { term: "shape", ipa: "" },
        { term: "silk", ipa: "" },
        { term: "sleeve", ipa: "" },
        { term: "smooth", ipa: "" },
        { term: "stretch", ipa: "" },
        { term: "striped", ipa: "" },
        { term: "style", ipa: "" },
        { term: "suit", ipa: "" },
        { term: "suitable", ipa: "" },
        { term: "tear", ipa: "" },
        { term: "tight", ipa: "" },
        { term: "tool", ipa: "" },
        { term: "cut off", ipa: "" },
        { term: "do up", ipa: "" },
        { term: "fill up", ipa: "" },
        { term: "have on", ipa: "" },
        { term: "leave out", ipa: "" },
        { term: "put on", ipa: "" },
        { term: "take off", ipa: "" },
        { term: "try on", ipa: "" },
        { term: "at the back (of)", ipa: "" },
        { term: "at the end (of)", ipa: "" },
        { term: "in fashion/style", ipa: "" },
        { term: "in front (of)", ipa: "" },
        { term: "in the corner (of)", ipa: "" },
        { term: "out of fashion/style", ipa: "" },
        { term: "art", ipa: "" },
        { term: "artist", ipa: "" },
        { term: "artistic", ipa: "" },
        { term: "break", ipa: "" },
        { term: "broke", ipa: "" },
        { term: "broken", ipa: "" },
        { term: "(un)breakable", ipa: "" },
        { term: "compose", ipa: "" },
        { term: "composition", ipa: "" },
        { term: "composer", ipa: "" },
        { term: "exhibit", ipa: "" },
        { term: "exhibition", ipa: "" },
        { term: "free", ipa: "" },
        { term: "freedom", ipa: "" },
        { term: "hand", ipa: "" },
        { term: "handful", ipa: "" },
        { term: "handle", ipa: "" },
        { term: "imagine", ipa: "" },
        { term: "imagination", ipa: "" },
        { term: "imaginative", ipa: "" },
        { term: "intelligent", ipa: "" },
        { term: "intelligence", ipa: "" },
        { term: "perfect", ipa: "" },
        { term: "perfection", ipa: "" },
        { term: "imperfect", ipa: "" },
        { term: "prepare", ipa: "" },
        { term: "preparation", ipa: "" },
        { term: "amazed at/by", ipa: "" },
        { term: "disappointed with", ipa: "" },
        { term: "familiar with", ipa: "" },
        { term: "involved in", ipa: "" },
        { term: "similar to", ipa: "" },
        { term: "change sth (from sth) into", ipa: "" },
        { term: "describe sth as", ipa: "" },
        { term: "explain sth to", ipa: "" },
        { term: "remind sb of", ipa: "" },
        { term: "remove sth from", ipa: "" },
        { term: "an influence on", ipa: "" },
        { term: "a picture of", ipa: "" },
      ] },
    { step: 44, label: "R11", kind: "review", title: "Units 31, 32 and 33" },
    { step: 45, label: "34", kind: "grammar", title: "Direct and indirect objects" },
    { step: 46, label: "35", kind: "grammar", title: "wish" },
    { step: 47, label: "36", kind: "vocabulary", title: "Nature and the universe",
      words: [
        { term: "amazing", ipa: "" },
        { term: "climate", ipa: "" },
        { term: "countryside", ipa: "" },
        { term: "environment", ipa: "" },
        { term: "extinct", ipa: "" },
        { term: "forecast", ipa: "" },
        { term: "freezing", ipa: "" },
        { term: "global", ipa: "" },
        { term: "heatwave", ipa: "" },
        { term: "insect", ipa: "" },
        { term: "lightning", ipa: "" },
        { term: "litter", ipa: "" },
        { term: "local", ipa: "" },
        { term: "locate", ipa: "" },
        { term: "mammal", ipa: "" },
        { term: "mild", ipa: "" },
        { term: "name", ipa: "" },
        { term: "origin", ipa: "" },
        { term: "planet", ipa: "" },
        { term: "preserve", ipa: "" },
        { term: "recycle", ipa: "" },
        { term: "reptile", ipa: "" },
        { term: "rescue", ipa: "" },
        { term: "satellite", ipa: "" },
        { term: "shower", ipa: "" },
        { term: "solar system", ipa: "" },
        { term: "species", ipa: "" },
        { term: "thunder", ipa: "" },
        { term: "wild", ipa: "" },
        { term: "wildlife", ipa: "" },
        { term: "blow up", ipa: "" },
        { term: "build up", ipa: "" },
        { term: "clear up", ipa: "" },
        { term: "go out", ipa: "" },
        { term: "keep out", ipa: "" },
        { term: "put down", ipa: "" },
        { term: "put out", ipa: "" },
        { term: "put up", ipa: "" },
        { term: "at most", ipa: "" },
        { term: "at the top/bottom (of)", ipa: "" },
        { term: "in the beginning", ipa: "" },
        { term: "in the distance", ipa: "" },
        { term: "in total", ipa: "" },
        { term: "on top (of)", ipa: "" },
        { term: "centre", ipa: "" },
        { term: "central", ipa: "" },
        { term: "circle", ipa: "" },
        { term: "circular", ipa: "" },
        { term: "danger", ipa: "" },
        { term: "dangerous", ipa: "" },
        { term: "deep", ipa: "" },
        { term: "deeply", ipa: "" },
        { term: "depth", ipa: "" },
        { term: "destroy", ipa: "" },
        { term: "destruction", ipa: "" },
        { term: "destructive", ipa: "" },
        { term: "fog", ipa: "" },
        { term: "foggy", ipa: "" },
        { term: "garden", ipa: "" },
        { term: "gardener", ipa: "" },
        { term: "gardening", ipa: "" },
        { term: "invade", ipa: "" },
        { term: "invasion", ipa: "" },
        { term: "invader", ipa: "" },
        { term: "nature", ipa: "" },
        { term: "natural", ipa: "" },
        { term: "naturally", ipa: "" },
        { term: "pollute", ipa: "" },
        { term: "pollution", ipa: "" },
        { term: "polluted", ipa: "" },
        { term: "afraid of", ipa: "" },
        { term: "aware of", ipa: "" },
        { term: "enthusiastic about", ipa: "" },
        { term: "serious about", ipa: "" },
        { term: "short of", ipa: "" },
        { term: "escape from", ipa: "" },
        { term: "prevent sb from", ipa: "" },
        { term: "save sth from", ipa: "" },
        { term: "think about", ipa: "" },
        { term: "worry about", ipa: "" },
        { term: "damage to", ipa: "" },
        { term: "an increase in", ipa: "" },
      ] },
    { step: 48, label: "R12", kind: "review", title: "Units 34, 35 and 36" },
    { step: 49, label: "37", kind: "grammar", title: "-ing and infinitive" },
    { step: 50, label: "38", kind: "grammar", title: "Both, either, neither, so, nor" },
    { step: 51, label: "39", kind: "vocabulary", title: "Laughing and crying",
      words: [
        { term: "amusing", ipa: "" },
        { term: "annoy", ipa: "" },
        { term: "attitude", ipa: "" },
        { term: "bad-tempered", ipa: "" },
        { term: "behave", ipa: "" },
        { term: "bully", ipa: "" },
        { term: "calm", ipa: "" },
        { term: "celebrate", ipa: "" },
        { term: "character", ipa: "" },
        { term: "depressed", ipa: "" },
        { term: "embarrassing", ipa: "" },
        { term: "emotion", ipa: "" },
        { term: "enthusiastic", ipa: "" },
        { term: "feeling", ipa: "" },
        { term: "glad", ipa: "" },
        { term: "hurt", ipa: "" },
        { term: "miserable", ipa: "" },
        { term: "naughty", ipa: "" },
        { term: "noisy", ipa: "" },
        { term: "polite", ipa: "" },
        { term: "react", ipa: "" },
        { term: "regret", ipa: "" },
        { term: "ridiculous", ipa: "" },
        { term: "romantic", ipa: "" },
        { term: "rude", ipa: "" },
        { term: "sense of humour", ipa: "" },
        { term: "shy", ipa: "" },
        { term: "stress", ipa: "" },
        { term: "tell a joke", ipa: "" },
        { term: "upset", ipa: "" },
        { term: "calm down", ipa: "" },
        { term: "cheer up", ipa: "" },
        { term: "come on", ipa: "" },
        { term: "go on", ipa: "" },
        { term: "hang on", ipa: "" },
        { term: "run away (from)", ipa: "" },
        { term: "shut up", ipa: "" },
        { term: "speak up", ipa: "" },
        { term: "at first", ipa: "" },
        { term: "at least", ipa: "" },
        { term: "at times", ipa: "" },
        { term: "in secret", ipa: "" },
        { term: "in spite of", ipa: "" },
        { term: "in tears", ipa: "" },
        { term: "bore", ipa: "" },
        { term: "boring", ipa: "" },
        { term: "bored", ipa: "" },
        { term: "comedy", ipa: "" },
        { term: "comedian", ipa: "" },
        { term: "emotional", ipa: "" },
        { term: "energy", ipa: "" },
        { term: "energetic", ipa: "" },
        { term: "excite", ipa: "" },
        { term: "excitement", ipa: "" },
        { term: "exciting", ipa: "" },
        { term: "excited", ipa: "" },
        { term: "feel", ipa: "" },
        { term: "felt", ipa: "" },
        { term: "feelings", ipa: "" },
        { term: "happy", ipa: "" },
        { term: "unhappy", ipa: "" },
        { term: "happiness", ipa: "" },
        { term: "unhappiness", ipa: "" },
        { term: "hate", ipa: "" },
        { term: "hatred", ipa: "" },
        { term: "noise", ipa: "" },
        { term: "noisily", ipa: "" },
        { term: "sympathy", ipa: "" },
        { term: "sympathise", ipa: "" },
        { term: "sympathetic", ipa: "" },
        { term: "ashamed of", ipa: "" },
        { term: "embarrassed about", ipa: "" },
        { term: "frightened of", ipa: "" },
        { term: "happy about/with", ipa: "" },
        { term: "nervous about", ipa: "" },
        { term: "scared of", ipa: "" },
        { term: "sorry about/for", ipa: "" },
        { term: "surprised at/by", ipa: "" },
        { term: "tired of", ipa: "" },
        { term: "congratulate sb on", ipa: "" },
        { term: "laugh at", ipa: "" },
        { term: "a joke about", ipa: "" },
      ] },
    { step: 52, label: "R13", kind: "review", title: "Units 37, 38 and 39" },
    { step: 53, label: "40", kind: "grammar", title: "Connectives" },
    { step: 54, label: "41", kind: "grammar", title: "The causative" },
    { step: 55, label: "42", kind: "vocabulary", title: "Problems and solutions",
      words: [
        { term: "accident", ipa: "" },
        { term: "assume", ipa: "" },
        { term: "cause", ipa: "" },
        { term: "claim", ipa: "" },
        { term: "complain", ipa: "" },
        { term: "convince", ipa: "" },
        { term: "criticise", ipa: "" },
        { term: "deny", ipa: "" },
        { term: "discussion", ipa: "" },
        { term: "doubt", ipa: "" },
        { term: "encourage", ipa: "" },
        { term: "get rid of", ipa: "" },
        { term: "gossip", ipa: "" },
        { term: "ideal", ipa: "" },
        { term: "insult", ipa: "" },
        { term: "investigate", ipa: "" },
        { term: "negative", ipa: "" },
        { term: "positive", ipa: "" },
        { term: "praise", ipa: "" },
        { term: "pretend", ipa: "" },
        { term: "purpose", ipa: "" },
        { term: "refuse", ipa: "" },
        { term: "result", ipa: "" },
        { term: "rumour", ipa: "" },
        { term: "sensible", ipa: "" },
        { term: "serious", ipa: "" },
        { term: "spare", ipa: "" },
        { term: "theory", ipa: "" },
        { term: "thought", ipa: "" },
        { term: "warn", ipa: "" },
        { term: "hang up", ipa: "" },
        { term: "pick up", ipa: "" },
        { term: "put back", ipa: "" },
        { term: "run out (of)", ipa: "" },
        { term: "share out", ipa: "" },
        { term: "sort out", ipa: "" },
        { term: "watch out", ipa: "" },
        { term: "work out", ipa: "" },
        { term: "by accident", ipa: "" },
        { term: "by mistake", ipa: "" },
        { term: "in a mess", ipa: "" },
        { term: "in danger (of)", ipa: "" },
        { term: "in my view", ipa: "" },
        { term: "in trouble", ipa: "" },
        { term: "under pressure", ipa: "" },
        { term: "advice", ipa: "" },
        { term: "advise", ipa: "" },
        { term: "adviser", ipa: "" },
        { term: "confuse", ipa: "" },
        { term: "confused", ipa: "" },
        { term: "confusion", ipa: "" },
        { term: "except", ipa: "" },
        { term: "exception", ipa: "" },
        { term: "help", ipa: "" },
        { term: "helpful", ipa: "" },
        { term: "unhelpful", ipa: "" },
        { term: "helpless", ipa: "" },
        { term: "luck", ipa: "" },
        { term: "lucky", ipa: "" },
        { term: "unlucky", ipa: "" },
        { term: "luckily", ipa: "" },
        { term: "unluckily", ipa: "" },
        { term: "prefer", ipa: "" },
        { term: "preference", ipa: "" },
        { term: "preferable", ipa: "" },
        { term: "recommend", ipa: "" },
        { term: "recommendation", ipa: "" },
        { term: "refusal", ipa: "" },
        { term: "solve", ipa: "" },
        { term: "solution", ipa: "" },
        { term: "suggest", ipa: "" },
        { term: "suggestion", ipa: "" },
        { term: "sure about/of", ipa: "" },
        { term: "advise against", ipa: "" },
        { term: "agree with", ipa: "" },
        { term: "approve of", ipa: "" },
        { term: "believe in", ipa: "" },
        { term: "deal with", ipa: "" },
        { term: "happen to", ipa: "" },
        { term: "hide sth from sb", ipa: "" },
        { term: "insist on", ipa: "" },
        { term: "rely on", ipa: "" },
        { term: "an advantage of", ipa: "" },
        { term: "a solution to", ipa: "" },
      ] },
    { step: 56, label: "R14", kind: "review", title: "Units 40, 41 and 42" },
  ],
};
